Repository AliceO2Group/Bookkeeping, pull requests merged in 2021-11, with the labels that each got.

#442 [O2B-457] Dockerfile updates and lint fixes
  Dockerfile
  lib/public/views/Runs/Runs.js
Labels: docker, frontend

#450 [O2B-458] Dependencies and dependabot configuration updates
  .github/dependabot.yml
  package-lock.json
  package.json
  test/e2e/logs.test.js
  test/e2e/subsystems.test.js
  test/e2e/tags.test.js
Labels: dependencies

#438 [O2B-447] Removed main panel and modified router params to point to logs panel.
  lib/public/views/Tags/Details/index.js
  test/public/tags/detail.test.js
Labels: frontend

#440 [O2B-438] Moved main logs table to the right of the screen.
  lib/public/views/Runs/Details/index.js
  test/public/flps/detail.test.js
  test/public/logs/detail.test.js
  test/public/runs/detail.test.js
Labels: frontend
