Repository AliceO2Group/Bookkeeping, pull requests merged in 2021-12, with the labels that each got.

#441 [O2B-425] Replies are backend validated
  lib/domain/dtos/CreateLogDto.js
  lib/public/views/Logs/ActiveColumns/index.js
  spec/openapi-source.yaml
  spec/openapi.yaml
  test/e2e/logs.test.js
  test/public/home/overview.test.js
  test/usecases/log/CreateLogUseCase.test.js
Labels: backend

#455 Prepare release notes for 0.18.0
  CHANGELOG.md
  lib/public/views/About/Overview/index.js
  package-lock.json
  package.json
Labels: documentation

#456 [O2B-459] Migrate to js-yaml v4
  lib/public/views/Tags/Overview/index.js
  package-lock.json
  package.json
  spec/convert.js
  spec/openapi-source.yaml
  spec/openapi.yaml
  test/openapi.test.js
Labels: CI

#458 [O2B-468] Add token to download link of attachment
  lib/public/components/Post/index.js
Labels: frontend

#459 [O2B-467] Add Bookkeping GH templates and extend on current workflows
  .github/CODEOWNERS
  .github/pull_request_template.md
  .github/workflows/release.yml
  package.json
Labels: CI

#460 [O2B-469] Update configs with in-line condition
  lib/config/database.js
  lib/config/jwt.js
  lib/config/openid.js
Labels: backend
