Repository AliceO2Group/Bookkeeping, pull requests merged in 2022-05, with the labels that each got.

#557 [O2B-526] New environment database model
  database/configuration/my.cnf
  lib/database/adapters/EnvironmentAdapter.js
  lib/database/adapters/RunAdapter.js
  lib/database/adapters/index.js
  lib/database/migrations/20220404093143-create-environments-table.js
  lib/database/migrations/20220412121531-create-env-id-for-runs.js
  lib/database/models/environment.js
  lib/database/models/index.js
  lib/database/models/run.js
  lib/database/repositories/EnvironmentRepository.js
  lib/database/repositories/index.js
  lib/database/seeders/20200713103855-runs.js
  lib/database/seeders/20220412122043-environments.js
Labels: backend, db

#579 [O2B-571] Tag edit mode saves old edit data on page switch
  lib/public/components/TagDetail/index.js
  lib/public/views/Tags/Details/index.js
Labels: frontend

#581 [O2B-567] Migrate runs.detectors to string type
  lib/database/migrations/20220511102048-update-run-detectors-column.js
  lib/domain/dtos/StartRunDto.js
  spec/openapi-source.yaml
  spec/openapi.yaml
  test/e2e/runs.test.js
  test/usecases/run/StartRunUseCase.test.js
  test/usecases/run/index.js
Labels: backend, db

#587 [O2B-576] Adapt retrieval of run to include eor
  lib/database/adapters/EorReasonAdapter.js
  lib/database/adapters/RunAdapter.js
  lib/usecases/run/GetRunUseCase.js
  spec/openapi-source.yaml
  spec/openapi.yaml
  test/openapi.test.js
  test/usecases/run/GetRunUseCase.test.js
Labels: backend

#596 [O2B-566] Add frontend widgets for eor reasons selection and removal
  lib/public/Model.js
  lib/public/components/RunDetail/index.js
  lib/public/views/Runs/Details/index.js
  lib/public/views/Runs/Runs.js
  lib/server/controllers/runs.controller.js
Labels: frontend

#575 [O2B-494] Extended db schema and created the lhcfills schema
  docs/data-model.md
  lib/database/adapters/LhcFillAdapter.js
  lib/database/adapters/RunAdapter.js
  lib/database/adapters/index.js
  lib/database/migrations/20220503095951-run-lhc-variables.js
  lib/database/migrations/20220503101937-lhc-fills-table-creation.js
  lib/database/models/index.js
  lib/database/models/lhcFill.js
  lib/database/models/run.js
  lib/database/repositories/LhcFillRepository.js
  lib/database/repositories/index.js
  lib/database/seeders/20200713103855-runs.js
  lib/database/seeders/20220503120937-lhc-fills.js
  spec/openapi-source.yaml
  spec/openapi.yaml
Labels: backend, db

#598 [O2B-572] Update freetype
  Dockerfile
Labels: docker

#583 [O2B-495] Update run by run number
  lib/database/adapters/RunAdapter.js
  lib/domain/dtos/GetLhcFillDto.js
  lib/domain/dtos/UpdateRunByRunNumberDto.js
  lib/domain/dtos/index.js
  lib/server/controllers/runs.controller.js
  lib/server/routers/runs.router.js
  lib/usecases/index.js
  lib/usecases/lhcFill/GetLhcFillUseCase.js
  lib/usecases/lhcFill/index.js
  lib/usecases/run/EndRunUseCase.js
  lib/usecases/run/UpdateRunUseCase.js
  spec/openapi-source.yaml
  spec/openapi.yaml
  test/e2e/runs.test.js
  test/usecases/index.js
  test/usecases/lhcFill/GetLhcFillUseCase.test.js
  test/usecases/lhcFill/index.js
  test/usecases/run/EndRunUseCase.test.js
  test/usecases/run/UpdateRunUseCase.test.js
  test/usecases/run/index.js
Labels: backend, db

#591 [O2B-493] LhcFill endpoints
  lib/database/models/run.js
  lib/database/seeders/20220503120937-lhc-fills.js
  lib/domain/dtos/CreateLhcFillDto.js
  lib/domain/dtos/GetAllLhcFillsDto.js
  lib/domain/dtos/GetLhcFillRunDto.js
  lib/domain/dtos/UpdateLhcFillDto.js
  lib/domain/dtos/index.js
  lib/server/controllers/index.js
  lib/server/controllers/lhcFill.controller.js
  lib/server/controllers/runs.controller.js
  lib/server/routers/index.js
  lib/server/routers/lhcFills.router.js
  lib/usecases/lhcFill/CreateLhcFillUseCase.js
  lib/usecases/lhcFill/GetAllLhcFillsUseCase.js
  lib/usecases/lhcFill/GetLhcFillRunByRunNumberUseCase.js
  lib/usecases/lhcFill/GetLhcFillRunsUseCase.js
  lib/usecases/lhcFill/UpdateLhcFillUseCase.js
  lib/usecases/lhcFill/index.js
  spec/openapi-source.yaml
  spec/openapi.yaml
  test/e2e/index.js
  test/e2e/lhcFills.test.js
  test/e2e/runs.test.js
  test/usecases/index.js
  test/usecases/lhcFill/CreateLhcFillUseCase.test.js
  test/usecases/lhcFill/GetAllLhcFillsUseCase.test.js
  test/usecases/lhcFill/GetLhcFillRunByRunNumberUseCase.test.js
  test/usecases/lhcFill/GetLhcFillUseCase.test.js
  test/usecases/lhcFill/UpdateLhcFillUseCase.test.js
  test/usecases/lhcFill/index.js
  test/usecases/run/index.js
Labels: backend, db

#600 Release notes 0.28.0
  CHANGELOG.md
  database/CHANGELOG.md
  lib/public/views/About/Overview/index.js
  package-lock.json
  package.json
Labels: release
