Repository AliceO2Group/Bookkeeping, pull requests merged in 2022-07, with the labels that each got.

#637 [O2B-610] Fix runs infinite mode
  lib/public/utilities/parseFetchResponse.js
  lib/public/views/Runs/Runs.js
Labels: bug, frontend

#644 Update CODEOWNERS
  .github/CODEOWNERS
Labels: documentation

#643 [O2B-636] Fix debounced filtering
  lib/public/components/Filters/LogsFilter/created.js
  lib/public/components/Filters/RunsFilter/o2start.js
  lib/public/components/Filters/RunsFilter/o2stop.js
  lib/public/views/Logs/Logs.js
  lib/public/views/Runs/Runs.js
Labels: frontend

#646 [O2B-641] Replace master by main in CI
  .github/workflows/bookkeeping.yml
  .github/workflows/docker.yml
  .github/workflows/openapi.yml
Labels: CI

#633 [O2B-620] Add run duration to details page + bug fixes
  lib/public/components/Detail/index.js
  lib/public/components/RunDetail/index.js
  lib/public/components/lhcFillsDetail/index.js
  lib/public/utilities/formatTimestamp.js
  lib/public/views/Runs/ActiveColumns/index.js
  lib/public/views/Runs/formatRunDuration.js
Labels: frontend

#648 [O2B-523] Fix filtering in infinite mode for runs and logs
  lib/public/utilities/debounce.js
  lib/public/views/Logs/Logs.js
  lib/public/views/Runs/Runs.js
  test/public/logs/overview.test.js
  test/public/runs/overview.test.js
Labels: frontend

#645 [O2B-639] Add new info from Core to Run-Details
  CHANGELOG.md
  database/CHANGELOG.md
  docs/data-model.md
  lib/public/components/Detail/index.js
  lib/public/components/RunDetail/index.js
  lib/public/components/lhcFillsDetail/index.js
  lib/public/utilities/formatBoolean.js
Labels: frontend

#651 Release of : 0.32.0
  CHANGELOG.md
  lib/public/views/About/Overview/index.js
  package-lock.json
  package.json
Labels: release

#652 [O2B-647] Fix run duration displaying UNKNOWN above 48h
  lib/public/views/Runs/formatRunDuration.js
Labels: bug, frontend

#653 [O2B-648] Fill number information on run overview
  lib/domain/dtos/GetAllRunsDto.js
  lib/public/components/Filters/RunsFilter/fillNumbers.js
  lib/public/views/Runs/ActiveColumns/index.js
  lib/public/views/Runs/Runs.js
  lib/usecases/run/GetAllRunsUseCase.js
  test/public/runs/overview.test.js
  test/usecases/run/GetAllRunsUseCase.test.js
Labels: frontend, backend

#654 Add release notes for 0.33.0
  CHANGELOG.md
  lib/public/views/About/Overview/index.js
  package-lock.json
  package.json
Labels: release

#655 [O2B-645] Include tags update in run update
  CHANGELOG.md
  lib/database/repositories/RunTagsRepository.js
  lib/domain/dtos/UpdateRunDto.js
  lib/domain/dtos/UpdateRunTagsDto.js
  lib/domain/dtos/index.js
  lib/public/views/Runs/Details/editTagsPanel.js
  lib/public/views/Runs/Runs.js
  lib/server/controllers/runs.controller.js
  lib/server/routers/runs.router.js
  lib/usecases/run/UpdateRunTagsUseCase.js
  lib/usecases/run/UpdateRunUseCase.js
  lib/usecases/run/index.js
  spec/openapi-source.yaml
  spec/openapi.yaml
  test/e2e/runs.test.js
  test/public/logs/create.test.js
  test/public/runs/detail.test.js
Labels: frontend, backend

#636 [O2B-619] Refactor table to be model-independent
  lib/public/components/Table/SortModel.js
  lib/public/components/Table/headers.js
  lib/public/components/Table/index.js
  lib/public/components/Table/rows.js
  lib/public/views/About/Overview/index.js
  lib/public/views/Envs/Overview/index.js
  lib/public/views/Flps/Overview/index.js
  lib/public/views/Home/Overview/index.js
  lib/public/views/LhcFills/Overview/index.js
  lib/public/views/Logs/Logs.js
  lib/public/views/Logs/Overview/index.js
  lib/public/views/Runs/Details/index.js
  lib/public/views/Runs/Overview/index.js
  lib/public/views/Subsystems/Details/index.js
  lib/public/views/Subsystems/Overview/index.js
  lib/public/views/Tags/ActiveColumns/index.js
  lib/public/views/Tags/Details/index.js
  lib/public/views/Tags/Overview/index.js
  test/public/logs/create.test.js
  test/public/logs/overview.test.js
Labels: frontend

#635 [O2B-619] Inform user when table data is loading
  lib/public/Model.js
  lib/public/views/Envs/Envs.js
  lib/public/views/Envs/Overview/index.js
  lib/public/views/Flps/Flps.js
  lib/public/views/Flps/Overview/index.js
  lib/public/views/Home/Overview/index.js
  lib/public/views/LhcFills/Overview/index.js
  lib/public/views/Logs/Overview/index.js
  lib/public/views/Runs/Details/index.js
  lib/public/views/Runs/Overview/index.js
  lib/public/views/Subsystems/Details/index.js
  lib/public/views/Subsystems/Overview/index.js
  lib/public/views/Tags/Details/index.js
  lib/public/views/Tags/Overview/TagsOverviewModel.js
  lib/public/views/Tags/Overview/index.js
  lib/usecases/flp/GetAllFlpsUseCase.js
  lib/utilities/setPromiseTimeout.js
  test/public/tags/overview.test.js
Labels: frontend

#656 [O2B-644] Create getTagsByTextsUseCase and use it in other use cases
  CHANGELOG.md
  lib/database/repositories/LogTagsRepository.js
  lib/database/repositories/Repository.js
  lib/database/repositories/RunTagsRepository.js
  lib/database/utilities/groupByProperty.js
  lib/domain/dtos/CreateLogDto.js
  lib/domain/dtos/CustomJoi.js
  lib/domain/dtos/GetAllLogsDto.js
  lib/domain/dtos/GetAllRunsDto.js
  lib/domain/dtos/UpdateRunDto.js
  lib/domain/dtos/filters/TagsFilterDto.js
  lib/public/views/Logs/Logs.js
  lib/public/views/Runs/Runs.js
  lib/server/controllers/logs.controller.js
  lib/server/controllers/runs.controller.js
  lib/server/controllers/tags.controller.js
  lib/usecases/log/CreateLogUseCase.js
  lib/usecases/log/GetAllLogsUseCase.js
  lib/usecases/run/EndRunUseCase.js
  lib/usecases/run/GetAllRunsUseCase.js
  lib/usecases/run/UpdateRunUseCase.js
  lib/usecases/tag/GetLogsByTagUseCase.js
  lib/usecases/tag/getTagsByTextsUseCase.js
  lib/usecases/tag/index.js
  spec/openapi-source.yaml
  spec/openapi.yaml
  test/e2e/logs.test.js
  test/public/runs/overview.test.js
  test/usecases/log/CreateLogUseCase.test.js
  test/usecases/log/GetAllLogsUseCase.test.js
  test/usecases/run/UpdateRunUseCase.test.js
Labels: frontend, backend

#661 [O2B-659] Make active columns independent of the model + refactoring
  lib/public/Model.js
  lib/public/components/Filters/FlpsFilter/index.js
  lib/public/components/Filters/LogsFilter/index.js
  lib/public/components/Filters/RunsFilter/index.js
  lib/public/utilities/frontLink.js
  lib/public/views/Envs/ActiveColumns/envsActiveColumns.js
  lib/public/views/Envs/Overview/index.js
  lib/public/views/Flps/ActiveColumns/flpsActiveColumns.js
  lib/public/views/Flps/Overview/index.js
  lib/public/views/Home/Overview/index.js
  lib/public/views/LhcFills/ActiveColumns/lhcFillsActiveColumns.js
  lib/public/views/LhcFills/Overview/index.js
  lib/public/views/Logs/ActiveColumns/logsActiveColumns.js
  lib/public/views/Logs/ActiveColumns/reducedLogsActiveColumns.js
  lib/public/views/Logs/Logs.js
  lib/public/views/Logs/Overview/index.js
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
  lib/public/views/Runs/Details/index.js
  lib/public/views/Runs/Overview/exportRunsModal.js
  lib/public/views/Runs/Overview/index.js
  lib/public/views/Runs/Runs.js
  lib/public/views/Subsystems/Details/index.js
  lib/public/views/Tags/ActiveColumns/tagsActiveColumns.js
  lib/public/views/Tags/Details/index.js
  lib/public/views/Tags/Overview/index.js
  test/public/logs/overview.test.js
Labels: frontend

#664 Add release notes for 0.34.0
  CHANGELOG.md
  lib/public/views/About/Overview/index.js
  package-lock.json
  package.json
Labels: release

#668 [O2B-657] Store lhcPeriod value in runs
  database/CHANGELOG.md
  docs/data-model.md
  go-api-client/Example.go
  go-api-client/openapi-source.yaml
  go-api-client/src/BookkeepingApi.go
  go-api-client/src/go-client-generated/api/swagger.yaml
  go-api-client/src/go-client-generated/docs/Run.md
  go-api-client/src/go-client-generated/model_run.go
  lib/database/adapters/RunAdapter.js
  lib/database/migrations/20220726074211-runs-lhc-period.js
  lib/database/models/run.js
  lib/database/seeders/20200713103855-runs.js
  lib/domain/dtos/EndRunDto.js
  spec/openapi-source.yaml
  spec/openapi.yaml
  test/e2e/runs.test.js
  test/usecases/run/EndRunUseCase.test.js
Labels: backend, db

#669 [O2B-627] LHC period UI implementation
  CHANGELOG.md
  lib/database/seeders/20200713103855-runs.js
  lib/domain/dtos/GetAllRunsDto.js
  lib/public/components/Filters/RunsFilter/lhcPeriod.js
  lib/public/components/lhcFillsDetail/index.js
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
  lib/public/views/Runs/Runs.js
  lib/usecases/run/GetAllRunsUseCase.js
  test/e2e/runs.test.js
  test/public/runs/overview.test.js
  test/usecases/run/GetAllRunsUseCase.test.js
  test/usecases/run/GetRunUseCase.test.js
Labels: frontend, backend

#670 [O2B-654] Epns UI
  CHANGELOG.md
  lib/domain/dtos/GetAllRunsDto.js
  lib/public/components/Filters/RunsFilter/nEpns.js
  lib/public/components/RunDetail/index.js
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
  lib/public/views/Runs/Runs.js
  lib/usecases/run/GetAllRunsUseCase.js
  test/e2e/runs.test.js
  test/public/runs/overview.test.js
Labels: frontend, backend
