Repository AliceO2Group/Bookkeeping, pull requests merged in 2022-04, with the labels that each got.

#547 [O2B-504] Create tag and add email and mattermost
  lib/domain/dtos/CreateTagDto.js
  lib/public/Model.js
  lib/public/views/Tags/Create/index.js
  lib/public/views/Tags/Details/index.js
  lib/public/views/Tags/Tags.js
  lib/server/controllers/tags.controller.js
  lib/usecases/tag/CreateTagUseCase.js
  spec/openapi-source.yaml
  spec/openapi.yaml
  test/e2e/tags.test.js
  test/public/flps/overview.test.js
  test/public/runs/overview.test.js
  test/public/tags/create.test.js
Labels: frontend, backend

#551 [O2B-537] Return all information on user from session
  lib/usecases/user/CreateOrUpdateUser.js
Labels: backend

#550 [O2B-540] JOI validation caches dates
  lib/domain/dtos/GetAllLogsDto.js
  lib/domain/dtos/GetAllRunsDto.js
  lib/server/controllers/logs.controller.js
  lib/server/controllers/runs.controller.js
  lib/server/utilities/fromToValidator.js
  lib/server/utilities/index.js
  test/e2e/index.js
  test/e2e/runs.test.js
Labels: bug, backend

#552 [O2B-543] - Fix skipped tests for filter
  spec/openapi-source.yaml
  spec/openapi.yaml
  test/e2e/runs.test.js
Labels: backend

#562 [O2B-555] FLP/Detector number fields in Run Filters cannot be negative
  lib/public/components/Filters/RunsFilter/nDetectors.js
  lib/public/components/Filters/RunsFilter/nFlps.js
Labels: frontend
