Repository AliceO2Group/Bookkeeping, pull requests merged in 2022-08, with the labels that each got.

#672 [O2B-664] Include run numbers in log entry notification
  lib/server/controllers/logs.controller.js
  package-lock.json
  package.json
Labels: backend

#673 Release/0.35.0
  CHANGELOG.md
  database/CHANGELOG.md
  lib/public/views/About/Overview/index.js
  package-lock.json
  package.json
Labels: release

#676 [O2B-671] Update labels and placeholders as per conventions
  database/CHANGELOG.md
  docs/data-model.md
  go-api-client/Example.go
  lib/database/seeders/20200713103855-runs.js
  lib/public/components/Filters/RunsFilter/lhcPeriod.js
  lib/public/components/RunDetail/index.js
  test/e2e/runs.test.js
  test/public/runs/overview.test.js
  test/usecases/run/EndRunUseCase.test.js
  test/usecases/run/GetAllRunsUseCase.test.js
  test/usecases/run/GetRunUseCase.test.js
Labels: frontend

#663 [O2B-651] Add LHC fills statistics
  CHANGELOG.md
  lib/database/seeders/20200511151010-tags.js
  lib/database/seeders/20200713103855-runs.js
  lib/database/seeders/20220603150752-run-tag.js
  lib/public/app.css
  lib/public/services/run/extractRunStatistics.js
  lib/public/views/LhcFills/Detail/lhcFillDetailsComponent.js
  lib/server/controllers/lhcFill.controller.js
  lib/usecases/lhcFill/GetLhcFillUseCase.js
  test/e2e/runs.test.js
  test/e2e/tags.test.js
  test/public/lhcFills/detail.test.js
  test/public/tags/overview.test.js
  test/usecases/run/GetAllRunsUseCase.test.js
  test/usecases/tag/GetAllTagsUseCase.test.js
Labels: frontend, backend

#674 [O2B-633] odc topology fullname field
  CHANGELOG.md
  database/CHANGELOG.md
  docs/data-model.md
  go-api-client/Example.go
  go-api-client/openapi-source.yaml
  go-api-client/src/BookkeepingApi.go
  go-api-client/src/go-client-generated/api/swagger.yaml
  go-api-client/src/go-client-generated/docs/Run.md
  go-api-client/src/go-client-generated/model_run.go
  lib/database/adapters/RunAdapter.js
  lib/database/migrations/20220801093722-run-odc-topology-fullname.js
  lib/database/models/run.js
  lib/database/seeders/20200713103855-runs.js
  lib/domain/dtos/EndRunDto.js
  lib/domain/dtos/GetAllRunsDto.js
  lib/domain/dtos/StartRunDto.js
  lib/public/components/Filters/RunsFilter/odcTopologyFullName.js
  lib/public/components/RunDetail/index.js
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
  lib/public/views/Runs/Runs.js
  lib/usecases/run/GetAllRunsUseCase.js
  spec/openapi-source.yaml
  spec/openapi.yaml
  test/e2e/runs.test.js
  test/usecases/run/EndRunUseCase.test.js
  test/usecases/run/GetRunUseCase.test.js
Labels: frontend, backend, db

#680 [O2B-674] Add LHC fills statistics on overview and details
  CHANGELOG.md
  lib/database/seeders/20200713103855-runs.js
  lib/database/seeders/20220503120937-lhc-fills.js
  lib/public/app.css
  lib/public/components/Detail/detailsGrid.js
  lib/public/services/lhcFill/addStatisticsToLhcFill.js
  lib/public/services/lhcFill/computeLhcFillStatistics.js
  lib/public/services/run/isPotentiallyPhysicsRun.js
  lib/public/utilities/formatting/formatPercentage.js
  lib/public/views/LhcFills/ActiveColumns/lhcFillsActiveColumns.js
  lib/public/views/LhcFills/Detail/LhcFillDetailsModel.js
  lib/public/views/LhcFills/Detail/lhcFillDetailsComponent.js
  lib/public/views/LhcFills/Detail/lhcFillDisplayConfiguration.js
  lib/public/views/LhcFills/LhcFills.js
  test/e2e/runs.test.js
  test/public/lhcFills/detail.test.js
  test/public/lhcFills/overview.test.js
  test/usecases/run/GetAllRunsUseCase.test.js
  test/usecases/run/UpdateRunUseCase.test.js
Labels: frontend

#681 Release 0.36.0
  lib/public/views/About/Overview/index.js
  package-lock.json
  package.json
Labels: release

#684 [O2B-678] Debounce render after window resize
  lib/public/Model.js
Labels: bug, frontend

#682 [O2B-680] Update docker image and dependencies
  Dockerfile
  package-lock.json
  package.json
Labels: dependencies, docker

#685 [O2B-646] Allow tags of 2 characters
  CHANGELOG.md
  lib/domain/dtos/CreateTagDto.js
  lib/public/views/Tags/Create/index.js
  test/e2e/tags.test.js
Labels: frontend, backend

#689 [O2B-683] Fix run details page when there is no LHC fill
  lib/public/components/Detail/detailsList.js
  lib/public/views/Runs/Details/lhcFillPanel.js
  lib/public/views/Runs/Runs.js
Labels: bug, frontend

#687 [O2B-665] Main tabs are links and no buttons
  CHANGELOG.md
  lib/public/app.css
  lib/public/components/NavBar/index.js
  lib/public/utilities/frontLink.js
Labels: frontend

#690 [O2B-642] Run quality change should create a log
  CHANGELOG.md
  docker-compose.dev.yml
  lib/database/index.js
  lib/database/repositories/Repository.js
  lib/database/seeders/20200511151010-tags.js
  lib/database/utilities/TransactionHelper.js
  lib/public/components/Detail/detailsList.js
  lib/usecases/lhcFill/checkLhcFill.js
  lib/usecases/log/CreateLogUseCase.js
  lib/usecases/log/GetAllLogsUseCase.js
  lib/usecases/run/GetAllRunsUseCase.js
  lib/usecases/run/UpdateRunUseCase.js
  lib/usecases/run/getRunOrFail.js
  lib/usecases/tag/getAllTagsByTextOrFail.js
  lib/usecases/tag/getTagsByTextUseCase.js
  lib/usecases/tag/index.js
  test/public/home/overview.test.js
  test/public/logs/create.test.js
  test/public/logs/overview.test.js
  test/usecases/run/UpdateRunUseCase.test.js
  test/usecases/tag/GetAllTagsUseCase.test.js
Labels: backend

#693 Release 0.37.0
  lib/public/views/About/Overview/index.js
  package-lock.json
  package.json
Labels: release

#699 [O2B-687] Fix negative LHC before first run duration
  lib/public/services/lhcFill/computeLhcFillStatistics.js
Labels: bug, frontend

#698 [O2B-686] Fix log notification for auto-generated logs
  lib/usecases/log/CreateLogUseCase.js
Labels: bug, backend

#691 [O2B-679] AliECS pdp/readout fields
  CHANGELOG.md
  database/CHANGELOG.md
  docs/data-model.md
  go-api-client/Example.go
  go-api-client/openapi-source.yaml
  go-api-client/src/BookkeepingApi.go
  go-api-client/src/go-client-generated/.swagger-codegen/VERSION
  go-api-client/src/go-client-generated/api/swagger.yaml
  go-api-client/src/go-client-generated/docs/Run.md
  go-api-client/src/go-client-generated/model_run.go
  lib/database/adapters/RunAdapter.js
  lib/database/migrations/20220819093639-aliecs-pdp-readout-run-values.js
  lib/database/models/run.js
  lib/database/seeders/20200713103855-runs.js
  lib/domain/dtos/EndRunDto.js
  lib/public/components/RunDetail/index.js
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
  spec/openapi-source.yaml
  spec/openapi.yaml
  test/e2e/runs.test.js
  test/usecases/run/EndRunUseCase.test.js
Labels: frontend, backend, db

#701 [O2B-689] Add time loss at end of beam
  CHANGELOG.md
  lib/public/services/lhcFill/computeLhcFillStatistics.js
  lib/public/views/LhcFills/ActiveColumns/lhcFillsActiveColumns.js
  lib/public/views/LhcFills/Detail/lhcFillDisplayConfiguration.js
  test/public/lhcFills/detail.test.js
  test/public/lhcFills/overview.test.js
Labels: frontend

#703 [O2B-694] Remove the page reset on log column hover
  lib/public/components/Table/SortModel.js
  lib/public/views/Logs/Logs.js
Labels: bug, frontend

#711 Release 0.38.0
  CHANGELOG.md
  lib/public/views/About/Overview/index.js
  package-lock.json
  package.json
Labels: release
