Repository AliceO2Group/Bookkeeping, pull requests merged in 2022-06, with the labels that each got.

#594 [O2B-539] Handle empty tags list on front end
  lib/public/views/Tags/Tags.js
Labels: bug, frontend

#585 [O2B-573] Multiple run overview page improvements
  lib/presentation/log/toTreeView.js
  lib/public/app.css
  lib/public/components/Table/rows.js
  lib/public/utilities/clipToViewport.js
  lib/public/utilities/wrapWithBalloon.js
  lib/public/views/Envs/Overview/index.js
  lib/public/views/Runs/ActiveColumns/index.js
  lib/public/views/Runs/Export/index.js
  test/public/defaults.js
  test/public/runs/overview.test.js
Labels: frontend

#606 [O2B-583] Lhc overview descending sort on fill number
  lib/usecases/lhcFill/GetAllLhcFillsUseCase.js
Labels: backend

#605 [O2B-580] Fixed the lhc fills infinite mode
  lib/public/views/LhcFills/LhcFills.js
  test/public/lhcFills/overview.test.js
Labels: frontend

#609 [O2B-588] Acronysms fixes and eor visuals improvements
  lib/public/components/NavBar/index.js
  lib/public/components/RunDetail/index.js
  lib/public/components/lhcFillsDetail/index.js
  lib/public/views/LhcFills/ActiveColumns/index.js
  test/public/runs/detail.test.js
Labels: frontend

#582 [O2B-552] More button should allow for opening in new-tab
  lib/public/views/Logs/ActiveColumns/index.js
  lib/public/views/Runs/ActiveColumns/index.js
  test/public/home/overview.test.js
  test/public/logs/create.test.js
  test/public/logs/overview.test.js
Labels: frontend

#614 [02B-546] Edit Run button admin validation frontend
  lib/public/views/Runs/Details/index.js
  test/public/runs/detail.test.js
Labels: frontend

#597 [O2B-577] Block run creation on duplicate run number
  lib/database/migrations/20220519134614-add-unique-run-number-constraint.js
  lib/server/controllers/runs.controller.js
  lib/usecases/run/StartRunUseCase.js
  test/e2e/runs.test.js
  test/usecases/run/StartRunUseCase.test.js
Labels: backend

#607 [O2B-512] Filter run qualities using checkboxes
  lib/domain/dtos/GetAllRunsDto.js
  lib/public/components/Filters/RunsFilter/runQuality.js
  lib/public/components/Filters/RunsFilter/tags.js
  lib/public/views/Runs/Runs.js
  lib/usecases/run/GetAllRunsUseCase.js
  test/e2e/runs.test.js
  test/public/defaults.js
  test/public/runs/overview.test.js
  test/usecases/run/GetAllRunsUseCase.test.js
Labels: frontend, backend

#603 [O2B-581] Add searchbox on tag name in tag overview
  lib/domain/dtos/GetAllTagsDto.js
  lib/public/app.css
  lib/public/components/Table/headers.js
  lib/public/views/Tags/ActiveColumns/index.js
  lib/public/views/Tags/Tags.js
  lib/usecases/tag/GetAllTagsUseCase.js
  test/e2e/tags.test.js
  test/public/tags/overview.test.js
  test/usecases/tag/GetAllTagsUseCase.test.js
Labels: frontend, backend

#619 [O2B-582] Add balloon on some overview pages
  lib/database/seeders/20200508094502-logs.js
  lib/database/seeders/20200511151016-log-tags.js
  lib/database/seeders/20220412122043-environments.js
  lib/public/views/Envs/ActiveColumns/index.js
  lib/public/views/LhcFills/ActiveColumns/index.js
  lib/public/views/Logs/ActiveColumns/index.js
  test/public/envs/overview.test.js
  test/public/lhcFills/overview.test.js
  test/public/logs/create.test.js
  test/public/logs/overview.test.js
Labels: frontend

#615 [O2B-511] Run filters should accept operators
  lib/database/utilities/QueryBuilder.js
  lib/domain/dtos/GetAllRunsDto.js
  lib/public/components/Filters/RunsFilter/nDetectors.js
  lib/public/components/Filters/RunsFilter/nFlps.js
  lib/public/components/Filters/components/amountFilter.js
  lib/public/components/Filters/components/comparisonOperatorFilter.js
  lib/public/components/Table/rows.js
  lib/public/views/Runs/ActiveColumns/index.js
  lib/public/views/Runs/Runs.js
  lib/server/controllers/runs.controller.js
  lib/usecases/run/GetAllRunsUseCase.js
  test/e2e/runs.test.js
  test/public/runs/overview.test.js
  test/testUtilities/catchAsyncError.js
  test/usecases/run/GetAllRunsUseCase.test.js
Labels: frontend, backend

#617 [O2B-545] Factorize tags selections
  .eslintrc
  lib/public/Model.js
  lib/public/components/Filters/LogsFilter/tags.js
  lib/public/components/Filters/RunsFilter/tags.js
  lib/public/components/Filters/common/TagFilterModel.js
  lib/public/components/Filters/common/remoteDataTagFilter.js
  lib/public/components/Filters/common/tagFilter.js
  lib/public/components/common/spinner.js
  lib/public/components/pickers/tag/TagPickerModel.js
  lib/public/components/pickers/tag/remoteDataTagPicker.js
  lib/public/components/pickers/tag/tagPicker.js
  lib/public/views/Logs/ActiveColumns/index.js
  lib/public/views/Logs/Create/index.js
  lib/public/views/Logs/Logs.js
  lib/public/views/Logs/Overview/index.js
  lib/public/views/Runs/ActiveColumns/index.js
  lib/public/views/Runs/ActiveColumnsLogs/index.js
  lib/public/views/Runs/Details/editTagsPanel.js
  lib/public/views/Runs/Runs.js
  lib/public/views/Tags/Tags.js
  test/public/logs/create.test.js
  test/public/runs/detail.test.js
Labels: frontend

#604 [O2B-510] Allow multiple values for some run filters
  lib/database/seeders/20200713103855-runs.js
  lib/domain/dtos/GetAllRunsDto.js
  lib/public/components/Filters/RunsFilter/environmentId.js
  lib/public/components/Filters/RunsFilter/runNumber.js
  lib/public/views/Runs/Runs.js
  lib/server/controllers/runs.controller.js
  lib/usecases/run/GetAllRunsUseCase.js
  test/public/runs/overview.test.js
  test/usecases/run/GetAllRunsUseCase.test.js
Labels: frontend, backend

#620 Adding release notes 0.30.0
  .github/pull_request_template.md
  CHANGELOG.md
  lib/public/views/About/Overview/index.js
  package-lock.json
  package.json
Labels: release

#622 [O2B-599] API retrieving run(s) should include run duration
  lib/database/adapters/RunAdapter.js
  lib/database/models/run.js
  lib/database/seeders/20200713103855-runs.js
  lib/public/utilities/formatTimestamp.js
  lib/public/views/Runs/ActiveColumns/index.js
  spec/openapi-source.yaml
  spec/openapi.yaml
  test/e2e/runs.test.js
  test/usecases/run/GetRunUseCase.test.js
Labels: backend

#623 [O2B-600] Api run should accept duration filter
  lib/database/utilities/QueryBuilder.js
  lib/domain/dtos/GetAllRunsDto.js
  lib/usecases/run/GetAllRunsUseCase.js
  test/e2e/runs.test.js
  test/usecases/run/GetAllRunsUseCase.test.js
Labels: backend

#626 [O2B-609] Factorize dates and timestamp displays
  lib/public/components/Post/index.js
  lib/public/components/RunDetail/index.js
  lib/public/components/TagDetail/index.js
  lib/public/components/lhcFillsDetail/index.js
  lib/public/utilities/formatTimestamp.js
  lib/public/utilities/pick.js
  lib/public/views/Envs/ActiveColumns/index.js
  lib/public/views/LhcFills/ActiveColumns/index.js
  lib/public/views/Logs/ActiveColumns/index.js
  lib/public/views/Logs/Overview/index.js
  lib/public/views/Runs/ActiveColumns/index.js
  lib/public/views/Runs/ActiveColumnsLogs/index.js
  lib/public/views/Runs/Overview/index.js
  lib/public/views/Tags/ActiveColumns/index.js
Labels: frontend

#627 [O2B-601] Add run duration column and filter
  lib/public/components/Filters/RunsFilter/durationFilter.js
  lib/public/components/Filters/components/amountFilter.js
  lib/public/views/Runs/ActiveColumns/index.js
  lib/public/views/Runs/Runs.js
  test/public/runs/overview.test.js
Labels: frontend

#628 [O2B-615] Fix persistent tags filtering
  lib/public/components/Table/headers.js
  lib/public/utilities/remoteDataFromResponse.js
  lib/public/views/Tags/ActiveColumns/index.js
  lib/public/views/Tags/Overview/TagsOverviewModel.js
  lib/public/views/Tags/Overview/index.js
  lib/public/views/Tags/Tags.js
Labels: bug, frontend

#632 Release 0.31.0
  CHANGELOG.md
  database/CHANGELOG.md
  lib/public/views/About/Overview/index.js
  lib/public/views/Runs/Details/index.js
  package-lock.json
  package.json
Labels: release

#629 [O2B-579] Add polarity fields to support
  docs/data-model.md
  lib/database/adapters/RunAdapter.js
  lib/database/migrations/20220623125959-lhc-polarity.js
  lib/database/models/run.js
  lib/database/seeders/20200713103855-runs.js
  lib/domain/dtos/UpdateRunByRunNumberDto.js
  lib/public/components/lhcFillsDetail/index.js
  lib/usecases/run/UpdateRunUseCase.js
  spec/openapi-source.yaml
  spec/openapi.yaml
  test/e2e/runs.test.js
  test/usecases/run/UpdateRunUseCase.test.js
Labels: frontend, backend, db
