Repository AliceO2Group/Bookkeeping, pull requests merged in 2022-10, with the labels that each got.

#757 [O2B-730] Runs home to start stop
  CHANGELOG.md
  lib/public/components/RunDetail/index.js
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
Labels: frontend

#753 [O2B-733] Fix run overview active filters
  CHANGELOG.md
  lib/public/views/Runs/Runs.js
Labels: bug, frontend

#742 [O2B-724] Add CALIBRATION to run definition
  CHANGELOG.md
  lib/database/seeders/20200713103855-runs.js
  lib/domain/dtos/GetAllRunsDto.js
  lib/public/components/Filters/RunsFilter/definitionFilter.js
  lib/public/views/Runs/Runs.js
  lib/services/getRunDefinition.js
  lib/usecases/run/GetAllRunsUseCase.js
  test/e2e/runs.test.js
  test/public/runs/overview.test.js
  test/usecases/lhcFill/GetLhcFillUseCase.test.js
  test/usecases/run/GetAllRunsUseCase.test.js
Labels: frontend, backend

#749 [O2B-706] Add fields ccdb by run number
  CHANGELOG.md
  database/CHANGELOG.md
  docs/data-model.md
  lib/database/adapters/RunAdapter.js
  lib/database/migrations/20220926072445-runs-ccdb-fields-added.js
  lib/database/models/run.js
  lib/database/models/typedefs/SequelizeRun.js
  lib/database/seeders/20200713103855-runs.js
  lib/domain/dtos/UpdateRunByRunNumberDto.js
  lib/domain/entities/Run.js
  lib/public/components/RunDetail/index.js
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
  spec/openapi-source.yaml
  spec/openapi.yaml
  test/e2e/runs.test.js
  test/usecases/run/UpdateRunUseCase.test.js
Labels: frontend, backend, db

#761 Release 0.42.0
  lib/public/views/About/Overview/index.js
  package-lock.json
  package.json
Labels: release

#765 [O2B-744] Fix environment's run link when creating run
  lib/database/adapters/RunAdapter.js
  test/e2e/runs.test.js
  test/usecases/run/StartRunUseCase.test.js
Labels: bug, backend

#756 [O2B-735] Improve pagination
  lib/public/Model.js
  lib/public/components/Pagination/PaginationModel.js
  lib/public/components/Pagination/amountSelector.js
  lib/public/components/Pagination/pageSelector.js
  lib/public/components/Pagination/paginationComponent.js
  lib/public/components/common/table/rows.js
  lib/public/utilities/parseFetchResponse.js
  lib/public/views/Envs/Envs.js
  lib/public/views/Envs/Overview/index.js
  lib/public/views/Flps/Flps.js
  lib/public/views/Flps/Overview/index.js
  lib/public/views/Home/Overview/index.js
  lib/public/views/LhcFills/Overview/LhcFillsOverviewModel.js
  lib/public/views/LhcFills/Overview/index.js
  lib/public/views/Logs/Logs.js
  lib/public/views/Logs/Overview/index.js
  lib/public/views/OverviewModel.js
  lib/public/views/Runs/Overview/index.js
  lib/public/views/Runs/Runs.js
  test/public/envs/overview.test.js
  test/public/flps/overview.test.js
  test/public/logs/overview.test.js
  test/public/runs/overview.test.js
  test/public/tags/overview.test.js
Labels: frontend

#743 [O2B-723] Restrict cosmic definition to cosmic run types
  lib/database/seeders/20200713103855-runs.js
  lib/services/getRunDefinition.js
  lib/usecases/run/GetAllRunsUseCase.js
  test/public/runs/overview.test.js
  test/usecases/run/GetAllRunsUseCase.test.js
Labels: backend

#773 Add documentation on run definitions
  docs/RUN_DEFINITIONS.md
Labels: documentation

#772 [O2B-751] Start stop runs now inline
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
Labels: frontend

#770 [O2B-750] File size is shown as '0' instead of null
  lib/database/adapters/RunAdapter.js
  lib/database/seeders/20200713103855-runs.js
  lib/public/components/RunDetail/index.js
  test/e2e/runs.test.js
Labels: frontend, backend

#767 [O2B-743] Always start infinite scroll from the first item
  lib/public/components/Pagination/PaginationModel.js
  lib/public/components/Pagination/amountSelector.js
  lib/public/views/Envs/Envs.js
  lib/public/views/Flps/Flps.js
  lib/public/views/LhcFills/Overview/LhcFillsOverviewModel.js
  lib/public/views/Logs/Logs.js
  lib/public/views/Runs/Runs.js
Labels: bug, frontend

#771 [O2B-749] Improve run quality update logging
  lib/server/services/run/RunService.js
  lib/server/services/run/updateRun.js
  lib/server/services/user/UserService.js
  lib/server/services/user/getUser.js
  lib/server/services/user/getUserOrFail.js
  lib/usecases/run/UpdateRunUseCase.js
  test/usecases/run/UpdateRunUseCase.test.js
Labels: backend

#769 [O2B-741] Runs must overlap with stable beam to be considered as physics
  lib/database/adapters/RunAdapter.js
  lib/database/models/run.js
  lib/database/models/typedefs/SequelizeRun.js
  lib/database/utilities/QueryBuilder.js
  lib/domain/entities/Run.js
  lib/public/services/lhcFill/LhcFillStatisticsExtractor.js
  lib/public/services/run/TimeBetweenRunsTracker.js
  lib/public/services/run/constants.js
  lib/public/services/run/getRunStartAndEnd.js
  lib/public/views/Runs/formatRunDuration.js
  lib/services/getRunDefinition.js
  lib/usecases/lhcFill/GetLhcFillUseCase.js
  lib/usecases/run/GetAllRunsUseCase.js
  spec/openapi-source.yaml
  spec/openapi.yaml
Labels: backend

#768 [O2B-742] Validate custom items per page when pressing enter
  lib/public/app.css
  lib/public/components/Pagination/PaginationModel.js
  lib/public/components/Pagination/amountSelector.js
  test/public/envs/overview.test.js
  test/public/lhcFills/overview.test.js
  test/public/runs/overview.test.js
Labels: frontend

#776 [O2B-740] Add total items counter at the bottom of the page
  lib/public/components/Pagination/PaginationModel.js
  lib/public/components/Pagination/amountSelector.js
  lib/public/components/Pagination/paginationComponent.js
  lib/public/views/Envs/Envs.js
  lib/public/views/Flps/Flps.js
  lib/public/views/LhcFills/Overview/LhcFillsOverviewModel.js
  lib/public/views/Logs/Logs.js
  lib/public/views/Runs/Runs.js
  test/public/envs/overview.test.js
  test/public/flps/overview.test.js
  test/public/lhcFills/overview.test.js
  test/public/logs/overview.test.js
  test/public/runs/overview.test.js
Labels: frontend

#764 [release] 0.43.0
  CHANGELOG.md
  lib/public/views/About/Overview/index.js
  package-lock.json
  package.json
Labels: release

#785 [O2B-761] Remove unicode characters from test file name
  test/assets/hadron_collider_(é_è).jpg
  test/e2e/logs.test.js
  test/public/logs/create.test.js
Labels: bug

#775 [O2B-720] Add detector table to data model
  Dockerfile
  lib/database/adapters/DetectorAdapter.js
  lib/database/adapters/RunAdapter.js
  lib/database/adapters/RunDetectorsAdapter.js
  lib/database/adapters/index.js
  lib/database/migrations/20220926072445-runs-ccdb-fields-added.js
  lib/database/migrations/20220930085415-create-detectors-table.js
  lib/database/migrations/20220930092539-run-detector-table-creation.js
  lib/database/migrations/20221010120629-convert-run-detectors-to-separate-table.js
  lib/database/migrations/20221013114826-run-table-detectors-rename.js
  lib/database/models/detector.js
  lib/database/models/index.js
  lib/database/models/run.js
  lib/database/models/typedefs/SequelizeDetector.js
  lib/database/models/typedefs/SequelizeRun.js
  lib/database/repositories/DetectorRepository.js
  lib/database/repositories/RunDetectorsRepository.js
  lib/database/repositories/index.js
  lib/database/repositories/qbHelpers/lhcFill/physicsRunsIncludeExpression.js
  lib/database/seeders/20200713103855-runs.js
  lib/database/seeders/20220603150752-run-tag.js
  lib/database/seeders/20221005120315-detector.js
  lib/database/seeders/20221006084006-run-detectors.js
  lib/database/tables/index.js
  lib/database/tables/rundetectors.js
  lib/domain/entities/Detector.js
  lib/server/services/detector/getAllDetectorsByNameOrFail.js
  lib/server/services/detector/getDetectorsByNames.js
  lib/server/services/run/RunService.js
  lib/server/services/run/createRun.js
  lib/server/services/run/getRun.js
  lib/services/getRunDefinition.js
  lib/usecases/lhcFill/GetLhcFillUseCase.js
  lib/usecases/run/GetAllRunsUseCase.js
  lib/usecases/run/GetRunUseCase.js
  lib/usecases/run/StartRunUseCase.js
  spec/openapi-source.yaml
  spec/openapi.yaml
  test/usecases/run/GetRunUseCase.test.js
Labels: backend, db
