Repository AliceO2Group/Bookkeeping, pull requests merged in 2022-11, with the labels that each got.

#713 [O2B-698] Prepare function to query data easily
  lib/public/utilities/fetch/getRemoteData.js
  lib/public/utilities/fetch/getRemoteDataSlice.js
  lib/public/utilities/fetch/jsonFetch.js
  lib/public/utilities/parseFetchResponse.js
  lib/public/views/LhcFills/Overview/LhcFillsOverviewModel.js
  lib/public/views/Logs/Create/LogCreationModel.js
  lib/public/views/Logs/Logs.js
  lib/public/views/Runs/Runs.js
  lib/public/views/Tags/Overview/TagsOverviewModel.js
  lib/public/views/Tags/Tags.js
Labels: frontend

#751 [O2B-731] Handle all links through frontend router
  lib/public/Model.js
  lib/public/app.css
  lib/public/components/FlpRun/index.js
  lib/public/components/NavBar/index.js
  lib/public/components/Post/index.js
  lib/public/components/PostCollapsed/index.js
  lib/public/components/common/navigation/absoluteFrontLink.js
  lib/public/components/common/navigation/frontLink.js
  lib/public/components/common/navigation/frontLinkListener.js
  lib/public/components/common/navigation/frontLinks.js
  lib/public/components/common/navigation/tabLink.js
  lib/public/components/tag/remoteDataTagPicker.js
  lib/public/utilities/currentPageAndParameters.js
  lib/public/utilities/frontLink.js
  lib/public/views/Flps/Details/index.js
  lib/public/views/LhcFills/ActiveColumns/lhcFillsActiveColumns.js
  lib/public/views/LhcFills/Detail/lhcFillDisplayConfiguration.js
  lib/public/views/Logs/ActiveColumns/logsActiveColumns.js
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
  lib/public/views/Runs/Details/index.js
  lib/public/views/Runs/Runs.js
  lib/public/views/Subsystems/Details/index.js
  lib/public/views/Tags/Details/index.js
  test/public/logs/create.test.js
Labels: frontend

#778 Release 0.44.0
  CHANGELOG.md
  lib/public/views/About/Overview/index.js
  package-lock.json
  package.json
Labels: release

#796 [O2B-772] Add proto to npm package
  package.json
Labels: bug

#797 [O2B-773] Fix detectors migration
  lib/database/migrations/20221010120629-convert-run-detectors-to-separate-table.js
Labels: bug, backend

#798 Release 0.44.1
  CHANGELOG.md
  lib/public/views/About/Overview/index.js
  package-lock.json
  package.json
Labels: release

#804 Release/0.45.0
  CHANGELOG.md
  lib/public/views/About/Overview/index.js
  package-lock.json
  package.json
Labels: release

#790 [O2B-746] Run quality must not be edited on runs that are not ended yet
  lib/domain/dtos/StartRunDto.js
  lib/public/components/RunDetail/index.js
  lib/server/services/run/updateRun.js
  test/e2e/runs.test.js
  test/public/runs/detail.test.js
  test/usecases/run/StartRunUseCase.test.js
  test/usecases/run/UpdateRunUseCase.test.js
Labels: frontend, backend

#805 [O2B-782] Add detector quality modification to run edition
  lib/database/adapters/RunAdapter.js
  lib/database/adapters/index.js
  lib/database/models/detector.js
  lib/database/models/index.js
  lib/database/models/run.js
  lib/database/models/rundetectors.js
  lib/database/models/typedefs/SequelizeRun.js
  lib/database/repositories/RunDetectorsRepository.js
  lib/database/tables/index.js
  lib/domain/entities/Run.js
  lib/public/Model.js
  lib/public/app.css
  lib/public/components/Detail/detailsList.js
  lib/public/components/RunDetail/index.js
  lib/public/components/common/selection/dropdown/dropdown.js
  lib/public/components/common/toggle/toggleContainer.js
  lib/public/components/tag/tagDetail.js
  lib/public/views/Runs/Details/RunDetailsModel.js
  lib/public/views/Runs/Details/editTagsPanel.js
  lib/public/views/Runs/Details/index.js
  lib/public/views/Runs/Details/lhcFillPanel.js
  lib/public/views/Runs/Runs.js
  lib/server/services/run/RunService.js
  lib/usecases/run/EndRunUseCase.js
  lib/usecases/run/StartRunUseCase.js
  lib/usecases/run/UpdateRunUseCase.js
  test/e2e/runs.test.js
Labels: frontend

#806 release 0.46.0
  CHANGELOG.md
  lib/public/views/About/Overview/index.js
  package-lock.json
  package.json
Labels: release

#810 [O2B-782] Add test to run detector quality edition
  lib/database/models/typedefs/SequelizeRunDetector.js
  lib/public/components/RunDetail/index.js
  lib/server/services/runDetector/updateRunDetector.js
  lib/usecases/run/UpdateRunUseCase.js
  test/e2e/runs.test.js
  test/public/defaults.js
  test/public/runs/detail.test.js
  test/public/runs/overview.test.js
  test/usecases/run/GetRunUseCase.test.js
  test/usecases/run/UpdateRunUseCase.test.js
Labels: frontend, backend
