Repository AliceO2Group/Bookkeeping, pull requests merged in 2022-03, with the labels that each got.

#486 [O2B-281] Sequelize migration for tags table to add notification data
  lib/database/migrations/20220125151025-create-tag.js
  lib/database/models/tag.js
Labels: db

#527 Release 0.23.0
  CHANGELOG.md
  lib/public/views/About/Overview/index.js
Labels: release

#529 [O2B-421] Fix notification URL
  lib/server/controllers/logs.controller.js
Labels: bug

#528 [O2B-421] Fix notification configuration
  lib/config/notification.js
Labels: bug

#530 [O2B-508] When creating logs double run numbers are filtered in the backend
  lib/usecases/log/CreateLogUseCase.js
  test/e2e/logs.test.js
  test/public/home/overview.test.js
  test/usecases/log/CreateLogUseCase.test.js
Labels: backend

#531 [O2B-513] RUN filter improvements for DCS field
  lib/database/seeders/20200713103855-runs.js
  lib/database/utilities/QueryBuilder.js
  lib/domain/dtos/StartRunDto.js
  lib/public/components/Filters/RunsFilter/dcs.js
  lib/public/views/Runs/Runs.js
  lib/usecases/run/GetAllRunsUseCase.js
  test/database/utilities/QueryBuilder.test.js
  test/usecases/index.js
  test/usecases/run/GetAllRunsUseCase.test.js
Labels: frontend, backend

#532 [O2B-513] RUN Filter improvements for EPN field
  lib/database/seeders/20200713103855-runs.js
  lib/domain/dtos/StartRunDto.js
  lib/public/components/Filters/RunsFilter/epn.js
  lib/public/views/Runs/Runs.js
  lib/usecases/run/GetAllRunsUseCase.js
  test/usecases/run/GetAllRunsUseCase.test.js
Labels: frontend, backend

#533 [O2B-513] RUN filter improvements for field DD
  lib/database/seeders/20200713103855-runs.js
  lib/domain/dtos/StartRunDto.js
  lib/public/components/Filters/RunsFilter/ddflp.js
  lib/public/views/Runs/Runs.js
  lib/usecases/run/GetAllRunsUseCase.js
  test/usecases/run/GetAllRunsUseCase.test.js
Labels: frontend, backend

#535 [O2B-520] Runs API should accept multiple run numbers for listRuns
  lib/domain/dtos/GetAllRunsDto.js
  lib/public/views/Runs/Runs.js
  lib/usecases/run/GetAllRunsUseCase.js
  test/usecases/run/GetAllRunsUseCase.test.js
Labels: backend

#523 [O2B-500] Display of email groups and mattermost channels in tag overview
  lib/database/adapters/TagAdapter.js
  lib/public/views/Tags/ActiveColumns/index.js
  lib/public/views/Tags/Overview/index.js
  spec/openapi-source.yaml
  spec/openapi.yaml
  test/e2e/logs.test.js
Labels: frontend, backend

#537 [O2B-505] Improve listTags API to accept filters for tags retrieval
  lib/database/seeders/20200511151010-tags.js
  lib/domain/dtos/GetAllTagsDto.js
  lib/server/controllers/tags.controller.js
  lib/server/routers/tags.router.js
  lib/usecases/tag/GetAllTagsUseCase.js
  test/e2e/logs.test.js
  test/usecases/tag/GetAllTagsUseCase.test.js
Labels: backend

#538 Release 0.24.0
  CHANGELOG.md
  lib/public/views/About/Overview/index.js
  package-lock.json
  package.json
Labels: release

#542 [O2B-507] - Infinite mode in Run Statistics table displays duplicates
  lib/public/components/Pagination/pageSelector.js
  lib/public/views/Logs/Logs.js
  lib/public/views/Runs/Runs.js
Labels: frontend

#545 [O2B-479] Dispaly log details if it has no children
  lib/public/views/Logs/Details/index.js
  test/public/logs/detail.test.js
Labels: frontend

#544 [O2B-502] API Route to update a tag
  cpp-api-client/openapi-source.yaml
  docs/data-model.md
  go-api-client/openapi-source.yaml
  lib/database/adapters/TagAdapter.js
  lib/database/migrations/20220309132744-create-tag.js
  lib/database/models/tag.js
  lib/domain/dtos/UpdateTagDto.js
  lib/domain/dtos/index.js
  lib/public/components/Detail/index.js
  lib/public/components/NavBar/index.js
  lib/public/components/RunDetail/index.js
  lib/public/components/TagDetail/index.js
  lib/public/views/Tags/Details/index.js
  lib/public/views/Tags/Tags.js
  lib/server/controllers/tags.controller.js
  lib/server/index.js
  lib/server/routers/tags.router.js
  lib/usecases/tag/UpdateTagUseCase.js
  lib/usecases/tag/index.js
  spec/openapi-source.yaml
  spec/openapi.yaml
  test/e2e/logs.test.js
  test/e2e/tags.test.js
  test/usecases/tag/UpdateTagUseCase.test.js
  test/usecases/tag/index.js
Labels: frontend, backend, db

#536 [O2B-509] Improvement run start stop filters
  lib/database/seeders/20200713103855-runs.js
  lib/domain/dtos/GetAllRunsDto.js
  lib/public/components/Filters/RunsFilter/o2start.js
  lib/public/components/Filters/RunsFilter/o2stop.js
  lib/public/views/Runs/ActiveColumns/index.js
  lib/public/views/Runs/Runs.js
  test/public/runs/overview.test.js
  test/usecases/run/GetAllRunsUseCase.test.js
Labels: frontend, backend
