Repository AliceO2Group/Bookkeeping, pull requests merged in 2022-02, with the labels that each got.

#495 [OGUI-482] Display run quality column on run-overview and run-details
  lib/public/components/RunDetail/index.js
  lib/public/components/Table/rows.js
  lib/public/views/Runs/ActiveColumns/index.js
  test/public/runs/detail.test.js
Labels: frontend

#496 [O2B-484] Add Edit Mode and quality field to runs
  lib/public/components/RunDetail/index.js
  lib/public/views/Runs/Details/editTagsPanel.js
  lib/public/views/Runs/Details/index.js
  lib/public/views/Runs/Runs.js
  test/public/runs/detail.test.js
Labels: frontend

#497 [O2B-486] Add RunQuality as filter option to RunOverview
  lib/domain/dtos/GetAllRunsDto.js
  lib/public/components/Filters/RunsFilter/runQuality.js
  lib/public/views/Runs/ActiveColumns/index.js
  lib/public/views/Runs/Runs.js
  lib/usecases/run/GetAllRunsUseCase.js
Labels: frontend, backend

#505 [O2B-487] Add check for null values before attempt to display
  lib/public/components/Post/index.js
  lib/public/components/PostCollapsed/index.js
  lib/public/components/RunDetail/index.js
Labels: bug, frontend

#512 [O2B-488] Generate GO API updates
  go-api-client/openapi-source.yaml
  go-api-client/src/BookkeepingApi.go
  go-api-client/src/go-client-generated/.swagger-codegen/VERSION
  go-api-client/src/go-client-generated/api/swagger.yaml
  go-api-client/src/go-client-generated/model_run_quality.go
  spec/openapi-source.yaml
  spec/openapi.yaml
Labels: dependencies, backend

#514 [O2B-484] Fix C++ integration by bringing back runQuality to EndRun DTO
  CHANGELOG.md
  lib/domain/dtos/EndRunDto.js
  lib/public/views/About/Overview/index.js
  package-lock.json
  package.json
Labels: bug

#516 [O2B-491] Configurable attachment location
  CHANGELOG.md
  docs/DEVELOPMENT.md
  docs/data-model.md
  lib/public/views/About/Overview/index.js
  lib/server/middleware/multer.middleware.js
  package-lock.json
  package.json
Labels: backend
