Repository AliceO2Group/Bookkeeping, pull requests merged in 2022-09, with the labels that each got.

#678 [O2B-570] Preliminary code refactoring
  lib/public/Model.js
  lib/public/components/Filters/FlpsFilter/index.js
  lib/public/components/Filters/LogsFilter/author.js
  lib/public/components/Filters/LogsFilter/created.js
  lib/public/components/Filters/LogsFilter/index.js
  lib/public/components/Filters/LogsFilter/runs.js
  lib/public/components/Filters/RunsFilter/dcs.js
  lib/public/components/Filters/RunsFilter/ddflp.js
  lib/public/components/Filters/RunsFilter/detectors.js
  lib/public/components/Filters/RunsFilter/durationFilter.js
  lib/public/components/Filters/RunsFilter/environmentId.js
  lib/public/components/Filters/RunsFilter/epn.js
  lib/public/components/Filters/RunsFilter/fillNumbers.js
  lib/public/components/Filters/RunsFilter/index.js
  lib/public/components/Filters/RunsFilter/lhcPeriod.js
  lib/public/components/Filters/RunsFilter/nDetectors.js
  lib/public/components/Filters/RunsFilter/nEpns.js
  lib/public/components/Filters/RunsFilter/nFlps.js
  lib/public/components/Filters/RunsFilter/o2start.js
  lib/public/components/Filters/RunsFilter/o2stop.js
  lib/public/components/Filters/RunsFilter/odcTopologyFullName.js
  lib/public/components/Filters/RunsFilter/runNumber.js
  lib/public/components/Filters/RunsFilter/runQuality.js
  lib/public/components/Filters/RunsFilter/triggerValue.js
  lib/public/components/Filters/common/filters/amountFilter.js
  lib/public/components/Filters/common/filters/checkboxFilter.js
  lib/public/components/Filters/common/filters/comparisonOperatorFilter.js
  lib/public/components/Filters/common/filters/remoteDataTagFilter.js
  lib/public/components/Filters/common/filters/tagFilter.js
  lib/public/components/Filters/common/filtersPanel.js
  lib/public/components/Filters/common/filtersToggleButton.js
  lib/public/components/Filters/filtersConstants.js
  lib/public/components/Pagination/PaginationModel.js
  lib/public/components/modal/modalContainer.js
  lib/public/utilities/durationUtils.js
  lib/public/utilities/estimateDisplayableRowsCount.js
  lib/public/utilities/formatting/formatDuration.js
  lib/public/utilities/taggedEventRegistry.js
  lib/public/view.js
  lib/public/views/Envs/Envs.js
  lib/public/views/Flps/Overview/index.js
  lib/public/views/LhcFills/LhcFills.js
  lib/public/views/LhcFills/Overview/LhcFillsOverviewModel.js
  lib/public/views/LhcFills/Overview/index.js
  lib/public/views/Logs/ActiveColumns/logsActiveColumns.js
  lib/public/views/Logs/Logs.js
  lib/public/views/Logs/Overview/index.js
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
  lib/public/views/Runs/Overview/index.js
  lib/public/views/Runs/Runs.js
  test/e2e/logs.test.js
  test/public/lhcFills/overview.test.js
  test/public/logs/create.test.js
  test/public/logs/overview.test.js
  test/public/runs/overview.test.js
Labels: frontend

#708 [O2B-611] Environment loading times
  lib/database/adapters/EnvironmentAdapter.js
  lib/database/adapters/RunAdapter.js
  lib/database/seeders/20220412122043-environments.js
  spec/openapi-source.yaml
  spec/openapi.yaml
Labels: bug, backend

#704 [O2B-666]Only admins should be allowed to create tags
  CHANGELOG.md
  lib/public/views/Tags/Create/index.js
  lib/public/views/Tags/Overview/index.js
Labels: backend

#702 [O2B-693] Refactor tables and add profile system
  CHANGELOG.md
  lib/public/components/Table/index.js
  lib/public/components/Table/rows.js
  lib/public/components/common/table/SortModel.js
  lib/public/components/common/table/headers.js
  lib/public/components/common/table/profiles.js
  lib/public/components/common/table/rows.js
  lib/public/components/common/table/table.js
  lib/public/utilities/applyProfile.js
  lib/public/views/About/Overview/index.js
  lib/public/views/Envs/Overview/index.js
  lib/public/views/Flps/Overview/index.js
  lib/public/views/Home/Overview/index.js
  lib/public/views/LhcFills/Detail/lhcFillDetailsComponent.js
  lib/public/views/LhcFills/Overview/index.js
  lib/public/views/Logs/ActiveColumns/logsActiveColumns.js
  lib/public/views/Logs/Logs.js
  lib/public/views/Logs/Overview/index.js
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
  lib/public/views/Runs/Details/index.js
  lib/public/views/Runs/Overview/index.js
  lib/public/views/Subsystems/Details/index.js
  lib/public/views/Subsystems/Overview/index.js
  lib/public/views/Tags/Details/index.js
  lib/public/views/Tags/Overview/index.js
  test/public/about/overview.test.js
Labels: frontend

#700 [O2B-692] Add run definition column and filtering in runs overview
  CHANGELOG.md
  lib/database/adapters/RunAdapter.js
  lib/database/models/run.js
  lib/database/models/tag.js
  lib/database/seeders/20200713103855-runs.js
  lib/database/utilities/QueryBuilder.js
  lib/domain/dtos/GetAllRunsDto.js
  lib/public/app.css
  lib/public/components/Filters/RunsFilter/definitionFilter.js
  lib/public/components/Filters/common/filters/checkboxFilter.js
  lib/public/services/lhcFill/computeLhcFillStatistics.js
  lib/public/services/run/isPotentiallyPhysicsRun.js
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
  lib/public/views/Runs/Runs.js
  lib/services/getRunDefinition.js
  lib/usecases/lhcFill/GetLhcFillUseCase.js
  lib/usecases/run/GetAllRunsUseCase.js
  spec/convert.js
  spec/openapi-source.yaml
  spec/openapi.yaml
  test/e2e/runs.test.js
  test/openapi.test.js
  test/public/runs/overview.test.js
  test/usecases/run/GetAllRunsUseCase.test.js
Labels: backend

#715 [O2B-700] Fix several table display when row ids match
  CHANGELOG.md
  lib/public/view.js
Labels: bug, frontend

#716 [O2B-695] Restrict LHC fills' runs to physics only
  CHANGELOG.md
  lib/database/repositories/qbHelpers/lhcFill/physicsRunsIncludeExpression.js
  lib/usecases/lhcFill/GetAllLhcFillsUseCase.js
  lib/usecases/lhcFill/GetLhcFillUseCase.js
  test/usecases/lhcFill/GetLhcFillUseCase.test.js
Labels: backend

#720 [O2B-702] Fix log display cleanup
  CHANGELOG.md
  lib/public/views/Logs/Details/index.js
  lib/public/views/Logs/Logs.js
Labels: bug, frontend

#719 [O2B-702] Fix environment pagination
  CHANGELOG.md
  lib/public/views/Envs/Envs.js
  test/public/envs/overview.test.js
Labels: bug, frontend

#721 Release 0.39.0
  lib/public/views/About/Overview/index.js
  package-lock.json
  package.json
Labels: release

#724 [O2B-692] Fix fill overview and synthetic computing
  CHANGELOG.md
  lib/database/repositories/qbHelpers/lhcFill/physicsRunsIncludeExpression.js
  lib/database/seeders/20200713103855-runs.js
  lib/services/getRunDefinition.js
  lib/usecases/run/GetAllRunsUseCase.js
Labels: bug, backend

#694 [O2B-549] Visual improvement of log creation page
  CHANGELOG.md
  lib/public/app.css
  lib/public/views/Logs/Create/index.js
  lib/public/views/Logs/Logs.js
  test/public/logs/create.test.js
Labels: frontend

#730 [O2B-673] Fix run detectors filter
  CHANGELOG.md
  lib/database/utilities/QueryBuilder.js
  lib/usecases/run/GetAllRunsUseCase.js
  test/usecases/run/GetAllRunsUseCase.test.js
Labels: bug, frontend

#734 Fix for empty run type
  lib/public/utilities/formatting/formatRunType.js
Labels: frontend

#733 [O2B-672] Add run definition on run details
  CHANGELOG.md
  lib/public/components/RunDetail/index.js
Labels: frontend

#735 Release 0.40.0
  CHANGELOG.md
  database/CHANGELOG.md
  lib/public/views/About/Overview/index.js
  package-lock.json
  package.json
Labels: release

#732 [O2B-716] Fix log filtering whitespaces removal
  CHANGELOG.md
  lib/public/components/Filters/LogsFilter/author.js
  lib/public/components/Filters/LogsFilter/title.js
  lib/public/components/Filters/common/filters/FilterInputModel.js
  lib/public/views/Logs/Logs.js
Labels: bug, frontend

#679 [O2B-657] Start stop values
  CHANGELOG.md
  database/CHANGELOG.md
  lib/database/models/run.js
  lib/database/seeders/20200713103855-runs.js
  lib/public/components/RunDetail/index.js
  lib/public/components/common/popover/popover.js
  lib/public/components/common/table/headers.js
  lib/public/components/common/table/table.js
  lib/public/utilities/formatting/formatTimestamp.js
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
  lib/public/views/Runs/formatRunDuration.js
  lib/usecases/run/GetAllRunsUseCase.js
  test/e2e/runs.test.js
  test/public/runs/overview.test.js
  test/usecases/run/GetAllRunsUseCase.test.js
  test/usecases/run/GetRunUseCase.test.js
Labels: frontend, backend, db

#738 [O2B-638] Fix utf-8 characters file name in uploads
  CHANGELOG.md
  lib/server/middleware/multer.middleware.js
  test/assets/hadron_collider_(é_è)_🚀.jpg
  test/e2e/logs.test.js
  test/public/logs/create.test.js
Labels: bug, backend

#739 [O2B-688] Add efficiency per detectors
  CHANGELOG.md
  lib/public/services/lhcFill/LhcFillStatisticsExtractor.js
  lib/public/utilities/statistics/NonOverlappingSegmentsMerger.js
  lib/public/views/LhcFills/Detail/lhcFillDetailsComponent.js
  test/public/lhcFills/detail.test.js
Labels: frontend

#741 [O2B-709] Display timestamps as date or raw timestamps
  CHANGELOG.md
  lib/public/Model.js
  lib/public/components/NavBar/index.js
  lib/public/utilities/formatting/formatTimestamp.js
  lib/public/utilities/frontLink.js
  lib/public/utilities/userPreferencesStore.js
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
  test/public/runs/overview.test.js
Labels: frontend

#745 Release 0.41.0
  CHANGELOG.md
  lib/public/views/About/Overview/index.js
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
  package-lock.json
  package.json
Labels: release

#750 [O2B-637] Fix markdown auto size
  lib/public/components/common/markdown/markdown.js
Labels: bug, frontend

#752 [O2B-732] Duration time showing unknown when running
  lib/public/views/Runs/formatRunDuration.js
Labels: frontend

#725 [O2B-677] Add some entities typedefs to help service factorization
  CHANGELOG.md
  Dockerfile
  lib/database/adapters/AttachmentAdapter.js
  lib/database/adapters/EnvironmentAdapter.js
  lib/database/adapters/EorReasonAdapter.js
  lib/database/adapters/FlpAdapter.js
  lib/database/adapters/FlpRunsAdapter.js
  lib/database/adapters/LhcFillAdapter.js
  lib/database/adapters/LogAdapter.js
  lib/database/adapters/RunAdapter.js
  lib/database/adapters/SubsystemAdapter.js
  lib/database/adapters/TagAdapter.js
  lib/database/adapters/UserAdapter.js
  lib/database/models/environment.js
  lib/database/models/eorreason.js
  lib/database/models/typedefs/SequelizeAttachment.js
  lib/database/models/typedefs/SequelizeEnvironment.js
  lib/database/models/typedefs/SequelizeEorReason.js
  lib/database/models/typedefs/SequelizeFlp.js
  lib/database/models/typedefs/SequelizeLhcFill.js
  lib/database/models/typedefs/SequelizeLog.js
  lib/database/models/typedefs/SequelizeReasonType.js
  lib/database/models/typedefs/SequelizeRun.js
  lib/database/models/typedefs/SequelizeSubsystem.js
  lib/database/models/typedefs/SequelizeTag.js
  lib/database/models/typedefs/SequelizeUser.js
  lib/database/repositories/EorReasonRepository.js
  lib/domain/entities/Attachment.js
  lib/domain/entities/Environment.js
  lib/domain/entities/EorReason.js
  lib/domain/entities/Flp.js
  lib/domain/entities/LhcFill.js
  lib/domain/entities/Log.js
  lib/domain/entities/Run.js
  lib/domain/entities/Subsystem.js
  lib/domain/entities/Tag.js
  lib/domain/entities/User.js
  lib/usecases/environment/CreateEnvironmentUseCase.js
  lib/usecases/run/GetAllRunsUseCase.js
  lib/usecases/tag/getTagsByTextUseCase.js
  test/e2e/environments.test.js
  test/public/runs/overview.test.js
  test/usecases/log/GetAllLogsUseCase.test.js
Labels: documentation, backend
