Repository AliceO2Group/Bookkeeping, pull requests merged in 2023-12, with the labels that each got.

#1250 [O2B-1051] add sorting to lhc periods page
  lib/public/views/lhcPeriods/ActiveColumns/lhcPeriodsActiveColumns.js
  lib/public/views/lhcPeriods/Overview/LhcPeriodsOverviewModel.js
  lib/public/views/lhcPeriods/Overview/LhcPeriodsOverviewPage.js
  test/public/lhcPeriods/overview.test.js
Labels: frontend

#1265 [O2B-1053] filtering by year on lhc periods page
  lib/public/views/lhcPeriods/ActiveColumns/lhcPeriodsActiveColumns.js
  lib/public/views/lhcPeriods/Overview/LhcPeriodsOverviewModel.js
  test/public/lhcPeriods/overview.test.js
Labels: frontend

#1274 Release 0.73.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#1255 [O2B-1059] Tags details pagination for Logs
  lib/domain/dtos/GetAllLogsByTagDto.js
  lib/public/views/Tags/Details/TagDetailsModel.js
  lib/public/views/Tags/Details/tagDetailsComponent.js
  lib/server/controllers/tags.controller.js
  lib/usecases/tag/GetLogsByTagUseCase.js
Labels: frontend

#1263 [O2B-1061] hide lhc fill information if beam mode is not STABLE BEAMS
  lib/database/seeders/20200713103855-runs.js
  lib/public/domain/enums/BeamModes.js
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
  lib/public/views/Runs/Details/lhcFillPanel.js
  test/api/runs.test.js
  test/lib/usecases/run/GetAllRunsUseCase.test.js
  test/lib/usecases/run/StartRunUseCase.test.js
  test/mocks/mock-qc-pdp-eos-report.js
  test/mocks/mock-shift-leader-eos-report.js
  test/public/runs/detail.test.js
  test/public/runs/overview.test.js
Labels: frontend

#1278 [O2B-1074] Remove spurious re-render on chart hover
  lib/public/components/common/chart/lineChart/lineChartComponent.js
Labels: frontend

#1277 [O2B-1075] Fix time input filter clear re-render
  lib/public/components/common/form/inputs/DateTimeInputModel.js
  lib/public/components/common/formatting/formatTimeRange.js
  lib/public/views/Statistics/StatisticsPageModel.js
Labels: frontend

#1273 [O2B-1024] Add rows number estimation
  lib/public/views/lhcPeriods/Overview/LhcPeriodsOverviewPage.js
  test/public/lhcPeriods/overview.test.js
Labels: frontend

#1275 [O2B-1071] Improvements on LHC Fills Overview page
  lib/public/views/LhcFills/ActiveColumns/lhcFillsActiveColumns.js
  lib/public/views/LhcFills/format/formatLhcFillsTimeLoss.js
  test/public/lhcFills/overview.test.js
Labels: frontend

#1282 [O2B-805] Fix broken FLP API tests and remove unutilized and broken FLP Log implementation
  lib/server/controllers/flps.controller.js
  lib/server/routers/flps.router.js
  lib/usecases/flp/GetLogsByFlpUseCase.js
  lib/usecases/flp/index.js
  test/api/flps.test.js
  test/api/index.js
  test/lib/usecases/flp/GetAllFlpsUseCase.test.js
  test/lib/usecases/flp/index.js
Labels: backend

#1285 [O2B-1078] runs overview extraction
  lib/public/Model.js
  lib/public/components/Filters/RunsFilter/o2stop.js
  lib/public/view.js
  lib/public/views/Home/Overview/index.js
  lib/public/views/Runs/Overview/RunsOverviewModel.js
  lib/public/views/Runs/Overview/RunsOverviewPage.js
  lib/public/views/Runs/Overview/exportRunsModal.js
  lib/public/views/Runs/RunsModel.js
  test/public/runs/overview.test.js
Labels: frontend

#1276 [O2B-970] Add mean efficiency line
  lib/public/components/common/chart/rendering/LineChartRenderer.js
  lib/public/components/common/chart/rendering/dataset/renderDatasetAsLine.js
  lib/public/components/common/chart/rendering/legend/renderDatasetLegend.js
  lib/public/views/Statistics/StatisticsPage.js
  lib/public/views/Statistics/charts/efficiencyChartComponent.js
Labels: frontend

#1279 [O2B-952] Fixed a bug where the tally of replies was not accurately reflected on the log overview pages
  lib/database/repositories/LogRepository.js
  lib/server/services/log/LogService.js
  lib/usecases/log/GetAllLogsUseCase.js
  lib/usecases/run/GetLogsByRunUseCase.js
  lib/usecases/subsystem/GetLogsBySubsystemUseCase.js
  lib/usecases/tag/GetLogsByTagUseCase.js
Labels: bug, backend

#1286 Release 0.74.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#1280 [O2B-1070] Add history column to environments overview page
  lib/public/domain/enums/statusAcronyms.js
  lib/public/views/Environments/ActiveColumns/environmentsActiveColumns.js
  lib/public/views/Environments/ColoredEnvironmentStatusComponent.js
  lib/public/views/Environments/format/displayEnvironmentStatusHistory.js
Labels: frontend

#1281 [O2B-930] Add LHC period to run change notifier email
  lib/server/services/lhcPeriod/getLhcPeriod.js
  lib/server/services/log/getLogOrFail.js
  lib/server/services/run/logEntriesCreation/logRunQualityChange.js
  lib/server/services/run/updateRun.js
  test/lib/usecases/run/UpdateRunUseCase.test.js
Labels: backend

#1287 [O2B-1081] logs refactor
  lib/public/Model.js
  lib/public/views/Home/Overview/index.js
  lib/public/views/Logs/Create/LogCreationModel.js
  lib/public/views/Logs/LogsModel.js
  lib/public/views/Logs/Overview/LogsOverviewModel.js
  lib/public/views/Logs/Overview/index.js
  test/public/logs/overview.test.js
Labels: frontend

#1262 [O2B-1057] Use infoLoggerButtonGroup component in Environments and Runs overviews
  lib/public/components/Log/log.js
  lib/public/components/Log/logLinkButton.js
  lib/public/components/common/clipboardTarget.js
  lib/public/components/common/selection/infoLoggerButtonGroup/CopyToClipboardComponent.js
  lib/public/components/common/selection/infoLoggerButtonGroup/identifierColumnAndActionsDropdown.js
  lib/public/components/common/selection/infoLoggerButtonGroup/infoLoggerButtonGroup.js
  lib/public/services/externalRouting/getInfologgerLinksUrls.js
  lib/public/views/Environments/ActiveColumns/environmentsActiveColumns.js
  lib/public/views/Environments/Details/EnvironmentDetailsPage.js
  lib/public/views/Environments/format/displayEnvironmentInfologgerLinks.js
  lib/public/views/Logs/Create/LogCreationModel.js
  lib/public/views/Logs/Create/logCreationComponent.js
  lib/public/views/Logs/Details/LogTreeViewModel.js
  lib/public/views/Logs/Details/logTreeViewComponent.js
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
  lib/public/views/Runs/Details/runDetailsComponent.js
  lib/public/views/Runs/format/displayRunNumber.js
Labels: frontend

#1264 [O2B-1062] GET API LOG should allow for exclusion filter
  lib/usecases/common/checkForFilterExclusion.js
  lib/usecases/log/GetAllLogsUseCase.js
  test/api/logs.test.js
Labels: backend

#1295 [O2B-1088] Put back run number filter
  lib/public/components/Filters/RunsFilter/runNumber.js
  lib/public/components/Filters/common/filtersPanelPopover.js
  lib/public/views/Runs/Overview/RunsOverviewPage.js
Labels: frontend

#1299 Add padding for filter button in LHC Periods page
  lib/public/views/lhcPeriods/Overview/LhcPeriodsOverviewPage.js
Labels: frontend

#1297 [O2B-1077] Add margins between popover and screen edges
  lib/public/components/common/popover/PopoverEngine.js
  lib/public/components/common/popover/popover.js
Labels: frontend

#1296 [O2B-1066]: Added extra check for empty for log environment filter
  lib/public/views/Logs/Overview/LogsOverviewModel.js
Labels: bug, frontend

#1294 [1084] add getOrCreate function to UserService
  lib/server/WebUiServer.js
  lib/server/services/user/UserService.js
  lib/server/services/user/createOrUpdateUser.js
  lib/usecases/index.js
  lib/usecases/user/CreateOrUpdateUser.js
  test/lib/server/services/index.js
  test/lib/server/services/user/UserService.test.js
  test/lib/server/services/user/createOrUpdateUser.test.js
  test/lib/server/services/user/index.js
Labels: backend

#1305 Release 0.75.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#1293 [O2B-883]: Add bold line for detector quality in overview
  lib/public/app.css
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
  lib/public/views/Runs/format/formatRunDetectorsInline.js
Labels: frontend

#1311 [O2B-1096] Fix run overview details link
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
Labels: bug, frontend

#1312 [O2B-1097] Write environments ids in white in overview page
  lib/public/components/common/selection/infoLoggerButtonGroup/identifierColumnAndActionsDropdown.js
Labels: frontend

#1306 [O2B-1095] Fix log's attachment token
  lib/public/views/Logs/Details/logTreeViewComponent.js
Labels: bug, frontend

#1303 [O2B-926] Added button to overview for PHYSICS filter
  docs/get-started.md
  lib/public/components/Filters/RunsFilter/definitionFilter.js
  lib/public/components/Filters/RunsFilter/runNumber.js
  lib/public/domain/enums/RunDefinition.js
  lib/public/views/Runs/Overview/RunsOverviewPage.js
  lib/public/views/Runs/Overview/showPhysicsButton.js
Labels: frontend

#1304 [O2B-1085] update proto files and grpc run controller with new user struct
  proto/common.proto
  proto/run.proto
Labels: backend
