Repository AliceO2Group/Bookkeeping, pull requests merged in 2023-03, with the labels that each got.

#898 [O2B-831] Update git version in Dockerfile
  Dockerfile
Labels: dependencies, docker

#886 [O2B-830] Add getting started documentation
  docker-compose.dev.yml
  docs/CONTRIBUTING.md
  docs/DEVELOPMENT.md
  docs/data-model.md
  docs/get-started.md
  package-lock.json
  package.json
Labels: documentation, docker

#894 [O2B-833] Fix runs overview warning icon wrap
  lib/public/views/Runs/format/formatRunDuration.js
  lib/public/views/Runs/format/formatRunEnd.js
  lib/public/views/Runs/format/formatRunStart.js
  test/public/runs/overview.test.js
Labels: bug, frontend

#901 [O2B-842] Add NOISE as run type for CALIBRATION run definition
  docs/RUN_DEFINITIONS.md
  lib/server/services/run/getRunDefinition.js
  test/lib/server/services/run/getRunDefinition.test.js
  test/mocks/mock-run.js
Labels: backend

#896 [O2B-765] Fix tag update related logs refresh
  lib/public/Model.js
  lib/public/components/common/navigation/tabLink.js
  lib/public/components/common/table/noDataRow.js
  lib/public/components/common/table/rows.js
  lib/public/components/common/table/table.js
  lib/public/components/tag/tagDetail.js
  lib/public/utilities/targetURL.js
  lib/public/view.js
  lib/public/views/LhcFills/LhcFills.js
  lib/public/views/Logs/ActiveColumns/logsActiveColumns.js
  lib/public/views/Logs/ActiveColumns/reducedLogsActiveColumns.js
  lib/public/views/Runs/Details/RunDetailsPage.js
  lib/public/views/Tags/Create/index.js
  lib/public/views/Tags/Details/TagDetailsModel.js
  lib/public/views/Tags/Details/TagDetailsPage.js
  lib/public/views/Tags/Details/index.js
  lib/public/views/Tags/Overview/index.js
  lib/public/views/Tags/Tags.js
  test/public/defaults.js
  test/public/runs/detail.test.js
  test/public/tags/detail.test.js
Labels: bug, frontend

#899 [O2B-809] Add gRPC endpoint to fetch a run
  cxx-client/.gitignore
  cxx-client/CMakeLists.txt
  cxx-client/README.md
  cxx-client/cmake/BookkeepingApiConfig.cmake.in
  cxx-client/cmake/BookkeepingProtoApiConfig.cmake.in
  cxx-client/example/exampleProtoServices.cxx
  cxx-client/example/exampleSpecificServices.cxx
  cxx-client/include/BookkeepingApi/BkpProtoClient.h
  cxx-client/include/BookkeepingApi/BkpProtoClientFactory.h
  cxx-client/include/BookkeepingApi/RunProtoClient.h
  cxx-client/src/BkpProtoClientFactory.cxx
  cxx-client/src/grpc/GrpcBkpProtoClient.cxx
  cxx-client/src/grpc/GrpcBkpProtoClient.h
  cxx-client/src/grpc/services/GrpcRunProtoClient.cxx
  cxx-client/src/grpc/services/GrpcRunProtoClient.h
  lib/server/controllers/gRPC/GRPCRunController.js
  lib/server/services/run/RunService.js
  proto/common.proto
  proto/run.proto
Labels: backend

#903 Release 0.52.0
  CHANGELOG.md
  lib/public/views/About/Overview/index.js
  package-lock.json
  package.json
Labels: release

#905 [O2B-838] Create a role based access control middleware
  lib/domain/enums/BkpRoles.js
  lib/server/WebUiServer.js
  lib/server/controllers/tags.controller.js
  lib/server/middleware/rbac.middleware.js
  lib/server/routers/tags.router.js
  test/lib/server/index.js
  test/lib/server/middleware/index.js
  test/lib/server/middleware/rbac.middleware.test.js
Labels: backend

#911 [O2B-840] Create simple run duration formatting function
  lib/public/services/lhcFill/LhcFillStatisticsExtractor.js
  lib/public/services/run/TimeBetweenRunsTracker.js
  lib/public/services/run/constants.mjs
  lib/public/utilities/durationUtils.mjs
  lib/public/utilities/formatting/formatDuration.mjs
  lib/public/utilities/formatting/formatRunDuration.mjs
  lib/public/views/LhcFills/ActiveColumns/lhcFillsActiveColumns.js
  lib/public/views/LhcFills/Detail/commonLhcFillDisplayConfiguration.js
  lib/public/views/LhcFills/Detail/lhcFillDetailsComponent.js
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
  lib/public/views/Runs/Details/runDetailsConfiguration.js
  lib/public/views/Runs/format/displayRunDuration.js
  test/index.js
  test/lib/public/index.js
  test/lib/public/utilities/formatting/formatRunDuration.test.js
  test/lib/public/utilities/formatting/index.js
  test/lib/public/utilities/index.js
Labels: frontend, backend

#912 [O2B-840] Improve environment seeders
  lib/database/seeders/20220412122043-environments.js
  lib/database/seeders/20230124105627-environment-history.js
  test/lib/server/services/environment/EnvironmentService.test.js
  test/lib/server/services/environmentHistoryItem/getEnvironmentHistoryItem.test.js
  test/public/envs/detailsPage.test.js
  test/public/envs/overview.test.js
Labels: backend

#916 [O2B-840] Add user-created log to report
  lib/server/services/eosReport/EosReportService.js
  lib/server/services/log/getLogsByUserInPeriod.js
  test/lib/server/services/eosReport/EosReportService.test.js
  test/lib/server/services/eosReport/index.js
  test/mocks/mock-eos-report.js
Labels: backend

#914 [O2B-841] Add EOS report creation page
  lib/domain/dtos/eorReport/CreateEosReportDto.js
  lib/public/Model.js
  lib/public/app.css
  lib/public/components/common/markdown/markdown.js
  lib/public/view.js
  lib/public/views/EosReport/EosReportModel.js
  lib/public/views/EosReport/create/EosReportCreationModel.js
  lib/public/views/EosReport/create/EosReportCreationPage.js
  lib/public/views/EosReport/create/eosReportCreationComponent.js
  lib/public/views/Logs/Overview/index.js
  lib/server/WebUiServer.js
  lib/server/controllers/eosReport.controller.js
  lib/server/services/eosReport/formatEosReport.js
  lib/server/services/eosReport/getShiftFromTimestamp.js
  test/api/eosReport.test.js
  test/mocks/mock-eos-report.js
  test/public/defaults.js
  test/public/eosReport/creation.test.js
  test/public/eosReport/index.js
Labels: frontend
