Repository AliceO2Group/Bookkeeping, pull requests merged in 2023-09, with the labels that each got.

#1132 [O2B-971] Improve chart axis display
  lib/public/components/common/chart/lineChart/renderLineChart.js
  lib/public/components/common/chart/rendering/axis/AxisRenderer.js
  lib/public/components/common/chart/rendering/axis/BottomAxisRenderer.js
  lib/public/components/common/chart/rendering/axis/LeftAxisRenderer.js
  lib/public/components/common/chart/rendering/dataset/renderDatasetAsLine.js
  lib/public/components/common/chart/rendering/dataset/renderDatasetAsPointCloud.js
  lib/public/components/common/chart/rendering/renderHorizontalAxis.js
  lib/public/components/common/chart/rendering/renderVerticalAxis.js
  lib/public/components/common/chart/structures/Coordinates.js
  lib/public/services/lhcFill/computeLhcFillStatistics.js
  lib/public/views/Statistics/StatisticsPage.js
Labels: frontend

#1096 [O2B-947] Add API routes to create and retrieve logs with lhcFills
  lib/database/adapters/LogAdapter.js
  lib/domain/dtos/CreateLogDto.js
  lib/server/services/lhcFill/checkLhcFillsExistOrFail.js
  lib/server/services/lhcFill/getLhcFillByNumberOrFail.js
  lib/server/services/log/LogService.js
  lib/server/services/log/createLog.js
  lib/server/services/run/RunService.js
  lib/server/services/run/logEntriesCreation/logCalibrationStatusChange.js
  lib/server/services/run/logEntriesCreation/logRunQualityChange.js
  lib/usecases/log/CreateLogUseCase.js
  lib/usecases/log/GetAllLogsUseCase.js
  lib/usecases/log/GetLogUseCase.js
  test/api/logs.test.js
  test/api/shift.test.js
  test/lib/server/services/eosReport/EosReportService.test.js
  test/lib/server/services/shift/ShiftService.test.js
  test/lib/usecases/log/CreateLogUseCase.test.js
  test/public/logs/overview.test.js
Labels: backend

#1133 [O2B-979] Display environments in log tree view
  lib/public/components/Log/log.js
  lib/usecases/log/GetAllLogsUseCase.js
  lib/usecases/log/GetLogUseCase.js
  test/public/logs/detail.test.js
Labels: frontend, backend

#1100 [O2B-948] Add filter logs by LHC fill to API
  lib/database/repositories/LogLhcFillsRepository.js
  lib/database/repositories/LogRunsRepository.js
  lib/database/repositories/index.js
  lib/database/seeders/20230809094631-log-lhcfills.js
  lib/database/tables/loglhcfills.js
  lib/domain/dtos/GetAllLogsDto.js
  lib/server/services/log/createLog.js
  lib/usecases/log/GetAllLogsUseCase.js
  test/lib/usecases/log/GetAllLogsUseCase.test.js
Labels: backend

#1110 [O2B-964] Fix for O2B-929 - show null run detector quality
  lib/public/views/Runs/format/formatRunDetectors.js
Labels: frontend

#1134 Removed getEnvironmentsByLogId API route
  lib/server/controllers/logs.controller.js
  lib/server/routers/logs.router.js
  lib/server/services/environment/EnvironmentService.js
  lib/server/services/environment/getAllEnvironmentsByLogId.js
  test/api/logs.test.js
Labels: backend

#1135 [O2B-969] Include fills without runs in statistics
  lib/database/migrations/20230901090207-include-fill-without-runs-in-statistics.js
  test/lib/server/services/statistics/StatisticsService.test.js
Labels: backend

#1136 Release 0.63.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#1138 [O2B-991] Remove duplicate LHC fill input in log creation
  lib/public/views/Logs/Create/logCreationComponent.js
Labels: bug, frontend

#1004 [OGUI-1369] Replace depracated use-output and archived GH action
  .github/workflows/release.yml
Labels: github_actions

#1141 Update GH action nodejs version
  .github/workflows/bookkeeping.yml
  .github/workflows/release.yml
  package.json
Labels: CI

#1140 [O2B-992] Detector quality requires justification
  lib/domain/dtos/UpdateRunDto.js
  lib/public/views/Runs/Details/RunPatch.js
  lib/public/views/Runs/format/formatRunDetectors.js
  lib/server/services/run/RunService.js
  lib/usecases/run/UpdateRunUseCase.js
  test/api/runs.test.js
  test/lib/server/services/run/RunService.test.js
  test/lib/usecases/run/UpdateRunUseCase.test.js
  test/public/logs/overview.test.js
  test/public/runs/detail.test.js
Labels: frontend, backend

#1142 [O2B-993] Run quality update require justification
  lib/domain/dtos/UpdateRunDto.js
  lib/public/views/Runs/Details/RunPatch.js
  lib/public/views/Runs/format/formatRunQuality.js
  lib/server/services/run/RunService.js
  lib/server/services/run/logEntriesCreation/logRunQualityChange.js
  lib/server/services/run/updateRun.js
  lib/usecases/run/UpdateRunUseCase.js
  test/api/runs.test.js
  test/lib/server/services/run/RunService.test.js
  test/lib/usecases/run/UpdateRunUseCase.test.js
  test/public/logs/overview.test.js
Labels: backend

#1143 release 0.64.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#1149 [O2B-999] Add a button to create log from LHC fill details page
  lib/public/Model.js
  lib/public/components/common/errorAlert.js
  lib/public/views/LhcFills/Detail/lhcFillDetailsComponent.js
  lib/public/views/Logs/Create/LogCreationModel.js
  lib/public/views/Logs/Create/LogCreationPage.js
  lib/public/views/Logs/Logs.js
  lib/public/views/Runs/Details/runDetailsComponent.js
  test/public/lhcFills/detail.test.js
  test/public/runs/detail.test.js
Labels: frontend

#1152 [O2B-1003] Make justification input like other inputs
  lib/public/views/EosReport/create/typeSpecific/commentInput.js
  lib/public/views/EosReport/create/typeSpecific/eosFormEcsSpecificPart.js
  lib/public/views/Runs/format/formatRunCalibrationStatus.js
  lib/public/views/Runs/format/formatRunDetectors.js
  lib/public/views/Runs/format/formatRunQuality.js
Labels: frontend

#1154 [O2B-1004] Fix overview runs filtering by tags `or`
  lib/usecases/run/GetAllRunsUseCase.js
  test/lib/usecases/run/GetAllRunsUseCase.test.js
Labels: bug, backend

#1155 [O2B-989] filtering runs by updated at other solution
  lib/database/seeders/20200713103855-runs.js
  lib/domain/dtos/filters/RunFilterDto.js
  lib/usecases/run/GetAllRunsUseCase.js
  test/api/runs.test.js
  test/lib/usecases/run/GetAllRunsUseCase.test.js
Labels: backend, javascript

#1156 [O2B-1005] Allow no-justification when run quality goes from none to good or test
  lib/public/views/Runs/Details/RunPatch.js
  lib/public/views/Runs/format/formatRunQuality.js
  lib/server/services/run/updateRun.js
  test/lib/server/services/run/RunService.test.js
Labels: frontend, backend

#1153 [O2B-998] Add a button to create log from environment details page
  lib/public/views/Environments/Details/EnvironmentDetailsPage.js
  lib/public/views/Logs/Create/LogCreationModel.js
  lib/public/views/Logs/Logs.js
  test/public/envs/detailsPage.test.js
Labels: frontend

#1157 Release 0.65.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#1163 [O2B-1001] Add endpoint to fetch logs of a given LHC fill
  docs/backend-architecture.md
  lib/domain/dtos/DtoFactory.js
  lib/server/controllers/lhcFill.controller.js
  lib/server/routers/lhcFills.router.js
  lib/server/services/log/LogService.js
  lib/usecases/log/GetAllLogsUseCase.js
  test/api/lhcFills.test.js
  test/lib/server/services/log/LogService.test.js
Labels: backend

#1164 [O2B-1011] Fix chart tooltip alignment
  lib/public/components/common/chart/lineChart/renderLineChart.js
Labels: bug, frontend

#1166 [O2B-1002] Add endpoint to fetch environments logs
  lib/server/controllers/environments.controller.js
  lib/server/routers/environments.router.js
  lib/server/services/log/LogService.js
  test/api/environments.test.js
  test/lib/server/services/log/LogService.test.js
Labels: backend

#1168 [O2B-849] Rework popover to use portal
  lib/public/app.css
  lib/public/components/common/popover/overflowBalloon.js
  lib/public/components/common/popover/popover.js
  lib/public/components/common/popover/tooltip.js
  lib/public/components/common/table/headers.js
  lib/public/utilities/clipToViewport.js
  lib/public/utilities/createPortal.js
  lib/public/views/Environments/format/displayEnvironmentStatus.js
  lib/public/views/LhcFills/Detail/lhcFillDetailsComponent.js
  lib/public/views/Runs/format/displayRunDuration.js
  lib/public/views/Runs/format/formatRunEnd.js
  lib/public/views/Runs/format/formatRunStart.js
  test/public/defaults.js
  test/public/lhcFills/detail.test.js
  test/public/logs/create.test.js
  test/public/runs/detail.test.js
  test/public/runs/overview.test.js
Labels: frontend

#1169 [O2B-849] Add tag description
  lib/public/components/common/selection/SelectionModel.js
  lib/public/components/common/selection/dropdown/SelectionDropdownModel.js
  lib/public/components/tag/tagToOption.js
  lib/public/components/tag/tagToOptionWithArchiveBadge.js
  lib/public/utilities/createPortal.js
  test/public/logs/overview.test.js
Labels: frontend

#1170 [O2B-1002] Remove run tab title
  lib/public/views/Environments/Details/EnvironmentDetailsPage.js
  test/public/envs/detailsPage.test.js
Labels: frontend

#1171 Release 0.66.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#1175 [O2B-1015] Display horizontal line for ticks
  lib/public/app.css
  lib/public/components/common/chart/lineChart/lineChartComponent.js
  lib/public/components/common/chart/lineChart/renderLineChart.js
  lib/public/components/common/chart/rendering/axis/AxisRenderer.js
  lib/public/components/common/chart/rendering/grid/renderHorizontalGrid.js
Labels: frontend

#1174 [O2B-1014] Add data per week graph
  lib/database/models/index.js
  lib/database/models/stableBeamsRun.js
  lib/database/repositories/StableBeamRunsRepository.js
  lib/database/repositories/index.js
  lib/domain/entities/statistics/LhcFillStatistics.js
  lib/domain/entities/statistics/WeeklyDataSize.js
  lib/public/Model.js
  lib/public/components/TabbedPanel/tabbedPanelComponent.js
  lib/public/components/common/chart/lineChart/renderLineChart.js
  lib/public/components/common/remoteDataDisplay.js
  lib/public/utilities/fetch/getRemoteData.js
  lib/public/utilities/fetch/getRemoteDataSlice.js
  lib/public/views/Environments/Details/EnvironmentDetailsModel.js
  lib/public/views/Statistics/StatisticsPage.js
  lib/public/views/Statistics/StatisticsPageModel.js
  lib/public/views/Statistics/chartColors.js
  lib/public/views/Statistics/charts/efficiencyChartComponent.js
  lib/public/views/Statistics/charts/weeklyDataSizeChartComponent.js
  lib/server/controllers/statistics.controller.js
  lib/server/routers/statistics.router.js
  lib/server/services/statistics/StatisticsService.js
  test/api/statistics.test.js
  test/lib/server/services/statistics/StatisticsService.test.js
Labels: frontend, backend

#1176 [O2B-1016] Add mean duration graph
  lib/public/components/common/chart/lineChart/renderLineChart.js
  lib/public/components/common/chart/rendering/dataset/renderDatasetAsLine.js
  lib/public/views/Statistics/StatisticsPage.js
  lib/public/views/Statistics/StatisticsPageModel.js
  lib/public/views/Statistics/charts/meanRunDurationChartComponent.js
Labels: frontend

#1177 [O2B-831] Update docker dependencies
  Dockerfile
Labels: dependencies, docker

#1178 [O2B-831] Use mariadb production version in docker
  docker-compose.yml
Labels: dependencies, docker

#1179 [O2B-1017] Fix popover misbehavior when moving from parent to child elt
  lib/public/app.css
  lib/public/components/common/popover/overflowBalloon.js
  lib/public/components/common/popover/tooltip.js
  test/public/defaults.js
  test/public/logs/overview.test.js
  test/public/runs/overview.test.js
Labels: frontend

#1180 Release 0.67.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release
