Repository AliceO2Group/Bookkeeping, pull requests merged in 2023-08, with the labels that each got.

#1078 O2B-937 About page enhancements
  lib/public/Model.js
  lib/public/views/About/About.js
  lib/public/views/About/Overview/index.js
  test/public/about/overview.test.js
Labels: frontend

#1092 [O2B-935] Run tables column rework
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
  lib/public/views/Runs/Details/runDetailsConfiguration.js
  test/public/runs/detail.test.js
  test/public/runs/overview.test.js
Labels: frontend

#1099 [O2B-931] Create endpoint to fetch fill statistics
  lib/database/adapters/LhcFillStatisticsAdapter.js
  lib/database/adapters/index.js
  lib/database/migrations/20230717163538-add-fill-statistics-view.js
  lib/database/models/index.js
  lib/database/models/lhcFillStatistics.js
  lib/database/models/typedefs/SequelizeLhcFillStatistics.js
  lib/database/repositories/LhcFillRepository.js
  lib/database/repositories/LhcFillStatisticsRepository.js
  lib/database/repositories/index.js
  lib/domain/entities/LhcFillStatistics.js
  lib/public/services/lhcFill/LhcFillStatisticsExtractor.js
  lib/public/views/LhcFills/ActiveColumns/lhcFillsActiveColumns.js
  lib/public/views/LhcFills/Detail/lhcFillDetailsComponent.js
  lib/server/controllers/statistics.controller.js
  lib/server/routers/index.js
  lib/server/routers/statistics.router.js
  lib/server/services/environment/getEnvironmentsInPeriod.js
  lib/server/services/statistics/StatisticsService.js
  lib/server/utilities/timestampToMysql.js
  test/api/index.js
  test/api/statistics.test.js
  test/lib/server/services/index.js
  test/lib/server/services/statistics/StatisticsService.test.js
  test/lib/server/services/statistics/index.js
  test/public/lhcFills/detail.test.js
  test/public/lhcFills/overview.test.js
Labels: backend

#1097 Shows 'Collapse all' button for single logs
  lib/public/views/Logs/Details/LogTreeViewModel.js
  test/public/logs/create.test.js
Labels: bug, frontend

#1102 [O2B-958] Display statistics as graph
  lib/public/app.css
  lib/public/assets/d3.min.js
  lib/public/components/common/chart/lineChart/lineChartComponent.js
  lib/public/components/common/chart/lineChart/renderLineChart.js
  lib/public/components/common/chart/rendering/datasetRendering/renderDatasetAsLine.js
  lib/public/components/common/chart/rendering/datasetRendering/renderDatasetAsPointCloud.js
  lib/public/components/common/chart/rendering/renderHorizontalAxis.js
  lib/public/components/common/chart/rendering/renderVerticalAxis.js
  lib/public/components/common/chart/structures/BoundingBox.js
  lib/public/components/common/chart/structures/Point.js
  lib/public/components/common/chart/structures/PointLocator.js
  lib/public/components/common/chart/structures/Range.js
  lib/public/views/Statistics/StatisticsPage.js
  package-lock.json
  package.json
Labels: frontend

#1103 [O2B-958] Add tooltip on point hover
  lib/public/app.css
  lib/public/components/common/chart/lineChart/lineChartComponent.js
  lib/public/components/common/chart/lineChart/renderLineChart.js
  lib/public/utilities/createPortal.js
  lib/public/views/LhcFills/Overview/index.js
  lib/public/views/Statistics/StatisticsPage.js
  package-lock.json
  package.json
Labels: frontend

#1084 [O2B-939] Add environment relation
  lib/database/adapters/LogAdapter.js
  lib/database/adapters/index.js
  lib/database/migrations/20230802095128-create-log-environments.js
  lib/database/models/environment.js
  lib/database/models/log.js
  lib/database/models/typedefs/SequelizeLog.js
  lib/database/repositories/LogEnvironmentsRepository.js
  lib/database/repositories/index.js
  lib/database/seeders/20230802102102-log-environments.js
  lib/database/tables/index.js
  lib/database/tables/logenvironments.js
Labels: backend, db

#1083 [O2B-681] Filter runs by EOR reason type
  lib/domain/dtos/filters/RunFilterDto.js
  lib/public/components/Filters/RunsFilter/EorReasonsFilterModel.js
  lib/public/components/Filters/RunsFilter/eorReasonFilter.js
  lib/public/components/Filters/common/filtersPanel.js
  lib/public/components/runEorReasons/runEorReasonSelection.js
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
  lib/public/views/Runs/Runs.js
  lib/usecases/run/GetAllRunsUseCase.js
  test/public/runs/overview.test.js
Labels: frontend

#1066 [O2B-933] Allow for concurrent DPL process creation in bookkeeping
  lib/database/repositories/Repository.js
  lib/server/services/dpl/DplProcessService.js
  lib/server/services/dpl/getOrCreateDplDetector.js
  lib/server/services/dpl/getOrCreateDplProcess.js
  lib/server/services/dpl/getOrCreateDplProcessType.js
  lib/server/services/host/getOrCreateHost.js
  lib/utilities/cacheAsyncFunction.js
  test/lib/utilities/cacheAsyncFunction.test.js
  test/lib/utilities/index.js
Labels: bug, backend

#1104 Release 0.61.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#1095 [O2B-918] Autofill EoS report
  lib/public/app.css
  lib/public/components/common/contextualMessage/contextualInfo.js
  lib/public/components/common/contextualMessage/contextualMessage.js
  lib/public/views/EosReport/create/EosReportCreationModel.js
  lib/public/views/EosReport/create/eosReportCreationComponent.js
  lib/server/services/eosReport/formatEosReport.js
  lib/server/services/log/getLogsByTitle.js
  lib/server/services/shift/ShiftService.js
  test/lib/server/services/eosReport/EosReportService.test.js
  test/public/eosReport/ecs-creation.test.js
Labels: frontend, backend

#1094 [O2B-946] Add Logs-LhcFills table to database
  lib/database/adapters/LogAdapter.js
  lib/database/adapters/index.js
  lib/database/migrations/20230809084256-create-log-lhcfills.js
  lib/database/models/lhcFill.js
  lib/database/models/log.js
  lib/database/models/typedefs/SequelizeLogLhcFill.js
  lib/database/repositories/LogLhcfillsRepository.js
  lib/database/seeders/20230809094631-log-lhcfills.js
  lib/database/tables/index.js
  lib/database/tables/loglhcfills.js
Labels: backend, db

#1085 [O2B-940] Add environment log api route
  lib/database/migrations/20230802095128-create-log-environments.js
  lib/database/models/environment.js
  lib/domain/dtos/CreateLogDto.js
  lib/domain/entities/Log.js
  lib/server/controllers/logs.controller.js
  lib/server/routers/logs.router.js
  lib/server/services/environment/EnvironmentService.js
  lib/server/services/environment/getAllEnvironments.js
  lib/server/services/environment/getAllEnvironmentsByLogId.js
  lib/server/services/environment/getAllEnvironmentsOrFail.js
  lib/server/services/log/LogService.js
  lib/server/services/log/createLog.js
  lib/server/services/run/RunService.js
  lib/server/services/run/updateRun.js
  lib/usecases/log/CreateLogUseCase.js
  test/api/logs.test.js
  test/api/shift.test.js
  test/lib/server/services/eosReport/EosReportService.test.js
  test/lib/server/services/shift/ShiftService.test.js
  test/public/logs/overview.test.js
Labels: backend

#1108 [O2B-963] Fix fill efficiency tooltip value
  lib/public/views/Statistics/StatisticsPage.js
Labels: bug, frontend

#1107 [O2B-961] Add calibration status to calibration runs
  lib/database/adapters/RunAdapter.js
  lib/database/migrations/20230821070256-add-run-calibration-status.js
  lib/database/models/run.js
  lib/database/models/typedefs/SequelizeRun.js
  lib/database/seeders/20200713103855-runs.js
  lib/domain/dtos/UpdateRunDto.js
  lib/domain/entities/Run.js
  lib/domain/enums/RunCalibrationStatus.js
  lib/public/components/Detail/detailsList.js
  lib/public/domain/enums/RunCalibrationStatus.js
  lib/public/domain/enums/RunDefinition.js
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
  lib/public/views/Runs/Details/RunPatch.js
  lib/public/views/Runs/Details/runDetailsConfiguration.js
  lib/public/views/Runs/coloredCalibrationStatusComponent.js
  lib/public/views/Runs/format/formatRunCalibrationStatus.js
  lib/server/services/run/createRun.js
  lib/server/services/run/updateRun.js
  test/api/runs.test.js
  test/lib/server/services/run/RunService.test.js
  test/public/runs/detail.test.js
  test/public/runs/overview.test.js
Labels: frontend, backend

#1109 Fixed incorrectly named environment model
  lib/database/models/environment.js
  lib/server/services/environment/getAllEnvironmentsByLogId.js
Labels: backend

#1111 [O2B-965] Fix for O2B-935 - show EPN as 'ON' if nEpns not defined
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
  lib/public/views/Runs/Details/runDetailsConfiguration.js
Labels: frontend

#1086 [O2B-941] Add filtering to environment log api route
  lib/domain/dtos/GetAllLogsDto.js
  lib/domain/dtos/filters/EnvironmentsFilterDto.js
  lib/server/services/environment/getAllEnvironmentsOrFail.js
  lib/server/services/log/LogService.js
  lib/server/services/log/createLog.js
  lib/usecases/log/GetAllLogsUseCase.js
  lib/usecases/log/GetLogUseCase.js
  test/lib/usecases/log/GetAllLogsUseCase.test.js
Labels: backend

#1117 [O2B-972] Increase statistics graphs points size
  lib/public/views/Statistics/StatisticsPage.js
Labels: frontend

#1115 [O2B-962] Create log when calibration status moves from failed
  lib/domain/dtos/UpdateRunDto.js
  lib/public/app.css
  lib/public/components/Detail/detailsList.js
  lib/public/views/Runs/Details/RunDetailsModel.js
  lib/public/views/Runs/Details/RunPatch.js
  lib/public/views/Runs/Details/runDetailsComponent.js
  lib/public/views/Runs/format/formatRunCalibrationStatus.js
  lib/server/controllers/gRPC/GRPCRunController.js
  lib/server/services/run/RunService.js
  lib/server/services/run/logEntriesCreation/logCalibrationStatusChange.js
  lib/server/services/run/logEntriesCreation/logRunQualityChange.js
  lib/server/services/run/refreshRunsDefinitions.js
  lib/server/services/run/updateRun.js
  lib/usecases/run/EndRunUseCase.js
  lib/usecases/run/UpdateRunUseCase.js
  test/api/runs.test.js
  test/lib/server/services/run/RunService.test.js
  test/lib/server/services/run/updateRun.test.js
Labels: frontend, backend

#1118 Release 0.63.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#1088 [O2B-943] Add front end environment to log
  lib/public/views/Logs/Create/LogCreationModel.js
  lib/public/views/Logs/Create/logCreationComponent.js
  test/public/logs/create.test.js
Labels: frontend

#1123 [O2B-976] Fix calibration runs creation
  CHANGELOG.md
  lib/server/services/run/createRun.js
  test/lib/server/services/run/RunService.test.js
Labels: bug, backend
