Repository AliceO2Group/Bookkeeping, pull requests merged in 2023-01, with the labels that each got.

#834 [O2B-798] Rename hostName to hostname in flp proto
  lib/server/controllers/gRPC/GRPCFlpController.js
  proto/flp.proto
Labels: backend

#795 [O2B-725] Separate LHC fill into tabs to display physics or all runs
  lib/public/services/lhcFill/addStatisticsToLhcFill.js
  lib/public/views/LhcFills/Detail/LhcFillDetailsModel.js
  lib/public/views/LhcFills/Detail/commonLhcFillDisplayConfiguration.js
  lib/public/views/LhcFills/Detail/lhcFillDetailsComponent.js
  lib/public/views/LhcFills/Detail/lhcFillDisplayConfiguration.js
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
  lib/public/views/Runs/Details/lhcFillPanel.js
  lib/usecases/lhcFill/GetLhcFillUseCase.js
  test/public/lhcFills/detail.test.js
  test/usecases/lhcFill/GetLhcFillUseCase.test.js
Labels: frontend, backend

#787 [O2B-607] Add possibility to archive tags
  lib/database/adapters/TagAdapter.js
  lib/database/migrations/20221017102948-archive-tags.js
  lib/database/models/tag.js
  lib/database/models/typedefs/SequelizeTag.js
  lib/database/seeders/20200511151010-tags.js
  lib/database/utilities/QueryBuilder.js
  lib/domain/dtos/UpdateTagDto.js
  lib/domain/entities/Tag.js
  lib/public/components/common/selection/SelectionModel.js
  lib/public/components/tag/remoteDataTagPicker.js
  lib/public/components/tag/tagDetail.js
  lib/public/components/tag/tagToOptionWithArchiveBadge.js
  lib/public/views/Logs/Create/LogCreationPage.js
  lib/public/views/Runs/Details/RunDetailsModel.js
  lib/public/views/Runs/Details/editTagsPanel.js
  lib/public/views/Tags/ActiveColumns/tagsActiveColumns.js
  lib/public/views/Tags/Details/index.js
  lib/public/views/Tags/Tags.js
  lib/server/controllers/tags.controller.js
  lib/server/services/run/RunService.js
  lib/server/services/run/getRunOrFail.js
  lib/server/services/run/updateRun.js
  lib/server/services/tag/getAllTagsByTextOrFail.js
  lib/server/services/tag/getTagsByText.js
  lib/usecases/tag/GetAllTagsUseCase.js
  lib/usecases/tag/UpdateTagUseCase.js
  spec/openapi-source.yaml
  spec/openapi.yaml
  test/e2e/logs.test.js
  test/e2e/tags.test.js
  test/public/logs/create.test.js
  test/public/tags/detail.test.js
  test/usecases/tag/GetAllTagsUseCase.test.js
  test/usecases/tag/UpdateTagUseCase.test.js
Labels: frontend, backend

#843 [OGUI-1303] Migrate to v2 web-ui framework
  lib/public/index.html
  lib/public/index.js
  package-lock.json
  package.json
Labels: dependencies, backend

#844 Release/0.48.0
  CHANGELOG.md
  lib/public/views/About/Overview/index.js
  package-lock.json
  package.json
Labels: release

#849 [O2B-802] Fix detectors items wrap
  lib/public/components/RunDetail/index.js
Labels: bug, frontend

#855 [O2B-792] Remove spec directory accidentally re-introduced
  spec/openapi-source.yaml
  spec/openapi.yaml
Labels: backend

#802 [O2B-777] Set quality to 'good' when ending physics runs
  lib/database/seeders/20200713103855-runs.js
  lib/server/services/detector/getAllDetectorsByNameOrFail.js
  lib/server/services/run/updateRun.js
  test/api/runs.test.js
  test/lib/usecases/run/EndRunUseCase.test.js
  test/lib/usecases/run/GetAllRunsUseCase.test.js
  test/public/home/overview.test.js
  test/public/logs/overview.test.js
  test/public/runs/overview.test.js
Labels: backend
