Repository AliceO2Group/Bookkeeping, pull requests merged in 2023-06, with the labels that each got.

#1005 [O2B-898] Clean lost runs and environments every 30 seconds
  lib/application.js
  lib/config/services.js
  lib/server/routers/environments.router.js
  lib/server/services/environment/transitionToErrorLostEnvironments.js
  lib/server/services/housekeeping/handleLostRunsAndEnvironments.js
  lib/server/services/run/setO2StopOfLostRuns.js
  package-lock.json
  package.json
Labels: backend

#1007 release 0.56.0
  CHANGELOG.md
  lib/public/views/About/Overview/index.js
  package-lock.json
  package.json
Labels: release

#1008 [O2B-901] Add flag to enable housekeeping
  lib/application.js
  lib/config/services.js
Labels: backend

#976 [O2B-866] Create DPL tasks model
  docs/data-model.md
  lib/database/adapters/HostAdapter.js
  lib/database/adapters/dpl/DplDetectorAdapter.js
  lib/database/adapters/dpl/DplProcessAdapter.js
  lib/database/adapters/dpl/DplProcessExecutionAdapter.js
  lib/database/adapters/dpl/DplProcessTypeAdapter.js
  lib/database/adapters/index.js
  lib/database/migrations/20230424121312-add-dpl-process.js
  lib/database/models/dpl/dpldetector.js
  lib/database/models/dpl/dplprocess.js
  lib/database/models/dpl/dplprocessexecution.js
  lib/database/models/dpl/dplprocesstype.js
  lib/database/models/host.js
  lib/database/models/index.js
  lib/database/models/run.js
  lib/database/models/typedefs/SequelizeHost.js
  lib/database/models/typedefs/dpl/SequelizeDplDetector.js
  lib/database/models/typedefs/dpl/SequelizeDplProcess.js
  lib/database/models/typedefs/dpl/SequelizeDplProcessExecution.js
  lib/database/models/typedefs/dpl/SequelizeDplProcessType.js
  lib/database/repositories/EnvironmentHistoryItemRepository.js
  lib/database/repositories/HostRepository.js
  lib/database/repositories/dpl/DplDetectorRepository.js
  lib/database/repositories/dpl/DplProcessExecutionRepository.js
  lib/database/repositories/dpl/DplProcessRepository.js
  lib/database/repositories/dpl/DplProcessTypeRepository.js
  lib/database/repositories/index.js
  lib/database/seeders/20230426120201-dpl-process-types.js
  lib/database/seeders/20230428095027-dpl-detectors.js
  lib/database/seeders/20230428095047-dpl-processes.js
  lib/database/seeders/20230428095054-hosts.js
  lib/database/seeders/20230428095106-dpl-executed-processes.js
  lib/domain/entities/Host.js
  lib/domain/entities/dpl/DplDetector.js
  lib/domain/entities/dpl/DplProcess.js
  lib/domain/entities/dpl/DplProcessExecution.js
  lib/domain/entities/dpl/DplProcessType.js
Labels: backend

#1010 [O2B-902] Log runs and envs impacted by housekeeping
  lib/application.js
  lib/database/repositories/EnvironmentHistoryItemRepository.js
  lib/server/services/environment/transitionToErrorLostEnvironments.js
  lib/server/services/housekeeping/handleLostRunsAndEnvironments.js
  lib/server/services/run/setO2StopOfLostRuns.js
Labels: backend

#989 [O2B-872] Fetch all DPL detectors with at least one executed process
  lib/domain/dtos/DtoFactory.js
  lib/server/controllers/dplProcess.controller.js
  lib/server/routers/dplProcess.router.js
  lib/server/routers/index.js
  lib/server/services/dpl/DplProcessService.js
  test/api/dplProcess.test.js
  test/api/index.js
  test/lib/server/services/dpl/DplProcessService.test.js
  test/lib/server/services/dpl/index.js
  test/lib/server/services/index.js
Labels: backend

#1009 [O2B-899] Add slimos EoS report
  lib/domain/dtos/eosReport/CreateEosReportDto.js
  lib/domain/enums/ShiftTypes.js
  lib/public/domain/enums/ShiftTypes.js
  lib/public/views/EosReport/create/EosReportCreationModel.js
  lib/public/views/EosReport/create/eosReportCreationComponent.js
  lib/server/services/eosReport/eosTypeSpecificFormatter/getEosReportTagsByType.js
  lib/server/services/eosReport/formatEosReport.js
  lib/server/services/shift/ShiftService.js
  lib/server/services/shift/getShiftTagsFiltersByType.js
  test/api/shift.test.js
  test/lib/server/services/eosReport/EosReportService.test.js
  test/lib/server/services/eosReport/formatEosReport.test.js
  test/lib/server/services/shift/ShiftService.test.js
  test/mocks/base-mock-eos-report.js
  test/mocks/mock-ecs-eos-report.js
  test/mocks/mock-qc-pdp-eos-report.js
  test/mocks/mock-slimos-eos-report.js
  test/public/eosReport/slimos-creation.test.js
  test/public/logs/overview.test.js
Labels: frontend, backend

#1016 [O2B-900] Add Shift Leader EoS report
  lib/domain/dtos/eosReport/CreateEosReportDto.js
  lib/domain/enums/ShiftTypes.js
  lib/public/app.css
  lib/public/domain/enums/ShiftTypes.js
  lib/public/views/EosReport/create/EosReportCreationModel.js
  lib/public/views/EosReport/create/eosReportCreationComponent.js
  lib/public/views/EosReport/create/typeSpecific/eosFormQcPdpSpecificPart.js
  lib/public/views/EosReport/create/typeSpecific/eosFormShiftLeaderSpecificPart.js
  lib/server/services/eosReport/EosReportService.js
  lib/server/services/eosReport/eosTypeSpecificFormatter/formatShiftLeaderEosReportTypeSpecific.js
  lib/server/services/eosReport/eosTypeSpecificFormatter/getEosReportTagsByType.js
  lib/server/services/eosReport/formatEosReport.js
  lib/server/services/eosReport/getShiftIssues.js
  lib/server/services/log/getLogsByTagsInPeriod.js
  lib/server/services/log/getShiftIssuesTagsOccurrences.js
  lib/server/services/shift/ShiftService.js
  lib/server/services/shift/formatShiftDate.js
  lib/server/services/shift/getShiftTagsFiltersByType.js
  test/api/shift.test.js
  test/lib/server/services/eosReport/EosReportService.test.js
  test/lib/server/services/eosReport/formatEosReport.test.js
  test/lib/server/services/shift/ShiftService.test.js
  test/mocks/mock-shift-leader-eos-report.js
  test/public/eosReport/shift-leader-creation.test.js
  test/public/logs/overview.test.js
Labels: frontend, backend

#1017 Release 0.57.0
  CHANGELOG.md
  lib/public/views/About/Overview/index.js
  package-lock.json
  package.json
Labels: release

#1028 [O2B-911] Add gRPC endpoint to fetch the last LHC fill
  lib/server/controllers/gRPC/GRPCLhcFIllController.js
  lib/server/gRPC/servicesImplementationsMappings.js
  lib/server/services/lhcFill/LhcFillService.js
  lib/server/services/lhcFill/getLastLhcFill.js
  lib/server/services/lhcFill/getLhcFill.js
  lib/server/services/run/RunService.js
  lib/usecases/lhcFill/GetLhcFillUseCase.js
  proto/lhcFill.proto
  test/lib/server/services/lhcFill/LhcFillService.test.js
  test/lib/server/services/lhcFill/index.js
  test/lib/usecases/lhcFill/GetLhcFillRunByRunNumberUseCase.test.js
Labels: backend

#1033 [O2B-915] Fix time-dependents tests
  test/public/eosReport/shift-leader-creation.test.js
Labels: test

#1031 [O2B-916] Add a button to create EoS report
  lib/public/components/NavBar/index.js
Labels: frontend

#1034 [O2B-919] Add hints on EoS report
  lib/public/app.css
  lib/public/components/common/contextualMessage/contextualInfo.js
  lib/public/views/EosReport/create/eosReportCreationComponent.js
Labels: frontend

#1000 [O2B-562] Colored environment statuses
  lib/public/app.css
  lib/public/components/common/table/rows.js
  lib/public/views/Environments/ActiveColumns/environmentsActiveColumns.js
  lib/public/views/Environments/ColoredEnvironmentStatusComponent.js
  lib/public/views/Environments/Details/EnvironmentDetailsPage.js
  lib/public/views/Environments/Overview/environmentOverviewComponent.js
  test/public/defaults.js
  test/public/envs/overview.test.js
Labels: frontend

#1036 [O2B-919] Make hints icons more discrete
  lib/public/app.css
  lib/public/components/common/contextualMessage/contextualInfo.js
Labels: frontend

#1014 [O2B-886] Add total TF size alongside the total CTF size on lhc fill display
  lib/public/services/lhcFill/LhcFillStatisticsExtractor.js
  lib/public/views/LhcFills/Detail/lhcFillDetailsComponent.js
  test/public/lhcFills/detail.test.js
Labels: frontend
