Repository AliceO2Group/Bookkeeping, pull requests merged in 2023-02, with the labels that each got.

#828 [O2B-747] Lock detector quality for not ended runs
  lib/database/repositories/Repository.js
  lib/database/utilities/TransactionHelper.js
  lib/domain/dtos/UpdateRunDetectorDto.js
  lib/domain/dtos/index.js
  lib/public/components/RunDetail/index.js
  lib/server/controllers/detectors.controller.js
  lib/server/routers/index.js
  lib/server/routers/runDetectors.router.js
  lib/server/services/run/RunService.js
  lib/server/services/run/updateRun.js
  lib/server/services/runDetector/RunDetectorService.js
  lib/usecases/index.js
  lib/usecases/run/UpdateRunUseCase.js
  lib/usecases/runDetector/UpdateRunDetectorUseCase.js
  lib/usecases/runDetector/index.js
  test/api/index.js
  test/api/runDetectors.test.js
  test/api/runs.test.js
  test/lib/usecases/index.js
  test/lib/usecases/run/UpdateRunUseCase.test.js
  test/lib/usecases/runDetectors/UpdateRunDetectorUseCase.test.js
  test/lib/usecases/runDetectors/index.js
  test/public/runs/detail.test.js
Labels: frontend, backend

#833 [O2B-797] Merge tables flp_runs inside flp_roles
  lib/database/adapters/FlpRoleAdapter.js
  lib/database/adapters/FlpRunsAdapter.js
  lib/database/adapters/RunAdapter.js
  lib/database/adapters/index.js
  lib/database/migrations/20221010120629-convert-run-detectors-to-separate-table.js
  lib/database/migrations/20221214064931-merge-flp-runs-in-flp-roles.js
  lib/database/models/flprole.js
  lib/database/models/index.js
  lib/database/models/run.js
  lib/database/models/typedefs/SequelizeFlpRole.js
  lib/database/models/typedefs/SequelizeRun.js
  lib/database/repositories/FlpRepository.js
  lib/database/repositories/FlpRoleRepository.js
  lib/database/repositories/FlpRunsRepository.js
  lib/database/repositories/index.js
  lib/database/seeders/20200921181553-flps.js
  lib/database/seeders/20201021083549-flp-runs.js
  lib/database/tables/index.js
  lib/domain/entities/FlpRole.js
  lib/domain/entities/Run.js
  lib/public/components/FlpRun/index.js
  lib/server/controllers/gRPC/GRPCFlpRoleController.js
  lib/server/controllers/runs.controller.js
  lib/server/gRPC/servicesImplementationsMappings.js
  lib/server/services/flp/FlpRoleService.js
  lib/server/services/flp/FlpService.js
  lib/server/services/flp/createFlp.js
  lib/server/services/flp/createFlpRole.js
  lib/server/services/flp/getFlpRole.js
  lib/server/services/run/RunService.js
  lib/server/services/runType/getOrCreateRunType.js
  lib/usecases/flp/CreateFlpUseCase.js
  lib/usecases/flp/GetAllFlpsUseCase.js
  lib/usecases/flp/GetFlpUseCase.js
  lib/usecases/flp/GetLogsByFlpUseCase.js
  lib/usecases/flp/UpdateFlpUseCase.js
  lib/usecases/run/GetFlpsByRunUseCase.js
  test/api/flps.test.js
  test/lib/usecases/flp/CreateFlpUseCase.test.js
  test/public/flps/detail.test.js
Labels: backend, db

#856 [O2B-806] Updates run defintion for COSMICS to include missing value for beam_mode
  docs/RUN_DEFINITIONS.md
  lib/server/services/run/getRunDefinition.js
  test/lib/server/services/run/getRunDefinition.test.js
  test/lib/server/services/run/index.js
  test/mocks/mock-run.js
Labels: backend

#860 [O2B-808] Add two run types
  proto/common.proto
Labels: backend

#851 [O2B-661] Add ongoing information to LHC fill detail page
  database/CHANGELOG.md
  lib/public/views/LhcFills/ActiveColumns/lhcFillsActiveColumns.js
  lib/public/views/LhcFills/Detail/lhcFillDetailsComponent.js
  test/public/lhcFills/detail.test.js
  test/public/lhcFills/overview.test.js
Labels: frontend

#863 Release/0.49.0
  CHANGELOG.md
  database/CHANGELOG.md
  lib/public/views/About/Overview/index.js
  package-lock.json
  package.json
Labels: release

#866 [O2B-677] Fix cxx client readme
  cxx-client/README.md
Labels: documentation

#867 [O2B-812] Bump docker nodejs base image
  Dockerfile
Labels: docker

#869 [O2B-815] Separate tests from coverage
  .github/workflows/bookkeeping.yml
  Dockerfile
  docker-compose.coverage.yml
Labels: docker, CI

#873 [O2B-811] Improve database connection retry
  lib/database/index.js
Labels: backend, db

#874 [O2B-818] Add 'none' run quality
  lib/database/migrations/20230213082905-run-quality-unknown-to-null.js
  lib/database/models/run.js
  lib/database/models/rundetectors.js
  lib/database/models/typedefs/SequelizeRun.js
  lib/database/seeders/20200713103855-runs.js
  lib/domain/dtos/GetAllRunsDto.js
  lib/domain/dtos/UpdateRunByRunNumberDto.js
  lib/domain/dtos/UpdateRunDto.js
  lib/domain/entities/Run.js
  lib/domain/enums/RunDetectorQualities.js
  lib/domain/enums/RunQualities.js
  lib/public/components/Filters/RunsFilter/runQuality.js
  lib/public/components/RunDetail/index.js
  lib/public/domain/enums/RunDetectorQualities.js
  lib/public/domain/enums/RunQualities.js
  lib/public/services/lhcFill/LhcFillStatisticsExtractor.js
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
  lib/server/services/run/createRun.js
  lib/server/services/run/updateRun.js
  lib/server/services/tag/getTagsByText.js
  proto/common.proto
  test/api/runs.test.js
  test/gRPC/serviceImplementation.js
  test/lib/server/services/run/RunService.test.js
  test/lib/usecases/run/EndRunUseCase.test.js
  test/lib/usecases/run/GetAllRunsUseCase.test.js
  test/lib/usecases/run/GetRunUseCase.test.js
  test/lib/usecases/run/StartRunUseCase.test.js
  test/lib/usecases/run/UpdateRunUseCase.test.js
  test/public/home/overview.test.js
  test/public/lhcFills/detail.test.js
  test/public/logs/create.test.js
  test/public/logs/overview.test.js
  test/public/runs/overview.test.js
Labels: frontend, backend, db

#877 [O2B-819] Improve tags' emails display in display page
  lib/public/components/tag/tagDetail.js
  lib/public/utilities/formatting/formatEmail.js
  test/public/tags/detail.test.js
Labels: frontend

#879 [O2B-813] Fix migration of existing data
  Dockerfile
  lib/database/migrations/20230120160345-add-environment-history.js
Labels: bug, db

#878 [O2B-766] Add log-id and parent-log-id to kafka message
  lib/server/services/log/createLog.js
  package-lock.json
  package.json
Labels: backend

#884 [O2B-764] Expand logs targetted in URL
  lib/database/seeders/20200508094502-logs.js
  lib/public/Model.js
  lib/public/components/Log/logCollapsed.js
  lib/public/components/Log/logExpanded.js
  lib/public/components/Log/replyButton.js
  lib/public/components/PostCollapsed/index.js
  lib/public/view.js
  lib/public/views/Logs/Details/LogTreeViewModel.js
  lib/public/views/Logs/Details/LogTreeViewPage.js
  lib/public/views/Logs/Details/index.js
  lib/public/views/Logs/Details/logTreeViewComponent.js
  lib/public/views/Logs/Logs.js
  lib/server/controllers/logs.controller.js
  lib/usecases/log/GetLogTreeUseCase.js
  test/lib/database/utilities/QueryBuilder.test.js
  test/public/logs/create.test.js
  test/public/logs/detail.test.js
Labels: frontend

#885 [O2B-771] Improve run's duration missing data message
  lib/public/components/RunDetail/index.js
  lib/public/components/common/table/rows.js
  lib/public/components/common/table/table.js
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
  lib/public/views/Runs/format/formatRunDuration.js
  lib/public/views/Runs/format/formatRunEnd.js
  lib/public/views/Runs/format/formatRunStart.js
  lib/public/views/Runs/formatRunDuration.js
  test/public/runs/detail.test.js
  test/public/runs/overview.test.js
Labels: frontend

#887 [O2B-823] Make runs list as hyperlink
  lib/public/components/common/navigation/frontLinks.js
  lib/public/views/Environments/ActiveColumns/environmentsActiveColumns.js
  lib/public/views/LhcFills/ActiveColumns/lhcFillsActiveColumns.js
  lib/public/views/Logs/ActiveColumns/logsActiveColumns.js
  lib/public/views/Runs/format/formatRunsList.js
  test/public/envs/overview.test.js
  test/public/lhcFills/overview.test.js
  test/public/logs/overview.test.js
Labels: frontend

#890 [O2B-771] Fix run duration popover
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
Labels: bug, frontend

#881 [O2B-826] Fix auto-created logs date display
  lib/server/services/run/RunService.js
  lib/server/services/run/updateRun.js
  lib/server/utilities/formatServerDate.js
Labels: bug, backend

#891 Release 0.51.0
  CHANGELOG.md
  lib/public/views/About/Overview/index.js
  package-lock.json
  package.json
Labels: release
