Repository AliceO2Group/Bookkeeping, pull requests merged in 2023-11, with the labels that each got.

#1213 [O2B-1035] Refactor chart scales computing & uniformize renderers
  lib/public/components/common/chart/barChart/barChartComponent.js
  lib/public/components/common/chart/histogram/histogramComponent.js
  lib/public/components/common/chart/lineChart/lineChartComponent.js
  lib/public/components/common/chart/rendering/BarChartRenderer.js
  lib/public/components/common/chart/rendering/ChartRenderer.js
  lib/public/components/common/chart/rendering/HistogramChartRenderer.js
  lib/public/components/common/chart/rendering/LineChartRenderer.js
  lib/public/components/common/chart/rendering/axis/AxisRenderer.js
  lib/public/components/common/chart/rendering/dataset/renderDatasetAsBars.js
  lib/public/components/common/chart/rendering/dataset/renderDatasetAsLine.js
  lib/public/components/common/chart/structures/Range.js
  lib/public/views/Statistics/charts/timeBetweenRunsHistogramComponent.js
Labels: frontend

#1225 [O2B-1035] Add tag occurrences in logs chart
  lib/database/repositories/LogRepository.js
  lib/public/components/common/chart/rendering/axis/AxisRenderer.js
  lib/public/views/Statistics/StatisticsPage.js
  lib/public/views/Statistics/StatisticsPageModel.js
  lib/public/views/Statistics/charts/tagOccurrencesBarChartComponent.js
  lib/server/controllers/statistics.controller.js
  lib/server/routers/statistics.router.js
  lib/server/services/statistics/StatisticsService.js
  test/lib/server/services/statistics/StatisticsService.test.js
  test/lib/server/services/statistics/index.js
Labels: frontend, backend

#1210 [O2B-1025] - lhc periods table extraction (#1193)
  lib/database/adapters/LhcPeriodAdapter.js
  lib/database/adapters/RunAdapter.js
  lib/database/adapters/index.js
  lib/database/migrations/20231011103554-create-lhc-period.js
  lib/database/models/index.js
  lib/database/models/lhcPeriod.js
  lib/database/models/run.js
  lib/database/models/typedefs/SequelizeLhcPeriod.js
  lib/database/repositories/LhcPeriodRepository.js
  lib/database/repositories/index.js
  lib/database/seeders/20200713103800-lhc-period.js
  lib/database/seeders/20200713103855-runs.js
  lib/domain/entities/LhcPeriod.js
  lib/public/components/Filters/RunsFilter/lhcPeriod.js
  lib/server/controllers/environments.controller.js
  lib/server/controllers/gRPC/GRPCRunController.js
  lib/server/controllers/runs.controller.js
  lib/server/services/period/getOrCreateLhcPeriod.js
  lib/server/services/run/RunService.js
  lib/usecases/run/EndRunUseCase.js
  lib/usecases/run/GetAllRunsUseCase.js
  lib/usecases/run/GetRunUseCase.js
  test/api/runs.test.js
  test/lib/usecases/run/EndRunUseCase.test.js
  test/lib/usecases/run/GetAllRunsUseCase.test.js
  test/lib/usecases/run/GetRunUseCase.test.js
Labels: backend, DB

#1222 [O2B-455] add flp home button
  lib/config/services.js
  lib/public/components/NavBar/index.js
  lib/server/controllers/configuration.controller.js
Labels: frontend, backend

#1223 [O2B-845] display original log when replying
  lib/public/components/Log/log.js
  lib/public/components/Log/logDetailsButton.js
  lib/public/components/Log/logText.js
  lib/public/views/Logs/Create/LogCreationModel.js
  lib/public/views/Logs/Create/LogCreationPage.js
  lib/public/views/Logs/Create/logCreationComponent.js
  lib/public/views/Logs/Logs.js
  test/public/logs/create.test.js
Labels: frontend

#1231 Release 0.71.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#1216 [O2B-1026] periods service
  lib/database/adapters/LhcPeriodStatisticsAdapter.js
  lib/database/adapters/index.js
  lib/database/migrations/20231025101611-create-lhc-periods-view.js
  lib/database/models/index.js
  lib/database/models/lhcPeriodsStatistics.js
  lib/database/models/typedefs/SequelizeLhcPeriodStatistics.js
  lib/database/repositories/LhcPeriodStatisticsRepository.js
  lib/database/repositories/index.js
  lib/database/seeders/20200713103855-runs.js
  lib/database/utilities/QueryBuilder.js
  lib/domain/entities/LhcPeriodStatistics.js
  lib/server/services/lhcPeriod/LhcPeriodStatisticsService.js
  lib/server/services/lhcPeriod/getOrCreateLhcPeriod.js
  lib/server/services/run/RunService.js
  test/lib/server/services/index.js
  test/lib/server/services/lhcPeriod/LhcPeriodStatisticsService.test.js
  test/lib/server/services/lhcPeriod/getOrCreateLhcPeriod.test.js
  test/lib/server/services/lhcPeriod/index.js
Labels: backend

#1230 scalars to lowercase
  lib/database/index.js
  lib/database/repositories/EorReasonRepository.js
  lib/database/utilities/QueryBuilder.js
  lib/public/Model.js
  lib/public/components/Detail/detailsGrid.js
  lib/public/components/Detail/detailsList.js
  lib/public/components/Filters/RunsFilter/dcs.js
  lib/public/components/Filters/RunsFilter/ddflp.js
  lib/public/components/Filters/RunsFilter/epn.js
  lib/public/components/Filters/common/filters/checkboxFilter.js
  lib/public/components/Log/logText.js
  lib/public/components/NavBar/index.js
  lib/public/components/Pagination/pageSelector.js
  lib/public/components/common/table/rows.js
  lib/public/utilities/export.js
  lib/public/utilities/scrollTo.js
  lib/public/utilities/targetURL.js
  lib/public/views/Environments/ColoredEnvironmentStatusComponent.js
  lib/public/views/Flps/Flps.js
  lib/public/views/Logs/ActiveColumns/logsActiveColumns.js
  lib/public/views/Logs/Logs.js
  lib/public/views/Runs/Runs.js
  lib/public/views/Tags/Create/TagCreationModel.js
  lib/server/routers/index.js
  lib/server/services/eosReport/formatEosReport.js
  lib/server/services/log/getLogsByTitle.js
  lib/server/services/shift/ShiftService.js
  lib/utilities/env-utils.js
  lib/utilities/isPromise.js
  test/public/defaults.js
Labels: documentation

#1224 [O2B-1028] add periods controllers
  lib/database/models/typedefs/SequelizeLhcPeriodStatistics.js
  lib/domain/dtos/DtoFactory.js
  lib/domain/entities/LhcPeriodStatistics.js
  lib/server/controllers/lhcPeriodStatistics.controller.js
  lib/server/routers/index.js
  lib/server/routers/lhcPeriodsStatistics.router.js
  lib/server/services/lhcPeriod/LhcPeriodStatisticsService.js
  lib/server/utilities/countedItemsToHttpView.js
  lib/server/utilities/dtoValidator.js
  lib/server/utilities/index.js
  test/api/index.js
  test/api/lhcPeriodsStatistics.test.js
  test/lib/server/services/lhcPeriod/LhcPeriodStatisticsService.test.js
Labels: backend

#1233 [O2B-1040] add RCT periods page
  lib/public/Model.js
  lib/public/view.js
  lib/public/views/lhcPeriods/ActiveColumns/lhcPeriodsActiveColumns.js
  lib/public/views/lhcPeriods/LhcPeriodsModel.js
  lib/public/views/lhcPeriods/Overview/LhcPeriodsOverviewModel.js
  lib/public/views/lhcPeriods/Overview/LhcPeriodsOverviewPage.js
  test/public/index.js
  test/public/lhcPeriods/index.js
  test/public/lhcPeriods/overview.test.js
Labels: frontend

#1237 Handle 0 in formatTimestamp function
  lib/public/utilities/formatting/formatTimestamp.js
Labels: bug, frontend

#1238 [O2B-1047] Fixed line chart fill
  lib/public/components/common/chart/rendering/dataset/renderDatasetAsLine.js
Labels: bug, frontend

#1236 [O2B-1043] Add time filter
  lib/public/app.css
  lib/public/components/Filters/common/FilterModel.js
  lib/public/components/Filters/common/filters/TimeRangeFilterModel.js
  lib/public/components/Filters/common/filters/timeRangeFilter.js
  lib/public/components/common/form/inputs/DateTimeInputModel.js
  lib/public/components/common/form/inputs/dateTimeInput.js
  lib/public/utilities/dateUtils.js
  lib/public/utilities/formatting/HTMLInputDateFormat.js
  lib/public/views/EosReport/create/typeSpecific/commentInput.js
  lib/public/views/EosReport/create/typeSpecific/eosFormEcsSpecificPart.js
  lib/public/views/Runs/format/editRunEorReasons.js
  lib/public/views/Statistics/StatisticsPage.js
  lib/public/views/Statistics/StatisticsPageModel.js
Labels: frontend

#1243 [O2B-1050] Fix ordering of LHC fill's related runs (sort them by runNumber)
  lib/database/seeders/20220513153907-eor-reason.js
  lib/server/services/lhcFill/LhcFillService.js
Labels: backend

#1240 [O2B-1045] nav bar adjustment
  lib/public/Model.js
  lib/public/components/NavBar/index.js
  test/public/tags/create.test.js
Labels: frontend

#1219 [O2B-829] run number instead of run id in run details
  lib/domain/dtos/EndRunDto.js
  lib/domain/dtos/GetRunDto.js
  lib/domain/dtos/UpdateRunDto.js
  lib/public/Model.js
  lib/public/components/FlpRun/index.js
  lib/public/components/Log/log.js
  lib/public/views/EosReport/create/typeSpecific/eosFormEcsSpecificPart.js
  lib/public/views/EosReport/create/typeSpecific/eosFormQcPdpSpecificPart.js
  lib/public/views/EosReport/create/typeSpecific/eosFormShiftLeaderSpecificPart.js
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
  lib/public/views/Runs/Details/RunDetailsModel.js
  lib/public/views/Runs/Details/RunDetailsPage.js
  lib/public/views/Runs/Details/runDetailsComponent.js
  lib/public/views/Runs/Runs.js
  lib/public/views/Runs/format/displayRunNumber.js
  lib/public/views/Runs/format/formatRunsList.js
  lib/server/controllers/runs.controller.js
  lib/server/routers/runs.router.js
  lib/server/services/eosReport/eosTypeSpecificFormatter/formatEcsEosReportTypeSpecific.js
  lib/server/services/eosReport/eosTypeSpecificFormatter/formatQcPdpEosReportTypeSpecific.js
  lib/server/services/eosReport/eosTypeSpecificFormatter/formatShiftLeaderEosReportTypeSpecific.js
  lib/usecases/run/EndRunUseCase.js
  lib/usecases/run/GetFlpsByRunUseCase.js
  lib/usecases/run/GetLogsByRunUseCase.js
  lib/usecases/run/GetRunUseCase.js
  lib/usecases/run/UpdateRunUseCase.js
  test/api/index.js
  test/api/runs-with-runId.test.js
  test/api/runs.test.js
  test/lib/usecases/run/EndRunUseCase.test.js
  test/lib/usecases/run/UpdateRunUseCase.test.js
  test/mocks/mock-ecs-eos-report.js
  test/mocks/mock-qc-pdp-eos-report.js
  test/mocks/mock-shift-leader-eos-report.js
  test/public/eosReport/ecs-creation.test.js
  test/public/eosReport/qc-pdp-creation.test.js
  test/public/eosReport/shift-leader-creation.test.js
  test/public/flps/detail.test.js
  test/public/lhcFills/detail.test.js
  test/public/logs/detail.test.js
  test/public/logs/overview.test.js
  test/public/runs/detail.test.js
  test/public/runs/overview.test.js
Labels: frontend, backend, javascript

#1246 [O2B-1050] Group EoR reasons by category,title in EoR reasons chart
  lib/database/repositories/StableBeamRunsRepository.js
  lib/database/seeders/20220513153907-eor-reason.js
  test/lib/usecases/run/UpdateRunUseCase.test.js
  test/public/runs/overview.test.js
Labels: backend

#1242 [O2B-1043] Add pre-filled options for time range filter
  lib/public/app.css
  lib/public/components/Filters/common/filters/TimeRangeFilterModel.js
  lib/public/components/Filters/common/filters/timeRangeFilter.js
  lib/public/components/common/formatting/formatTimeRange.js
  lib/public/utilities/dateUtils.js
  lib/public/views/LhcFills/Overview/index.js
  lib/public/views/Statistics/StatisticsPage.js
  lib/public/views/Statistics/StatisticsPageModel.js
Labels: frontend

#1247 Release 0.72.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#1253 [O2B-1024] get only good runs
  lib/database/migrations/20231025101611-create-lhc-periods-view.js
  lib/server/services/lhcPeriod/LhcPeriodStatisticsService.js
Labels: backend, DB

#1248 [O2B-1049] add beam type column
  lib/database/adapters/LhcPeriodStatisticsAdapter.js
  lib/database/utilities/QueryBuilder.js
  lib/public/views/lhcPeriods/ActiveColumns/lhcPeriodsActiveColumns.js
  lib/server/controllers/lhcPeriodStatistics.controller.js
  lib/server/services/lhcPeriod/LhcPeriodStatisticsService.js
  test/api/lhcPeriodsStatistics.test.js
  test/lib/server/services/lhcPeriod/LhcPeriodStatisticsService.test.js
  test/public/lhcPeriods/overview.test.js
Labels: frontend, backend

#1257 [fix] Update Dockerfile
  Dockerfile
Labels: docker, CI

#1256 [O2B-1060] add lhcfill filter option for stable beams
  lib/domain/dtos/GetAllLhcFillsDto.js
  lib/domain/dtos/filters/LhcFillsFilterDto.js
  lib/usecases/lhcFill/GetAllLhcFillsUseCase.js
  test/lib/usecases/lhcFill/GetAllLhcFillsUseCase.test.js
Labels: backend
