Repository AliceO2Group/Bookkeeping, pull requests merged in 2023-10, with the labels that each got.

#1182 [O2B-913] Display EoR in env and LHC fill details
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
  lib/server/services/environment/EnvironmentService.js
  lib/server/services/lhcFill/LhcFillService.js
Labels: frontend

#1183 [O2B-1018] Add time between runs histogram
  lib/database/migrations/20230928091453-add-run-duration-column.js
  lib/database/repositories/StableBeamRunsRepository.js
  lib/domain/entities/statistics/Histogram.js
  lib/public/components/common/chart/histogram/histogramComponent.js
  lib/public/components/common/chart/lineChart/lineChartComponent.js
  lib/public/components/common/chart/lineChart/renderLineChart.js
  lib/public/components/common/chart/rendering/ChartRenderer.js
  lib/public/components/common/chart/rendering/HistogramChartRenderer.js
  lib/public/components/common/chart/rendering/PointBasedChartRenderer.js
  lib/public/components/common/chart/rendering/axis/AxisRenderer.js
  lib/public/components/common/chart/rendering/dataset/renderDatasetAsHistogram.js
  lib/public/views/Statistics/StatisticsPage.js
  lib/public/views/Statistics/StatisticsPageModel.js
  lib/public/views/Statistics/charts/timeBetweenRunsHistogramComponent.js
  lib/public/views/Statistics/charts/weeklyDataSizeChartComponent.js
  lib/server/controllers/statistics.controller.js
  lib/server/routers/statistics.router.js
  lib/server/services/statistics/StatisticsService.js
  test/lib/server/services/statistics/StatisticsService.test.js
Labels: frontend, backend

#1184 Release 0.68.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#1185 [O2B-1018] Fixed "over 30min" time between runs bin
  lib/database/repositories/StableBeamRunsRepository.js
  test/lib/server/services/statistics/StatisticsService.test.js
Labels: backend

#1187 [O2B-1023] Fix infinite amount selector tests
  test/public/flps/overview.test.js
  test/public/logs/overview.test.js
  test/public/runs/overview.test.js
Labels: backend

#1190 Delete useless controllers and routers
  lib/server/controllers/auth.controller.js
  lib/server/controllers/createpdf.controller.js
  lib/server/controllers/index.js
  lib/server/controllers/overviews.controller.js
  lib/server/controllers/settings.controller.js
  lib/server/controllers/users.controller.js
  lib/server/routers/auth.router.js
  lib/server/routers/createpdf.router.js
  lib/server/routers/index.js
  lib/server/routers/overviews.router.js
  lib/server/routers/settings.router.js
  lib/server/routers/users.router.js
Labels: backend

#1191 [O2B-1031] Fix tag popover
  lib/public/components/common/selection/dropdown/selectionDropdown.js
Labels: frontend

#1194 use newer docker command syntax
  package.json
Labels: docker

#1192 [O2B-913] Make popover system generic
  lib/public/app.css
  lib/public/components/Filters/common/filtersPanel.js
  lib/public/components/Filters/common/filtersToggleButton.js
  lib/public/components/Pagination/amountSelector.js
  lib/public/components/common/popover/PopoverEngine.js
  lib/public/components/common/popover/dropdown.js
  lib/public/components/common/popover/overflowBalloon.js
  lib/public/components/common/popover/popover.js
  lib/public/components/common/popover/tooltip.js
  lib/public/components/common/selection/dropdown/SelectionDropdownModel.js
  lib/public/components/common/selection/dropdown/selectionDropdown.js
  lib/public/components/common/toggle/toggleContainer.js
  lib/public/components/modal/modalContainer.js
  lib/public/utilities/createPortal.js
  lib/public/utilities/documentClickTaggedEventRegistry.js
  lib/public/view.js
  lib/public/views/Logs/Logs.js
  lib/public/views/Runs/Runs.js
  lib/public/views/Runs/format/formatRunDetectors.js
  test/public/defaults.js
  test/public/logs/overview.test.js
  test/public/runs/detail.test.js
  test/public/runs/overview.test.js
Labels: frontend

#1196 [O2B-913] Add infologger links
  lib/application.js
  lib/config/index.js
  lib/config/services.js
  lib/presentation/Component.js
  lib/public/app.css
  lib/public/index.html
  lib/public/services/externalRouting/getInfologgerLink.js
  lib/public/views/Environments/ActiveColumns/environmentsActiveColumns.js
  lib/public/views/Environments/Details/EnvironmentDetailsPage.js
  lib/public/views/Environments/format/displayEnvironmentInfologgerLinks.js
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
  lib/public/views/Runs/Details/runDetailsComponent.js
  lib/public/views/Runs/format/displayRunNumber.js
  lib/server/controllers/configuration.controller.js
  lib/server/controllers/index.js
  lib/server/routers/configuration.router.js
  lib/server/routers/index.js
  lib/server/services/housekeeping/handleLostRunsAndEnvironments.js
  test/api/configuration.test.js
  test/api/index.js
Labels: frontend, backend

#1197 Release 0.69.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#1198 [O2B-1034] Fix infologger run link
  lib/public/services/externalRouting/getInfologgerLink.js
Labels: frontend

#1199 [O2B-1012] - Filter by run number in overview
  lib/public/components/Filters/RunsFilter/runNumber.js
  lib/public/views/Runs/Overview/index.js
  test/public/runs/overview.test.js
Labels: frontend

#1200 [O2B-1033] Add endpoint to fetch detector efficiency
  lib/database/repositories/StableBeamRunsRepository.js
  lib/database/seeders/20221006084006-run-detectors.js
  lib/server/controllers/gRPC/GRPCDplProcessExecutionController.js
  lib/server/controllers/statistics.controller.js
  lib/server/routers/statistics.router.js
  lib/server/services/statistics/StatisticsService.js
  test/lib/server/services/statistics/StatisticsService.test.js
Labels: backend

#1201 [O2B-1033] Improve percentage format
  lib/public/services/lhcFill/LhcFillStatisticsExtractor.js
  lib/public/utilities/formatting/formatPercentage.js
  lib/public/views/Statistics/charts/efficiencyChartComponent.js
Labels: frontend

#1202 [O2B-1033] Add possibility to override min/max in graphs
  lib/public/components/common/chart/rendering/ChartRenderer.js
  lib/public/components/common/chart/rendering/HistogramChartRenderer.js
  lib/public/components/common/chart/rendering/PointBasedChartRenderer.js
  lib/public/components/common/chart/rendering/axis/AxisRenderer.js
  lib/public/components/common/chart/rendering/dataset/renderDatasetAsLine.js
  lib/public/components/common/chart/rendering/dataset/renderDatasetAsPointCloud.js
  lib/public/views/Statistics/charts/efficiencyChartComponent.js
Labels: frontend

#1203 [O2B-1033] Add several improvements to the chart rendering system
  lib/public/components/common/chart/lineChart/lineChartComponent.js
  lib/public/components/common/chart/rendering/PointBasedChartRenderer.js
Labels: frontend

#1205 [O2B-1036] remove /runs/tags/ endpoint
  lib/server/controllers/runs.controller.js
  lib/server/routers/runs.router.js
Labels: backend

#1193 [O2B-1025] - lhc periods table extraction
  lib/database/adapters/LhcPeriodAdapter.js
  lib/database/adapters/RunAdapter.js
  lib/database/adapters/index.js
  lib/database/migrations/20231011103554-create-lhc-period.js
  lib/database/models/index.js
  lib/database/models/lhcPeriod.js
  lib/database/models/run.js
  lib/database/models/typedefs/SequelizeLhcPeriod.js
  lib/database/repositories/LhcPeriodRepository.js
  lib/database/repositories/index.js
  lib/database/seeders/20200713103800-lhc-period.js
  lib/database/seeders/20200713103855-runs.js
  lib/domain/entities/LhcPeriod.js
  lib/public/components/Filters/RunsFilter/lhcPeriod.js
  lib/server/controllers/environments.controller.js
  lib/server/controllers/gRPC/GRPCRunController.js
  lib/server/controllers/runs.controller.js
  lib/server/services/period/getOrCreateLhcPeriod.js
  lib/server/services/run/RunService.js
  lib/usecases/run/EndRunUseCase.js
  lib/usecases/run/GetAllRunsUseCase.js
  lib/usecases/run/GetRunUseCase.js
  test/api/runs.test.js
  test/lib/usecases/run/EndRunUseCase.test.js
  test/lib/usecases/run/GetAllRunsUseCase.test.js
  test/lib/usecases/run/GetRunUseCase.test.js
Labels: backend, DB

#1209 [O2B-1037] Allow filtering on calibration status in runs API
  lib/domain/dtos/filters/RunFilterDto.js
  lib/usecases/run/GetAllRunsUseCase.js
  test/api/runs.test.js
  test/lib/usecases/run/GetAllRunsUseCase.test.js
Labels: backend

#1212 [O2B-1037] Pluralize calibration statuses filter
  lib/domain/dtos/filters/RunFilterDto.js
  lib/usecases/run/GetAllRunsUseCase.js
  test/api/runs.test.js
  test/lib/usecases/run/GetAllRunsUseCase.test.js
Labels: backend

#1204 [O2B-1033] Add detector efficiency graphs
  lib/public/app.css
  lib/public/components/common/form/switchInput.js
  lib/public/utilities/fetch/RemoteDataFetcher.js
  lib/public/utilities/fetch/buildUrl.js
  lib/public/views/Statistics/StatisticsPage.js
  lib/public/views/Statistics/StatisticsPageModel.js
  lib/public/views/Statistics/chartColors.js
  lib/public/views/Statistics/charts/detectorsEfficienciesComponent.js
Labels: frontend

#1214 Release 0.70.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#1217 [O2B-851] allow only admin to create and delete tags
  lib/server/WebUiServer.js
  lib/server/controllers/tags.controller.js
  lib/server/routers/tags.router.js
  test/api/tags.test.js
Labels: backend, javascript
