Repository AliceO2Group/Bookkeeping, pull requests merged in 2023-04, with the labels that each got.

#913 [O2B-840] Add function to fetch environments in a given period
  lib/server/services/environment/EnvironmentService.js
  lib/server/services/environment/environmentIncludeClauseFromRelations.js
  lib/server/services/environment/getEnvironmentsInPeriod.js
  test/lib/server/services/environment/getEnvironmentsInPeriod.test.js
  test/lib/server/services/environment/index.js
Labels: backend

#927 [O2B-840] Fix shift start extraction in EOS report controller
  lib/server/controllers/eosReport.controller.js
Labels: bug, backend

#930 [O2B-831] Update docker dependencies
  Dockerfile
Labels: dependencies, docker

#926 [O2B-840] Fix Logs fetching in a given period
  lib/server/services/log/getLogsByTagsInPeriod.js
  lib/server/services/log/getLogsByUserInPeriod.js
  test/api/shift.test.js
  test/lib/server/services/log/getLogsByTagsInPeriod.test.js
  test/lib/server/services/log/getLogsByUserInPeriod.test.js
  test/public/runs/overview.test.js
Labels: bug, backend

#932 [O2B-840] Update tags seeders with data required for EOS report
  lib/database/seeders/20200511151010-tags.js
  test/api/logs.test.js
  test/api/tags.test.js
  test/lib/server/services/eosReport/EosReportService.test.js
  test/lib/usecases/run/UpdateRunUseCase.test.js
  test/lib/usecases/tag/GetAllTagsUseCase.test.js
  test/lib/usecases/tag/GetTagByNameUseCase.test.js
  test/mocks/mock-eos-report.js
  test/presentation/log/toTreeView.test.js
  test/public/tags/overview.test.js
Labels: backend

#923 [O2B-840] Add ECS-specific data to EOS report
  lib/database/models/run.js
  lib/database/models/typedefs/SequelizeRun.js
  lib/server/services/environment/EnvironmentService.js
  lib/server/services/environment/environmentIncludeClauseFromRelations.js
  lib/server/services/environment/getEnvironmentsInPeriod.js
  lib/server/services/eosReport/EosReportService.js
  lib/server/services/eosReport/eosTypeSpecificFormatter/formatEcsEosReportTypeSpecific.js
  lib/server/services/eosReport/formatEosReport.js
  lib/server/services/log/getLogsByTagsInPeriod.js
  lib/server/services/run/RunService.js
  lib/server/services/run/runIncludeClauseFromRelations.js
  test/api/eosReport.test.js
  test/lib/server/services/environment/getEnvironmentsInPeriod.test.js
  test/lib/server/services/eosReport/EosReportService.test.js
  test/lib/server/services/eosReport/formatEosReport.test.js
  test/mocks/mock-eos-report.js
Labels: backend

#934 [O2B-850] Fix failing shift info test
  lib/server/services/shift/getShiftFromTimestamp.js
  test/api/shift.test.js
Labels: backend, test

#933 [O2B-840] Make links real links
  docker-compose.dev.yml
  lib/config/gRPCConfig.js
  lib/config/httpConfig.js
  lib/server/services/eosReport/EosReportService.js
  lib/server/services/eosReport/eosTypeSpecificFormatter/formatEcsEosReportTypeSpecific.js
  lib/server/services/eosReport/formatEosReport.js
  lib/utilities/frontUrl.js
  test/mocks/mock-eos-report.js
Labels: backend

#931 [O2B-849] Add tag description
  lib/database/adapters/TagAdapter.js
  lib/database/migrations/20230411123947-add-tag-description.js
  lib/database/models/tag.js
  lib/database/models/typedefs/SequelizeTag.js
  lib/database/seeders/20200511151010-tags.js
  lib/domain/dtos/CreateTagDto.js
  lib/domain/dtos/UpdateTagDto.js
  lib/domain/entities/Tag.js
  lib/public/app.css
  lib/public/components/Detail/detailsList.js
  lib/public/components/Filters/common/combinationOperatorChoiceComponent.js
  lib/public/components/common/form/createButton.js
  lib/public/components/common/form/creationFormComponent.js
  lib/public/components/tag/tagDetail.js
  lib/public/domain/enums/BkpRoles.js
  lib/public/models/CreationModel.js
  lib/public/models/OverviewModel.js
  lib/public/utilities/fetch/jsonPost.js
  lib/public/views/EosReport/create/EosReportCreationModel.js
  lib/public/views/EosReport/create/eosReportCreationComponent.js
  lib/public/views/Runs/Details/RunDetailsPage.js
  lib/public/views/Runs/Details/lhcFillPanel.js
  lib/public/views/Tags/Create/TagCreationModel.js
  lib/public/views/Tags/Create/index.js
  lib/public/views/Tags/Details/TagDetailsModel.js
  lib/public/views/Tags/Details/TagDetailsPage.js
  lib/public/views/Tags/Tags.js
  lib/server/controllers/tags.controller.js
  lib/usecases/tag/UpdateTagUseCase.js
  proto/log.proto
  test/api/logs.test.js
  test/api/tags.test.js
  test/lib/usecases/tag/CreateTagUseCase.test.js
  test/lib/usecases/tag/GetTagByNameUseCase.test.js
  test/lib/usecases/tag/UpdateTagUseCase.test.js
  test/public/tags/create.test.js
Labels: frontend, backend

#935 [O2B-841] Display shift issues in EOS report form
  lib/public/Model.js
  lib/public/models/CreationModel.js
  lib/public/views/EosReport/EosReportModel.js
  lib/public/views/EosReport/create/EosReportCreationModel.js
  lib/public/views/EosReport/create/eosReportCreationComponent.js
Labels: frontend

#938 [O2B-840] Add LHC machine transitions
  lib/domain/dtos/eorReport/CreateEosReportDto.js
  lib/public/views/EosReport/create/eosReportCreationComponent.js
  lib/server/services/eosReport/EosReportService.js
  lib/server/services/eosReport/formatEosReport.js
  test/mocks/mock-eos-report.js
  test/public/eosReport/creation.test.js
  test/public/index.js
Labels: frontend, backend

#939 [O2B-841] Polish EOS report form
  lib/public/utilities/dateUtils.js
  lib/public/views/EosReport/create/eosReportCreationComponent.js
  lib/server/services/eosReport/formatEosReport.js
  lib/server/services/run/RunService.js
  lib/server/services/shift/ShiftService.js
  lib/server/services/shift/getShiftFromTimestamp.js
  lib/server/utilities/formatServerDate.js
  test/mocks/mock-eos-report.js
Labels: frontend

#941 [O2B-841] Remove EOS report link from logs pages
  lib/public/views/Logs/Overview/index.js
Labels: frontend

#940 [O2B-841] Add run comments
  lib/domain/dtos/eorReport/CreateEosReportDto.js
  lib/public/views/EosReport/EosReportModel.js
  lib/public/views/EosReport/create/EosReportCreationModel.js
  lib/public/views/EosReport/create/ecs/eosFormEcsSpecificPart.js
  lib/public/views/EosReport/create/eosReportCreationComponent.js
  lib/server/services/eosReport/EosReportService.js
  lib/server/services/eosReport/eosTypeSpecificFormatter/formatEcsEosReportTypeSpecific.js
  test/mocks/mock-eos-report.js
  test/public/eosReport/creation.test.js
Labels: frontend, backend

#943 [O2B-840] Add environment comments
  lib/domain/dtos/eorReport/CreateEosReportDto.js
  lib/public/views/EosReport/create/EosReportCreationModel.js
  lib/public/views/EosReport/create/ecs/eosFormEcsSpecificPart.js
  lib/server/services/eosReport/EosReportService.js
  lib/server/services/eosReport/eosTypeSpecificFormatter/formatEcsEosReportTypeSpecific.js
  test/mocks/mock-eos-report.js
Labels: frontend, backend

#944 [OGUI-840] Add predefined list of tags to be used for eos ecs entry
  lib/database/seeders/20200511151010-tags.js
  lib/server/services/eosReport/EosReportService.js
  lib/server/services/eosReport/eosTypeSpecificFormatter/getTypeSpecificTags.js
  test/lib/server/services/eosReport/EosReportService.test.js
Labels: backend

#945 [O2B-840] Format timestamp in shifter format
  lib/server/services/eosReport/eosTypeSpecificFormatter/formatEcsEosReportTypeSpecific.js
  lib/server/services/shift/formatShiftDate.js
  test/mocks/mock-eos-report.js
  test/public/eosReport/creation.test.js
Labels: backend

#826 [O2B-753] Search on log text
  lib/database/migrations/20221207075506-index-log-content.js
  lib/database/utilities/QueryBuilder.js
  lib/domain/dtos/GetAllLogsDto.js
  lib/public/components/Filters/common/filters/textFilter.js
  lib/public/views/Logs/ActiveColumns/logsActiveColumns.js
  lib/public/views/Logs/Logs.js
  lib/usecases/log/GetAllLogsUseCase.js
  test/api/logs.test.js
  test/lib/usecases/log/GetAllLogsUseCase.test.js
  test/public/logs/overview.test.js
Labels: frontend, backend

#947 [O2B-841] Open EOS links in new tabs
  lib/public/views/EosReport/create/ecs/eosFormEcsSpecificPart.js
  lib/public/views/EosReport/create/eosReportCreationComponent.js
Labels: frontend

#948 [release] 0.53.0
  CHANGELOG.md
  database/CHANGELOG.md
  lib/public/views/About/Overview/index.js
  package-lock.json
  package.json
Labels: release

#950 [O2B-852] Link runs to EoS automated report
  lib/server/services/eosReport/EosReportService.js
  test/lib/server/services/eosReport/EosReportService.test.js
Labels: backend

#953 [O2B-853] Use current user as EoS report log author
  lib/server/services/eosReport/EosReportService.js
  test/lib/server/services/eosReport/EosReportService.test.js
Labels: backend

#959 [O2B-831] Update chromium in dockerfile
  Dockerfile
Labels: dependencies, docker

#951 [O2B-854] Make dropdown sort case-insensible
  lib/public/components/common/selection/dropdown/SelectionDropdownModel.js
  lib/public/components/common/toggle/TogglableModel.js
  test/public/logs/overview.test.js
Labels: frontend

#960 [O2B-860] Include run duration in EoS report
  lib/public/views/EosReport/create/ecs/eosFormEcsSpecificPart.js
  lib/server/services/eosReport/eosTypeSpecificFormatter/formatEcsEosReportTypeSpecific.js
  test/mocks/mock-eos-report.js
  test/public/eosReport/creation.test.js
Labels: frontend, backend

#954 [O2B-855] Allow sifter name to be modified in EoS report
  lib/domain/dtos/eorReport/CreateEosReportDto.js
  lib/public/views/EosReport/create/EosReportCreationModel.js
  lib/public/views/EosReport/create/eosReportCreationComponent.js
  lib/server/services/eosReport/EosReportService.js
  lib/server/services/eosReport/formatEosReport.js
  test/mocks/mock-eos-report.js
  test/public/eosReport/creation.test.js
Labels: frontend, backend

#963 [O2B-831] Update chromium in dockerfile
  Dockerfile
Labels: dependencies, docker

#961 [O2B-859] Remove issues summary block from EoS report
  lib/domain/dtos/eorReport/CreateEosReportDto.js
  lib/public/views/EosReport/create/eosReportCreationComponent.js
  lib/server/services/eosReport/EosReportService.js
  lib/server/services/eosReport/formatEosReport.js
  test/mocks/mock-eos-report.js
  test/public/eosReport/creation.test.js
Labels: frontend, backend

#962 [O2B-856] Update EoS report cutoff from 2h to 30min
  lib/server/services/shift/ShiftService.js
Labels: backend

#964 [release] 0.53.1
  CHANGELOG.md
  lib/public/views/About/Overview/index.js
  package-lock.json
  package.json
Labels: release

#965 [OGUI-1350] Add manual trigger of release job
  .github/workflows/release.yml
Labels: CI

#966 [O2B-861] Fix data reset when clicking in EoS report's shifter-name input
  lib/public/components/common/markdown/markdown.js
  lib/public/views/EosReport/create/eosReportCreationComponent.js
  lib/public/views/Logs/Create/logCreationComponent.js
  test/public/eosReport/creation.test.js
Labels: bug, frontend

#968 [O2B-863] Sort runs' detectors list
  lib/database/adapters/RunAdapter.js
  lib/database/seeders/20221005120315-detector.js
  lib/database/seeders/20221006084006-run-detectors.js
  lib/usecases/run/GetAllRunsUseCase.js
  test/api/detectors.test.js
  test/lib/server/services/detector/DetectorService.test.js
  test/lib/server/services/detector/getAllDetectors.test.js
  test/lib/usecases/run/GetAllRunsUseCase.test.js
  test/lib/usecases/run/GetRunUseCase.test.js
  test/lib/usecases/run/StartRunUseCase.test.js
  test/public/lhcFills/detail.test.js
Labels: frontend, backend

#967 [O2B-862] Fix rbac middleware and restablish tag update access
  lib/server/middleware/rbac.middleware.js
  test/lib/server/middleware/rbac.middleware.test.js
Labels: bug, backend

#971 [O2B-864] Fix LHC fill infinite scroll
  lib/public/components/Pagination/PaginationModel.js
  lib/public/views/LhcFills/Overview/LhcFillsOverviewModel.js
Labels: bug, frontend

#973 [O2B-831] Update git in Dockerfile
  Dockerfile
Labels: dependencies, docker

#972 [O2B-857] Remove replies from EoS report logs
  lib/server/services/eosReport/getShiftIssues.js
  lib/server/services/log/getLogsByTagsInPeriod.js
  lib/server/services/shift/getShiftEnvironments.js
  test/lib/server/services/eosReport/EosReportService.test.js
  test/lib/server/services/log/getLogsByTagsInPeriod.test.js
  test/mocks/mock-eos-report.js
Labels: backend

#974 [release] 0.54.0
  CHANGELOG.md
  lib/public/views/About/Overview/index.js
  package-lock.json
  package.json
Labels: release
