Repository AliceO2Group/Bookkeeping, pull requests merged in 2023-07, with the labels that each got.

#1038 [O2B-922] Fix environment display badges
  lib/public/views/Environments/Details/EnvironmentDetailsPage.js
  test/public/envs/detailsPage.test.js
Labels: bug, frontend

#990 [O2B-867] Fetch all DPL processes executed for a given run and detector
  lib/server/controllers/dplProcess.controller.js
  lib/server/routers/dplProcess.router.js
  lib/server/services/dpl/DplProcessService.js
  lib/server/services/dpl/getDplDetector.js
  lib/server/services/dpl/getDplDetectorOrFail.js
  test/api/dplProcess.test.js
  test/lib/server/services/dpl/DplProcessService.test.js
Labels: backend

#992 [O2B-871] Fetch all process executions by host & run & detector
  lib/server/controllers/dplProcess.controller.js
  lib/server/routers/dplProcess.router.js
  lib/server/services/dpl/DplProcessService.js
  lib/server/services/host/getHost.js
  lib/server/services/host/getHostOrFail.js
  test/api/dplProcess.test.js
  test/lib/server/services/dpl/DplProcessService.test.js
Labels: backend

#1043 [O2B-923] Fix cosmics runs filtering
  lib/database/seeders/20200713103855-runs.js
  lib/server/services/run/getRunDefinition.js
  lib/usecases/run/GetAllRunsUseCase.js
  test/api/runs.test.js
  test/lib/usecases/run/GetAllRunsUseCase.test.js
  test/public/runs/overview.test.js
Labels: backend

#1042 [O2B-715] Add c++ library for DPL executed processes
  cxx-client/CMakeLists.txt
  cxx-client/example/exampleProtoServices.cxx
  cxx-client/include/BookkeepingApi/BkpClient.h
  cxx-client/include/BookkeepingApi/BkpProtoClient.h
  cxx-client/include/BookkeepingApi/BkpProtoClientFactory.h
  cxx-client/include/BookkeepingApi/DplProcessExecutionProtoClient.h
  cxx-client/include/BookkeepingApi/RunProtoClient.h
  cxx-client/src/grpc/GrpcBkpProtoClient.cxx
  cxx-client/src/grpc/GrpcBkpProtoClient.h
  cxx-client/src/grpc/services/GrpcDplProcessExecutionProtoClient.cxx
  cxx-client/src/grpc/services/GrpcDplProcessExecutionProtoClient.h
  cxx-client/src/grpc/services/GrpcRunProtoClient.h
  lib/server/services/dpl/DplProcessService.js
  test/api/dplProcess.test.js
  test/lib/server/services/dpl/DplProcessService.test.js
Labels: backend

#1045 [O2B-868] Extract a reusable tabbed panel component
  lib/public/components/TabbedPanel/TabbedPanelModel.js
  lib/public/components/TabbedPanel/tabbedPanelComponent.js
  lib/public/views/Runs/Details/RunDetailsPage.js
  lib/public/views/Runs/Details/editTagsPanel.js
  lib/public/views/Tags/Details/TagDetailsModel.js
  lib/public/views/Tags/Details/TagDetailsPage.js
  lib/public/views/Tags/Details/tagDetailsComponent.js
  lib/public/views/Tags/Tags.js
Labels: frontend

#1047 [O2B-868] Refactor run details tabs
  lib/public/Model.js
  lib/public/views/Runs/Details/RunDetailsModel.js
  lib/public/views/Runs/Details/RunDetailsPage.js
  lib/public/views/Runs/Details/lhcFillPanel.js
  lib/public/views/Runs/Details/runDetailsComponent.js
  lib/public/views/Runs/Runs.js
  lib/public/views/Tags/Details/TagDetailsModel.js
  test/public/flps/detail.test.js
  test/public/logs/detail.test.js
Labels: frontend

#1049 [O2B-868] Add DPL process to run details
  lib/database/seeders/20230428095106-dpl-executed-processes.js
  lib/public/app.css
  lib/public/components/common/table/remoteDataTableBody.js
  lib/public/components/common/table/table.js
  lib/public/components/common/tree/collapsibleTreeNode.js
  lib/public/models/CollapsibleTreeNodeModel.js
  lib/public/views/Runs/Details/RunDetailsModel.js
  lib/public/views/Runs/Details/runDetailsComponent.js
Labels: frontend

#1048 [O2B-924] Add icon to environments error
  lib/public/views/Environments/ActiveColumns/environmentsActiveColumns.js
  lib/public/views/Environments/format/displayEnvironmentStatus.js
Labels: frontend

#1050 Release 0.59.0
  CHANGELOG.md
  lib/public/views/About/Overview/index.js
  package-lock.json
  package.json
Labels: release

#1053 [O2B-715] Fix DPL seeders
  lib/database/seeders/20230428095027-dpl-detectors.js
  lib/database/seeders/20230428095047-dpl-processes.js
  lib/database/seeders/20230428095054-hosts.js
  lib/database/seeders/20230428095106-dpl-executed-processes.js
Labels: test

#1062 [O2B-932] Increase runs numbers column width on runs overview page
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
Labels: frontend

#1064 [O2B-795] Refactor GetAllRunsDto
  lib/domain/dtos/GetAllLogsDto.js
  lib/domain/dtos/GetAllRunsDto.js
  lib/domain/dtos/filters/FromToFilterDto.js
  lib/server/controllers/logs.controller.js
  lib/server/controllers/runs.controller.js
  lib/server/utilities/fromToValidator.js
  lib/server/utilities/index.js
  test/api/logs.test.js
  test/api/runs.test.js
Labels: backend

#1068 [O2B-932] Increase LHC period column size in runs overview
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
Labels: frontend

#1067 [O2B-910] Use bigint for readout counters
  .eslintrc
  cxx-client/example/exampleSpecificServices.cxx
  cxx-client/include/BookkeepingApi/FlpServiceClient.h
  cxx-client/src/grpc/services/GrpcFlpServiceClient.cxx
  cxx-client/src/grpc/services/GrpcFlpServiceClient.h
  lib/database/migrations/20230630155135-use-uint-64-readout-counters.js
  lib/database/models/flprole.js
  lib/database/seeders/20200921181553-flps.js
  lib/server/GRPCServer.js
  lib/server/gRPC/bindGRPCController.js
  lib/server/gRPC/services/protoParsing/extractEnumsPaths.js
  lib/server/gRPC/services/protoParsing/extractFieldsConverters.js
  lib/server/utilities/bigIntConverter.js
  proto/flp.proto
  test/gRPC/extractAbsoluteMessageDefinitions.test.js
  test/gRPC/extractFieldConverters.test.js
  test/gRPC/gRPCEnumValueConverter.test.js
  test/gRPC/index.js
  test/gRPC/proto/main.proto
  test/gRPC/serviceImplementation.js
  test/gRPC/serviceImplementation.test.js
  test/index.js
  test/lib/server/utilities/bigIntConverter.test.js
  test/lib/server/utilities/index.js
Labels: backend

#1056 [O2B-795] Store run definition in database
  docs/RUN_DEFINITIONS.md
  lib/database/adapters/RunAdapter.js
  lib/database/migrations/20230706083148-add-run-definition-column.js
  lib/database/models/run.js
  lib/database/models/typedefs/SequelizeRun.js
  lib/database/seeders/20200713103855-runs.js
  lib/domain/dtos/GetAllRunsDto.js
  lib/domain/entities/Run.js
  lib/server/services/eosReport/EosReportService.js
  lib/server/services/eosReport/eosTypeSpecificFormatter/formatEcsEosReportTypeSpecific.js
  lib/server/services/run/RunService.js
  lib/server/services/run/createRun.js
  lib/server/services/run/getRunDefinition.js
  lib/server/services/run/refreshRunsDefinitions.js
  lib/server/services/run/updateRun.js
  lib/server/services/shift/getShiftRuns.js
  lib/usecases/lhcFill/UpdateLhcFillUseCase.js
  lib/usecases/lhcFill/checkLhcFill.js
  lib/usecases/run/GetAllRunsUseCase.js
  test/lib/server/services/eosReport/EosReportService.test.js
  test/lib/server/services/run/RunService.test.js
  test/lib/server/services/run/index.js
  test/lib/server/services/run/updateRun.test.js
  test/lib/usecases/lhcFill/UpdateLhcFillUseCase.test.js
  test/lib/usecases/run/GetAllRunsUseCase.test.js
  test/lib/usecases/run/StartRunUseCase.test.js
  test/mocks/mock-ecs-eos-report.js
  test/mocks/mock-qc-pdp-eos-report.js
  test/mocks/mock-run.js
  test/public/eosReport/ecs-creation.test.js
  test/public/eosReport/qc-pdp-creation.test.js
  test/public/eosReport/shift-leader-creation.test.js
Labels: backend, db

#1061 [O2B-927] Hide duplicated and verbose information in log tree view
  lib/public/components/Log/logCollapsed.js
  lib/public/components/Log/logExpanded.js
  lib/public/components/Log/logLinkButton.js
  lib/public/components/Log/logReplyButton.js
  lib/public/components/common/clipboardTarget.js
  lib/public/views/Logs/Details/logTreeViewComponent.js
  test/public/logs/create.test.js
  test/public/logs/detail.test.js
Labels: frontend

#1070 [O2B-928] Run type filter dropdown
  lib/public/components/Filters/RunsFilter/runTypeFilter.js
  lib/public/components/runTypes/RunTypesSelectionDropdownModel.js
  lib/public/components/runTypes/runTypeToOption.js
  lib/public/services/runTypes/runTypesProvider.js
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
  lib/public/views/Runs/Runs.js
  lib/usecases/run/GetAllRunsUseCase.js
  test/public/runs/overview.test.js
Labels: frontend, backend

#1074 [O2B-795] Separate runs filtering from the actual fetching
  lib/domain/dtos/GetAllRunsDto.js
  lib/domain/dtos/filters/NumericalComparisonDto.js
  lib/domain/dtos/filters/RunFilterDto.js
  lib/usecases/run/GetAllRunsUseCase.js
Labels: backend

#1072 [O2B-929] Run details should list all detectors
  lib/domain/entities/Run.js
  lib/domain/entities/RunDetectorQuality.js
  lib/public/views/Runs/Details/RunDetailsModel.js
  lib/public/views/Runs/format/formatRunDetectors.js
  test/public/runs/detail.test.js
Labels: frontend

#1076 [O2B-936] Convert int64 to numbers instead of bigint as temporary workaround for dates
  lib/server/gRPC/services/protoParsing/extractFieldsConverters.js
  lib/server/utilities/bigIntConverter.js
Labels: backend

#1077 Release 0.60.0
  CHANGELOG.md
  lib/public/views/About/Overview/index.js
  package-lock.json
  package.json
Labels: release
