Repository AliceO2Group/Bookkeeping, pull requests merged in 2023-05, with the labels that each got.

#978 [O2B-878] Use new headless chrome for puppeteer tests
  test/public/defaults.js
Labels: test

#981 [O2B-831] Update ca-certificates in dockerfile
  Dockerfile
Labels: docker

#977 [O2B-877] Prepare existing tests to easily add QC EoS report tests
  lib/database/seeders/20200511151010-tags.js
  lib/domain/dtos/eosReport/CreateEosReportDto.js
  lib/server/controllers/eosReport.controller.js
  lib/server/services/eosReport/eosTypeSpecificFormatter/formatEcsEosReportTypeSpecific.js
  lib/server/services/shift/ShiftService.js
  test/api/eosReport.test.js
  test/api/shift.test.js
  test/api/tags.test.js
  test/lib/server/services/eosReport/EosReportService.test.js
  test/lib/server/services/eosReport/formatEosReport.test.js
  test/lib/server/services/shift/ShiftService.test.js
  test/lib/usecases/tag/GetAllTagsUseCase.test.js
  test/mocks/base-mock-eos-report.js
  test/mocks/mock-ecs-eos-report.js
  test/public/eosReport/ecs-creation.test.js
  test/public/eosReport/index.js
  test/public/tags/overview.test.js
Labels: test

#980 [O2B-875] Add QC/PDP EoS report generation
  lib/server/services/detector/getOrCreateAllDetectorsByName.js
  lib/server/services/eosReport/EosReportService.js
  lib/server/services/eosReport/eosTypeSpecificFormatter/formatEcsEosReportTypeSpecific.js
  lib/server/services/eosReport/eosTypeSpecificFormatter/formatQcPdpEosReportTypeSpecific.js
  lib/server/services/eosReport/formatEosReport.js
  lib/server/services/eosReport/formatters.js
  test/lib/server/services/detector/getOrCreateAllDetectors.test.js
  test/lib/server/services/eosReport/EosReportService.test.js
  test/lib/server/services/eosReport/formatEosReport.test.js
  test/lib/server/services/eosReport/formatters.test.js
  test/lib/server/services/eosReport/index.js
  test/mocks/base-mock-eos-report.js
  test/mocks/mock-ecs-eos-report.js
  test/mocks/mock-qc-pdp-eos-report.js
Labels: backend

#983 [O2B-881] Add CTF file size sum in LHC fill display
  lib/database/seeders/20200713103855-runs.js
  lib/public/services/lhcFill/LhcFillStatisticsExtractor.js
  lib/public/views/LhcFills/Detail/lhcFillDetailsComponent.js
  test/public/lhcFills/detail.test.js
Labels: frontend

#984 [O2B-880] Display file size in human readable format
  lib/public/utilities/formatting/formatFileSize.js
  lib/public/views/LhcFills/Detail/lhcFillDetailsComponent.js
  lib/public/views/Runs/Details/runDetailsConfiguration.js
  test/public/lhcFills/detail.test.js
Labels: frontend

#985 [release] 0.55.0
  CHANGELOG.md
  lib/public/views/About/Overview/index.js
  package-lock.json
  package.json
Labels: release

#994 [O2B-887] Add missing QC tags to EoS report
  lib/database/seeders/20200511151010-tags.js
  lib/server/services/eosReport/eosTypeSpecificFormatter/getEosReportTagsByType.js
  test/api/tags.test.js
  test/lib/usecases/tag/GetAllTagsUseCase.test.js
  test/public/tags/overview.test.js
Labels: backend

#995 [release] 0.55.1
  CHANGELOG.md
  lib/public/views/About/Overview/index.js
  package-lock.json
  package.json
Labels: release

#1001 [O2B-890] Physics Def should include both ITS and FT0
  docs/RUN_DEFINITIONS.md
  lib/database/repositories/qbHelpers/lhcFill/physicsRunsIncludeExpression.js
  lib/database/seeders/20200713103855-runs.js
  lib/server/services/run/getRunDefinition.js
  lib/usecases/run/GetAllRunsUseCase.js
  test/lib/server/services/run/getRunDefinition.test.js
  test/lib/usecases/lhcFill/GetLhcFillUseCase.test.js
  test/lib/usecases/run/GetAllRunsUseCase.test.js
  test/mocks/mock-run.js
  test/public/runs/overview.test.js
Labels: documentation, backend

#1002 [release/0.55.2]
  CHANGELOG.md
  lib/public/views/About/Overview/index.js
  package-lock.json
  package.json
Labels: release
