Repository AliceO2Group/Bookkeeping, pull requests merged in 2024-04, with the labels that each got.

#1442 [O2B-1184] Add QC Flag Types overview page
  lib/public/Model.js
  lib/public/components/Filters/common/filters/checkboxFilter.js
  lib/public/components/NavBar/index.js
  lib/public/view.js
  lib/public/views/QcFlagTypes/ActiveColumns/qcFlagTypesActiveColumns.js
  lib/public/views/QcFlagTypes/Overview/QcFlagTypesOverviewModel.js
  lib/public/views/QcFlagTypes/Overview/QcFlagTypesOverviewPage.js
  lib/public/views/QcFlagTypes/QcFlagTypesModel.js
  lib/server/controllers/qcFlagTypes.controller.js
  lib/server/routers/qcFlagTypes.router.js
  lib/server/services/qualityControlFlag/QcFlagTypeService.js
  package-lock.json
  package.json
  test/public/defaults.js
  test/public/index.js
  test/public/logs/overview.test.js
  test/public/qcFlagTypes/index.js
  test/public/qcFlagTypes/overview.test.js
  test/public/simulationPasses/overviewAnchoredSimulationPasses.test.js
  test/public/simulationPasses/overviewPerLhcPeriod.test.js
Labels: frontend

#1468 [O2B-1197] Fix resetting of beamType filter
  lib/public/views/lhcPeriods/Overview/LhcPeriodsOverviewModel.js
  test/public/lhcPeriods/overview.test.js
Labels: frontend

#1456 Reduced MonALISA Synchroniser error logs
  lib/server/monalisa-synchronization/MonAlisaSynchronizer.js
Labels: backend

#1487 [O2B-1207] Replace docker-compose by docker compose
  .github/workflows/bookkeeping.yml
  .github/workflows/docker.yml
  docs/DOCKER.md
  docs/get-started.md
Labels: docker

#1485 [O2B-1138] Move sort model declaration to generic overview model
  lib/public/models/OverviewModel.js
  lib/public/views/DataPasses/PerLhcPeriodOverview/DataPassesPerLhcPeriodOverviewModel.js
  lib/public/views/DataPasses/PerLhcPeriodOverview/DataPassesPerLhcPeriodOverviewView.js
  lib/public/views/QcFlagTypes/Overview/QcFlagTypesOverviewModel.js
  lib/public/views/SimulationPasses/AnchoredOverview/AnchoredSimulationPassesOverviewModel.js
  lib/public/views/SimulationPasses/PerLhcPeriodOverview/SimulationPassesPerLhcPeriodOverviewModel.js
  lib/public/views/lhcPeriods/Overview/LhcPeriodsOverviewModel.js
  lib/public/views/lhcPeriods/Overview/LhcPeriodsOverviewPage.js
Labels: frontend

#1486 Remove redundant test suite call
  test/api/index.js
Labels: backend

#1488 [O2B-1209] Fix log reply main panel size
  lib/public/app.css
  lib/public/views/Logs/Create/logCreationComponent.js
Labels: bug, frontend

#1443 [O2B-1185] Add QC Flag types creation endpoint
  lib/domain/dtos/DtoFactory.js
  lib/server/controllers/qcFlagTypes.controller.js
  lib/server/express/updateExpressResponseFromNativeError.js
  lib/server/routers/qcFlagTypes.router.js
  lib/server/services/qualityControlFlag/QcFlagTypeService.js
  test/api/qcFlagTypes.test.js
  test/lib/server/services/qualityControlFlag/QcFlagTypeService.test.js
  test/lib/server/services/qualityControlFlag/index.js
Labels: backend

#1489 [O2B-821] Make all public routes private
  lib/server/routers/attachments.router.js
  lib/server/routers/configuration.router.js
  lib/server/routers/dataPasses.router.js
  lib/server/routers/detectors.router.js
  lib/server/routers/dplDetectors.router.js
  lib/server/routers/dplProcess.router.js
  lib/server/routers/environments.router.js
  lib/server/routers/eosReport.router.js
  lib/server/routers/flps.router.js
  lib/server/routers/home.router.js
  lib/server/routers/index.js
  lib/server/routers/lhcFills.router.js
  lib/server/routers/lhcPeriodsStatistics.router.js
  lib/server/routers/logs.router.js
  lib/server/routers/qcFlagTypes.router.js
  lib/server/routers/runTypes.router.js
  lib/server/routers/runs.router.js
  lib/server/routers/shift.router.js
  lib/server/routers/simulationPasses.router.js
  lib/server/routers/statistics.router.js
  lib/server/routers/status.router.js
  lib/server/routers/subsystems.router.js
  lib/server/routers/tags.router.js
Labels: backend

#1490 [O2B-821] Add default routes args
  lib/server/routers/index.js
Labels: bug, backend

#1374 [O2B-1134] Implement Runs per Simulation Pass view
  lib/domain/dtos/filters/RunFilterDto.js
  lib/public/Model.js
  lib/public/components/common/table/table.js
  lib/public/view.js
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
  lib/public/views/Runs/RunsModel.js
  lib/public/views/Runs/RunsPerSimulationPass/RunsPerSimulationPassOverviewModel.js
  lib/public/views/Runs/RunsPerSimulationPass/RunsPerSimulationPassOverviewPage.js
  lib/public/views/SimulationPasses/ActiveColumns/simulationPassesActiveColumns.js
  lib/usecases/run/GetAllRunsUseCase.js
  test/api/runs.test.js
  test/public/defaults.js
  test/public/runs/index.js
  test/public/runs/runsPerSimulationPass.overview.test.js
Labels: frontend, backend

#1447 [O2B-1186] Add QC flag type creation page
  lib/public/Model.js
  lib/public/view.js
  lib/public/views/QcFlagTypes/Create/QcFlagTypeCreationModel.js
  lib/public/views/QcFlagTypes/Create/QcFlagTypeCreationPage.js
  lib/public/views/QcFlagTypes/Overview/QcFlagTypesOverviewPage.js
  lib/public/views/QcFlagTypes/QcFlagTypesModel.js
  test/public/qcFlagTypes/creation.test.js
  test/public/qcFlagTypes/index.js
Labels: frontend

#1492 [O2B-1209] Fix panel sizing in logs
  lib/public/components/common/panel/PanelComponent.js
Labels: bug, frontend

#1448 [O2B-1191] Add QC flag type update endpoint
  lib/domain/dtos/DtoFactory.js
  lib/server/controllers/qcFlagTypes.controller.js
  lib/server/routers/qcFlagTypes.router.js
  lib/server/services/qualityControlFlag/QcFlagTypeService.js
  test/api/qcFlagTypes.test.js
  test/lib/server/services/qualityControlFlag/QcFlagTypeService.test.js
Labels: backend

#1495 Fix fill number not being filled when creating log for run
  lib/public/views/Runs/Details/runDetailsComponent.js
Labels: bug, frontend

#1494 [O2B-1168] Add QCG links to runs overview and details
  lib/config/services.js
  lib/public/components/common/externalLinks/infologgerLinksComponents.js
  lib/public/components/common/externalLinks/qcGuiLinkComponent.js
  lib/public/services/externalRouting/getRunQcGuiLinkUrl.js
  lib/public/views/Environments/ActiveColumns/environmentsActiveColumns.js
  lib/public/views/LhcFills/ActiveColumns/lhcFillsActiveColumns.js
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
  lib/public/views/Runs/Details/runDetailsComponent.js
  lib/server/controllers/configuration.controller.js
  lib/server/services/housekeeping/handleLostRunsAndEnvironments.js
  test/api/configuration.test.js
  test/public/runs/detail.test.js
  test/public/runs/overview.test.js
Labels: frontend

#1493 [O2B-1211] Fix shift computation with daylight saving time switch
  lib/server/services/shift/getShiftFromTimestamp.js
  test/lib/server/services/shift/getShiftFromTimestamp.test.js
Labels: backend

#1499 [O2B-1200] Add QC flags creation API
  lib/server/controllers/qcFlag.controller.js
  lib/server/routers/qcFlag.router.js
  lib/server/services/qualityControlFlag/QcFlagService.js
  test/api/qcFlags.test.js
  test/lib/server/services/qualityControlFlag/QcFlagService.test.js
Labels: backend

#1481 [O2B-1204] Several improvements of the on-call template
  lib/public/views/Logs/Create/templates/OnCallLogTemplate.js
  lib/public/views/Logs/Create/templates/onCallLogCreationConfiguration.js
  test/public/logs/create.test.js
Labels: frontend

#1503 Release 0.83.0
  CHANGELOG.md
  database/CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#1506 Remove spurious detectors from Runs views
  lib/public/views/Runs/ActiveColumns/runDetectorsAsyncQcActiveColumns.js
  test/public/runs/runsPerDataPass.overview.test.js
  test/public/runs/runsPerSimulationPass.overview.test.js
Labels: bug, frontend

#1501 [O2B-1157] Add QC Flag delete API
  lib/database/repositories/Repository.js
  lib/server/controllers/qcFlag.controller.js
  lib/server/errors/AccessDeniedError.js
  lib/server/express/updateExpressResponseFromNativeError.js
  lib/server/routers/qcFlag.router.js
  lib/server/services/qualityControlFlag/QcFlagService.js
  test/api/qcFlags.test.js
  test/lib/server/services/qualityControlFlag/QcFlagService.test.js
Labels: backend

#1511 [O2B-1155] Visual improvements of QC flag creation
  lib/public/components/Filters/common/filters/timeRangeFilter.js
  lib/public/components/common/form/inputs/TimeRangeInputComponent.js
  lib/public/views/QcFlags/Create/ForDataPass/QcFlagCreationForDataPassPage.js
  lib/public/views/QcFlags/Create/qcFlagCreationComponent.js
Labels: frontend

#1512 [O2B-1163] Add QC flag verification API
  lib/database/repositories/QcFlagVerificationRepository.js
  lib/database/repositories/index.js
  lib/server/controllers/qcFlag.controller.js
  lib/server/routers/qcFlag.router.js
  lib/server/services/qualityControlFlag/QcFlagService.js
  test/api/qcFlags.test.js
  test/lib/server/services/qualityControlFlag/QcFlagService.test.js
Labels: backend

#1510 [O2B-1168] Add runType and detector to QCG link
  lib/public/services/externalRouting/getRunQcGuiLinkUrl.js
  test/public/runs/detail.test.js
  test/public/runs/overview.test.js
Labels: bug, frontend

#1515 [O2B-1157] Improve QC flags get all API
  lib/database/adapters/DataPassQcFlagAdapter.js
  lib/database/adapters/SimulationPassQcFlagAdapter.js
  lib/database/adapters/index.js
  lib/database/models/dataPassQcFlag.js
  lib/database/models/index.js
  lib/database/models/simulationPassQcFlag.js
  lib/database/models/typedefs/SequelizeDataPassQcFlag.js
  lib/database/models/typedefs/SequelizeQcFlag.js
  lib/database/models/typedefs/SequelizeSimulationPassQcFlag.js
  lib/database/repositories/DataPassQcFlagRepository.js
  lib/database/repositories/SimulationPassQcFlagRepository.js
  lib/database/repositories/index.js
  lib/domain/entities/DataPassQcFlag.js
  lib/domain/entities/QcFlag.js
  lib/domain/entities/QcFlagType.js
  lib/domain/entities/SimulationPassQcFlag.js
  lib/public/components/common/table/table.js
  lib/public/views/QcFlags/ForDataPass/QcFlagsForDataPassOverviewModel.js
  lib/public/views/QcFlags/ForDataPass/QcFlagsForDataPassOverviewPage.js
  lib/public/views/QcFlags/ForSimulationPass/QcFlagsForSimulationPassOverviewModel.js
  lib/public/views/QcFlags/ForSimulationPass/QcFlagsForSimulationPassOverviewPage.js
  lib/public/views/QcFlags/Overview/QcFlagsOverviewModel.js
  lib/server/controllers/qcFlag.controller.js
  lib/server/errors/AdapterError.js
  lib/server/routers/qcFlag.router.js
  lib/server/services/qualityControlFlag/QcFlagService.js
  test/api/qcFlags.test.js
  test/lib/server/services/qualityControlFlag/QcFlagService.test.js
  test/public/qcFlags/forDataPassCreation.test.js
  test/public/qcFlags/index.js
Labels: frontend, backend

#1519 [O2B-1214] Allow filtering runs on none of the tags
  lib/domain/dtos/filters/RunFilterDto.js
  lib/public/components/Filters/RunsFilter/DetectorsFilterModel.js
  lib/public/components/Filters/common/CombinationOperatorChoiceModel.js
  lib/public/components/Filters/common/TagFilterModel.js
  lib/public/views/Runs/Overview/RunsOverviewModel.js
  lib/usecases/run/GetAllRunsUseCase.js
  test/api/runs.test.js
  test/lib/usecases/run/GetAllRunsUseCase.test.js
  test/public/runs/overview.test.js
Labels: frontend, backend

#1520 [O2B-1213] Add Inelastic interaction rate (INEL) values
  lib/database/adapters/RunAdapter.js
  lib/database/migrations/20240417163030-add-Mu-and-Inel-columns-to-runs.js
  lib/database/models/run.js
  lib/database/models/typedefs/SequelizeRun.js
  lib/database/seeders/20220503120937-lhc-fills.js
  lib/domain/dtos/UpdateRunDto.js
  lib/domain/entities/Run.js
  lib/public/components/Detail/detailsList.js
  lib/public/utilities/formatting/formatFloat.js
  lib/public/views/Runs/ActiveColumns/inelasticInteractionRateActiveColumnsForPbPb.js
  lib/public/views/Runs/ActiveColumns/inelasticInteractionRateActiveColumnsForProtonProton.js
  lib/public/views/Runs/Details/RunPatch.js
  lib/public/views/Runs/Details/runDetailsConfiguration.js
  lib/public/views/Runs/RunPerDataPass/RunsPerDataPassOverviewPage.js
  lib/public/views/Runs/RunPerPeriod/RunsPerLhcPeriodOverviewPage.js
  lib/public/views/Runs/RunsPerSimulationPass/RunsPerSimulationPassOverviewPage.js
  lib/public/views/Runs/format/formatEditableNumber.js
  test/api/runs.test.js
  test/public/runs/detail.test.js
  test/public/runs/runsPerDataPass.overview.test.js
  test/public/runs/runsPerPeriod.overview.test.js
  test/public/runs/runsPerSimulationPass.overview.test.js
Labels: frontend, backend

#1522 Release 0.85.0
  CHANGELOG.md
  database/CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#1527 [O2B-1220] Place RCT entry point directly in navigation bar
  lib/public/components/NavBar/index.js
Labels: frontend

#1523 Fix randomly failing QC flag type test
  test/public/defaults.js
Labels: frontend

#1532 [O2B-894] Mark run nullable properties as optional in proto
  proto/common.proto
Labels: backend

#1508 [O2B-1186] QC flag type creation page improvements
  lib/public/app.css
  lib/public/views/QcFlagTypes/Create/QcFlagTypeCreationPage.js
Labels: frontend

#1521 [O2B-1216] Change QC flag delete button accessibility to admins only
  lib/public/views/QcFlags/details/forDataPass/QcFlagDetailsForDataPassPage.js
  lib/public/views/QcFlags/details/forSimulationPass/QcFlagDetailsForSimulationPassPage.js
  lib/server/controllers/qcFlag.controller.js
  lib/server/routers/qcFlag.router.js
  lib/server/services/qualityControlFlag/QcFlagService.js
  test/api/qcFlags.test.js
  test/lib/server/services/qualityControlFlag/QcFlagService.test.js
Labels: frontend

#1524 [O2B-1177] Add runs counts for simulation pass overview
  lib/public/views/SimulationPasses/ActiveColumns/simulationPassesActiveColumns.js
  test/public/simulationPasses/overviewAnchoredSimulationPasses.test.js
  test/public/simulationPasses/overviewPerLhcPeriod.test.js
Labels: frontend

#1525 [O2B-1179] Add data passes counts for simulation pass overview
  lib/public/views/SimulationPasses/ActiveColumns/simulationPassesActiveColumns.js
  test/public/simulationPasses/overviewAnchoredSimulationPasses.test.js
  test/public/simulationPasses/overviewPerLhcPeriod.test.js
Labels: frontend

#1476 [O2B-1171] Do not display missing trigger start/stop when trigger is OFF
  lib/database/seeders/20200713103855-runs.js
  lib/public/components/Filters/RunsFilter/triggerValueFilter.js
  lib/public/domain/enums/TriggerValue.js
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
  lib/public/views/Runs/format/displayRunDuration.js
  lib/public/views/Runs/format/formatRunEnd.js
  lib/public/views/Runs/format/formatRunStart.js
  test/api/runs.test.js
  test/lib/usecases/run/GetAllRunsUseCase.test.js
  test/public/runs/detail.test.js
  test/public/runs/overview.test.js
Labels: frontend

#1534 Release 0.86.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release
