Repository AliceO2Group/Bookkeeping, pull requests merged in 2024-05, with the labels that each got.

#1540 Improve frontend tests robustness
  lib/public/components/common/table/remoteDataTableBody.js
  test/public/defaults.js
  test/public/envs/detailsPage.test.js
  test/public/lhcFills/detail.test.js
  test/public/logs/create.test.js
  test/public/logs/detail.test.js
  test/public/logs/overview.test.js
  test/public/qcFlags/forDataPassCreation.test.js
  test/public/qcFlags/forDataPassOverview.test.js
  test/public/qcFlags/forSimulationPassCreation.test.js
  test/public/qcFlags/forSimulationPassOverview.test.js
  test/public/runs/detail.test.js
  test/public/runs/overview.test.js
  test/public/runs/runsPerDataPass.overview.test.js
  test/public/runs/runsPerSimulationPass.overview.test.js
Labels: frontend

#1542 [O2B-1232] Add author and tags to get all logs
  lib/database/repositories/Repository.js
  lib/server/services/log/LogService.js
  lib/usecases/log/GetAllLogsUseCase.js
  test/public/lhcFills/detail.test.js
Labels: bug, backend

#1537 [O2B-1227] Add tags to RC daily log template
  lib/database/seeders/20200511151010-tags.js
  lib/public/components/Filters/common/filters/timeRangeFilter.js
  lib/public/components/common/form/inputs/DateTimeInputComponent.js
  lib/public/utilities/dateUtils.mjs
  lib/public/utilities/formatting/formatFullDate.js
  lib/public/utilities/formatting/formatTimestamp.js
  lib/public/views/EosReport/create/eosReportCreationComponent.js
  lib/public/views/Logs/Create/templates/RcDailyMeetingTemplate.js
  lib/public/views/Logs/Create/templates/rcDailyMeetingConfiguration.js
  lib/public/views/Runs/format/formatRunEnd.js
  lib/public/views/Runs/format/formatRunStart.js
  lib/public/views/Statistics/StatisticsPageModel.js
  test/api/tags.test.js
  test/lib/usecases/tag/GetAllTagsUseCase.test.js
  test/public/logs/create.test.js
  test/public/logs/detail.test.js
  test/public/logs/overview.test.js
  test/public/tags/overview.test.js
Labels: frontend

#1548 Release 0.87.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#1549 [O2B-1227] Fix RC template tests failing in the morning
  test/public/logs/create.test.js
Labels: backend

#1546 [O2B-1153] Preliminary QC flag service refactoring
  lib/server/controllers/qcFlag.controller.js
  lib/server/services/dpl/getPhysicalDplDetectorOrFail.js
  lib/server/services/qualityControlFlag/QcFlagService.js
  test/lib/server/services/qualityControlFlag/QcFlagService.test.js
Labels: backend

#1526 [O2B-1221] Reduce links display to count badges
  lib/public/views/DataPasses/ActiveColumns/dataPassesActiveColumns.js
  lib/public/views/lhcPeriods/ActiveColumns/lhcPeriodsActiveColumns.js
  test/public/dataPasses/overviewPerLhcPeriod.test.js
  test/public/dataPasses/overviewPerSimulationPass.test.js
  test/public/lhcPeriods/overview.test.js
Labels: frontend

#1467 [O2B-1099] Move reset filter button on top of filter panel
  lib/public/components/Filters/common/filtersPanelPopover.js
  test/public/dataPasses/overviewPerLhcPeriod.test.js
  test/public/dataPasses/overviewPerSimulationPass.test.js
  test/public/defaults.js
  test/public/lhcPeriods/overview.test.js
  test/public/simulationPasses/overviewPerLhcPeriod.test.js
Labels: frontend

#1425 [O2B-1137] Make RCT Runs overviews horizontally scrollable
  lib/public/components/common/table/table.js
  lib/public/models/OverviewModel.js
  lib/public/views/Runs/RunPerDataPass/RunsPerDataPassOverviewModel.js
  lib/public/views/Runs/RunPerDataPass/RunsPerDataPassOverviewPage.js
  lib/public/views/Runs/RunPerPeriod/RunsPerLhcPeriodOverviewModel.js
  lib/public/views/Runs/RunPerPeriod/RunsPerLhcPeriodOverviewPage.js
  lib/public/views/Runs/RunsPerSimulationPass/RunsPerSimulationPassOverviewModel.js
  lib/public/views/Runs/RunsPerSimulationPass/RunsPerSimulationPassOverviewPage.js
Labels: frontend

#1541 [O2B-1163] Add a verification form into QC flag details page
  lib/database/adapters/DataPassQcFlagAdapter.js
  lib/database/adapters/SimulationPassQcFlagAdapter.js
  lib/database/adapters/index.js
  lib/database/seeders/20240404100811-qc-flags.js
  lib/public/components/common/form/deleteButton.js
  lib/public/views/QcFlags/ActiveColumns/qcFlagVerificationsActiveColumns.js
  lib/public/views/QcFlags/ActiveColumns/qcFlagsActiveColumns.js
  lib/public/views/QcFlags/details/QcFlagDetailsModel.js
  lib/public/views/QcFlags/details/forDataPass/QcFlagDetailsForDataPassPage.js
  lib/public/views/QcFlags/details/forSimulationPass/QcFlagDetailsForSimulationPassPage.js
  lib/public/views/QcFlags/details/qcFlagDetailsComponent.js
  lib/public/views/QcFlags/details/qcFlagDetailsConfiguration.js
  lib/server/services/qualityControlFlag/QcFlagService.js
  test/api/qcFlags.test.js
  test/lib/server/services/qualityControlFlag/QcFlagService.test.js
  test/public/qcFlags/detailsForDataPass.test.js
  test/public/qcFlags/detailsForSimulationPass.test.js
  test/public/qcFlags/forSimulationPassOverview.test.js
Labels: frontend

#1550 [O2B-1253] Set DPL detectors order in RCT views
  lib/public/domain/enums/detectorsNames.js
  lib/public/services/detectors/detectorsProvider.js
  lib/public/services/detectors/dplDetectorsProvider.js
Labels: frontend

#1533 [O2B-1217] Calculate QC flags effective periods
  lib/database/migrations/20240424092020-add-qc-flag-effective-periods-table.js
  lib/database/models/index.js
  lib/database/models/qcFlag.js
  lib/database/models/qcFlagEffectivePeriod.js
  lib/database/models/typedefs/SequelizeQcFlagEffectivePeriod.js
  lib/database/repositories/QcFlagEffectivePeriodRepository.js
  lib/database/repositories/Repository.js
  lib/database/repositories/index.js
  lib/database/seeders/20240404100811-qc-flags.js
  lib/server/services/qualityControlFlag/QcFlagService.js
  test/api/qcFlags.test.js
  test/lib/server/services/qualityControlFlag/QcFlagService.test.js
  test/public/defaults.js
Labels: backend

#1556 [O2B-1256] Cannot create flag for GLO
  lib/database/seeders/20230428095027-dpl-detectors.js
  lib/public/domain/enums/detectorsNames.mjs
  lib/public/services/detectors/detectorsProvider.js
  lib/public/services/detectors/dplDetectorsProvider.js
  lib/public/views/Runs/ActiveColumns/runDetectorsAsyncQcActiveColumns.js
  lib/server/services/qualityControlFlag/QcFlagService.js
  test/api/dplDetectors.test.js
  test/api/qcFlags.test.js
  test/lib/server/services/dpl/DplDetectorsService.test.js
  test/lib/server/services/dpl/DplProcessService.test.js
Labels: frontend, backend

#1552 [O2B-1217] Add QC flags summary display
  lib/database/adapters/QcFlagEffectivePeriodAdapter.js
  lib/database/adapters/index.js
  lib/database/utilities/QueryBuilder.js
  lib/public/components/common/badge.js
  lib/public/components/qcFlags/qcFlagsPagesButtons.js
  lib/public/views/QcFlags/Create/forDataPass/QcFlagCreationForDataPassPage.js
  lib/public/views/QcFlags/Create/forSimulationPass/QcFlagCreationForSimulationPassModel.js
  lib/public/views/QcFlags/Create/forSimulationPass/QcFlagCreationForSimulationPassPage.js
  lib/public/views/QcFlags/ForDataPass/QcFlagsForDataPassOverviewPage.js
  lib/public/views/QcFlags/ForSimulationPass/QcFlagsForSimulationPassOverviewPage.js
  lib/public/views/Runs/ActiveColumns/runDetectorsAsyncQcActiveColumns.js
  lib/public/views/Runs/RunPerDataPass/RunsPerDataPassOverviewModel.js
  lib/public/views/Runs/RunPerDataPass/RunsPerDataPassOverviewPage.js
  lib/public/views/Runs/RunsPerSimulationPass/RunsPerSimulationPassOverviewModel.js
  lib/public/views/Runs/RunsPerSimulationPass/RunsPerSimulationPassOverviewPage.js
  lib/server/controllers/qcFlag.controller.js
  lib/server/routers/qcFlag.router.js
  lib/server/services/qualityControlFlag/QcFlagService.js
  test/api/qcFlags.test.js
  test/lib/server/services/qualityControlFlag/QcFlagService.test.js
  test/public/defaults.js
  test/public/runs/runsPerDataPass.overview.test.js
  test/public/runs/runsPerPeriod.overview.test.js
  test/public/runs/runsPerSimulationPass.overview.test.js
Labels: frontend, backend

#1560 [O2B-1260] Fix detectors order
  lib/public/services/detectors/dplDetectorsProvider.js
Labels: frontend

#1567 Fix QC flags tests
  test/public/qcFlags/forDataPassCreation.test.js
  test/public/qcFlags/forSimulationPassCreation.test.js
Labels: backend

#1565 [O2B-1153] Prepare QC flag gRPC API
  lib/database/seeders/20240213120811-qc-flags-types.js
  lib/public/services/detectors/dplDetectorsProvider.js
  lib/server/controllers/qcFlag.controller.js
  lib/server/services/dataPasses/DataPassService.js
  lib/server/services/dataPasses/getOneDataPass.js
  lib/server/services/dataPasses/getOneDataPassOrFail.js
  lib/server/services/dpl/getPhysicalDplDetectorOrFail.js
  lib/server/services/qualityControlFlag/QcFlagService.js
  lib/server/services/simulationPasses/SimulationPassService.js
  lib/server/services/simulationPasses/getOneSimulationPass.js
  lib/server/services/simulationPasses/getOneSimulationPassOrFail.js
  test/api/simulationPasses.test.js
  test/lib/server/services/dataPasses/DataPassesService.test.js
  test/lib/server/services/qualityControlFlag/QcFlagService.test.js
  test/lib/server/services/simulationPasses/SimulationPassesService.test.js
  test/public/runs/runsPerDataPass.overview.test.js
  test/public/runs/runsPerSimulationPass.overview.test.js
Labels: backend

#1569 [O2B-1153] Handle repeated fields in proto files
  lib/server/controllers/gRPC/GRPCEnvironmentController.js
  lib/server/controllers/gRPC/GRPCRunController.js
  lib/server/gRPC/bindGRPCController.js
  lib/server/gRPC/services/protoParsing/extractFieldsConverters.js
  proto/environment.proto
  test/gRPC/extractFieldConverters.test.js
  test/gRPC/proto/main.proto
  test/gRPC/serviceImplementation.test.js
Labels: backend

#1530 [O2B-1010] Hide protobuf dependency from the c++ library
  cxx-client/CMakeLists.txt
  cxx-client/cmake/BookkeepingProtoApiConfig.cmake.in
  cxx-client/example/exampleProtoServices.cxx
  cxx-client/include/BookkeepingApi/BkpProtoClient.h
  cxx-client/include/BookkeepingApi/BkpProtoClientFactory.h
  cxx-client/include/BookkeepingApi/DplProcessExecutionProtoClient.h
  cxx-client/include/BookkeepingApi/RunProtoClient.h
  cxx-client/src/BkpProtoClientFactory.cxx
  cxx-client/src/grpc/GrpcBkpProtoClient.cxx
  cxx-client/src/grpc/GrpcBkpProtoClient.h
  cxx-client/src/grpc/services/GrpcDplProcessExecutionProtoClient.cxx
  cxx-client/src/grpc/services/GrpcDplProcessExecutionProtoClient.h
  cxx-client/src/grpc/services/GrpcRunProtoClient.cxx
  cxx-client/src/grpc/services/GrpcRunProtoClient.h
Labels: backend

#1551 [O2B-1153] Implement QC flags gRPC API
  cxx-client/CMakeLists.txt
  lib/server/controllers/gRPC/GRPCQcFlagController.js
  lib/server/gRPC/servicesImplementationsMappings.js
  proto/qcFlag.proto
Labels: backend

#1559 [O2B-1241] RCT Runs overviews filtering
  lib/public/components/Filters/common/filtersPanelPopover.js
  lib/public/components/common/table/noDataRow.js
  lib/public/components/common/table/table.js
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
  lib/public/views/Runs/RunPerDataPass/RunsPerDataPassOverviewPage.js
  test/public/defaults.js
  test/public/runs/runsPerDataPass.overview.test.js
Labels: frontend

#1571 Release 0.89.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#1573 [O2B-1270] Fix environment update gRPC API
  lib/database/adapters/RunAdapter.js
  lib/server/controllers/gRPC/GRPCEnvironmentController.js
  lib/server/controllers/gRPC/GRPCRunController.js
  lib/server/services/environment/EnvironmentService.js
Labels: bug, backend

#1574 Release 0.89.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#1575 [O2B-1270] Handle properly nullable numbers from protobuf
  lib/server/controllers/gRPC/GRPCEnvironmentController.js
  lib/server/controllers/gRPC/GRPCQcFlagController.js
  proto/qcFlag.proto
Labels: bug, backend

#1578 Release 0.89.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#1563 [O2B-1262] Removed suite dependencies from the LhcFillsSuite suite
  test/public/about/overview.test.js
  test/public/dataPasses/overviewPerLhcPeriod.test.js
  test/public/dataPasses/overviewPerSimulationPass.test.js
  test/public/defaults.js
  test/public/envs/overview.test.js
  test/public/flps/detail.test.js
  test/public/flps/overview.test.js
  test/public/lhcFills/detail.test.js
  test/public/lhcFills/overview.test.js
  test/public/lhcPeriods/overview.test.js
  test/public/logs/create.test.js
  test/public/logs/detail.test.js
  test/public/logs/overview.test.js
  test/public/qcFlagTypes/creation.test.js
  test/public/qcFlagTypes/overview.test.js
  test/public/qcFlags/detailsForDataPass.test.js
  test/public/qcFlags/detailsForSimulationPass.test.js
  test/public/qcFlags/forDataPassCreation.test.js
  test/public/qcFlags/forDataPassOverview.test.js
  test/public/qcFlags/forSimulationPassCreation.test.js
  test/public/qcFlags/forSimulationPassOverview.test.js
  test/public/runs/detail.test.js
  test/public/runs/overview.test.js
  test/public/runs/runsPerDataPass.overview.test.js
  test/public/runs/runsPerPeriod.overview.test.js
  test/public/runs/runsPerSimulationPass.overview.test.js
  test/public/simulationPasses/overviewAnchoredSimulationPasses.test.js
  test/public/simulationPasses/overviewPerLhcPeriod.test.js
  test/public/subsystems/detail.test.js
  test/public/subsystems/overview.test.js
  test/public/tags/create.test.js
  test/public/tags/detail.test.js
  test/public/tags/overview.test.js
Labels: bug

#1583 [O2B-1279] time-out increased to 20 minutes
  .github/workflows/bookkeeping.yml
Labels: CI, github_actions

#1564 [O2B-1228] Improve magnets transitions in RC daily meeting log template
  lib/public/components/common/form/inputs/TimestampInputComponent.js
  lib/public/components/common/form/magnetsConfiguration/AliceMagnetsConfigurationSnapshotsForm.js
  lib/public/components/common/form/magnetsConfiguration/aliceMagnetsConfigurationsSnapshotsForm.js
  lib/public/views/Logs/Create/templates/RcDailyMeetingTemplate.js
  lib/server/services/eosReport/EosReportService.js
  lib/server/services/eosReport/eosTypeSpecificFormatter/formatShiftLeaderEosReportTypeSpecific.js
  test/mocks/mock-shift-leader-eos-report.js
  test/public/defaults.js
  test/public/eosReport/shift-leader-creation.test.js
  test/public/logs/create.test.js
Labels: frontend

#1588 Ignore eslint major upgrade in dependabot
  .github/dependabot.yml
Labels: dependencies

#1517 [O2B-1013] Added description to render tooltip on tag badges
  lib/public/views/Runs/Details/runDetailsConfiguration.js
  lib/public/views/Tags/format/formatTagsList.js
Labels: frontend
