Repository AliceO2Group/Bookkeeping, pull requests merged in 2024-09, with the labels that each got.

#1733 [O2B-1347] API for filtering by GAQ not bad data fraction
  lib/domain/dtos/filters/RunFilterDto.js
  lib/usecases/run/GetAllRunsUseCase.js
  test/api/runs.test.js
  test/lib/usecases/run/GetAllRunsUseCase.test.js
  test/public/runs/runsPerDataPass.overview.test.js
Labels: frontend, backend

#1743 [O2B-1356] Synchronous QC flags overview
  lib/public/Model.js
  lib/public/components/qcFlags/qcFlagsBreadcrumbs.js
  lib/public/components/qcFlags/qcFlagsPagesButtons.js
  lib/public/view.js
  lib/public/views/QcFlags/QcFlagsModel.js
  lib/public/views/QcFlags/Synchronous/SynchronousQcFlagsOverviewModel.js
  lib/public/views/QcFlags/Synchronous/SynchronousQcFlagsOverviewPage.js
  lib/public/views/Runs/ActiveColumns/runDetectorsSyncQcActiveColumns.js
  test/public/qcFlags/index.js
  test/public/qcFlags/synchronousOverview.test.js
  test/scripts/test-qc-flags.js
Labels: frontend

#1746 [O2B-1370] Store delivered lumi and colliding bunches per fill
  lib/database/adapters/LhcFillAdapter.js
  lib/database/migrations/20240902080430-add-fill-colliding-bunch-and-lumi.js
  lib/database/models/lhcFill.js
  lib/database/models/typedefs/SequelizeLhcFill.js
  lib/domain/dtos/UpdateLhcFillDto.js
  lib/domain/entities/LhcFill.js
  lib/server/controllers/lhcFill.controller.js
  lib/usecases/lhcFill/UpdateLhcFillUseCase.js
  test/api/lhcFills.test.js
  test/lib/usecases/lhcFill/UpdateLhcFillUseCase.test.js
Labels: backend

#1739 [O2B-1321] Fix formatting of TF
  lib/public/views/Runs/Details/runDetailsConfiguration.js
Labels: frontend

#1737 [O2B-1366] Extract user that start/stop runs from kafka message
  lib/server/kafka/AliEcsSynchronizer.js
Labels: backend

#1748 [O2B-1371] Store FLP from ECS kafka
  lib/server/services/run/RunService.js
Labels: bug, backend

#1750 Release 0.99.0
  CHANGELOG.md
  database/CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#1754 Fix condition in ML synchronizer
  lib/server/monalisa-synchronization/MonAlisaSynchronizer.js
Labels: bug, backend

#1753 [O2B-955] Use proper detector label to detect detector EoR reason
  lib/server/services/run/RunService.js
Labels: bug, backend

#1756 Release 0.99.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#1734 [O2B-1347] Filtering by GAQ not bad percentage
  lib/public/views/Runs/RunPerDataPass/RunsPerDataPassOverviewModel.js
  lib/public/views/Runs/RunPerDataPass/RunsPerDataPassOverviewPage.js
  test/public/runs/runsPerDataPass.overview.test.js
Labels: frontend

#1763 [O2B-831] Remove failing alpine package in dockerfile
  Dockerfile
Labels: dependencies, docker

#1765 [O2B-1381] Fix stable beams start/stop/duration typo (singular beam)
  CHANGELOG.md
  lib/server/services/run/getRunDefinition.js
  proto/common.proto
  test/lib/usecases/lhcFill/GetAllLhcFillsUseCase.test.js
Labels: backend

#1760 [O2B-1380] Add DONE environment status to the ones that closes environments
  lib/database/seeders/20230124105627-environment-history.js
  lib/server/services/environment/getEnvironmentsInPeriod.js
  test/lib/server/services/environment/getEnvironmentsInPeriod.test.js
Labels: backend

#1761 [O2B-1373] Extract run type and nEPNs from environment configuration
  lib/database/seeders/20220412122043-environments.js
  lib/server/controllers/gRPC/GRPCRunController.js
  lib/server/services/run/RunService.js
  test/lib/server/services/run/RunService.test.js
Labels: bug, backend

#1757 [O2B-1377] Store XSection, TRG efficiency and acceptance and phase shifts per run
  lib/database/adapters/RunAdapter.js
  lib/database/migrations/20240909074525-store-xsection-efficiency-acceptance-and-phase-shift-per-run.js
  lib/database/models/run.js
  lib/database/models/typedefs/SequelizeRun.js
  lib/database/seeders/20200713103855-runs.js
  lib/domain/dtos/UpdateRunByRunNumberDto.js
  lib/domain/entities/Run.js
  test/api/runs.test.js
  test/lib/server/services/run/RunService.test.js
  test/lib/usecases/run/UpdateRunUseCase.test.js
Labels: backend

#1766 Release 1.0.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#1770 Release 1.0.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#1772 [O2B-1377] Store phase shift for beam 1 and 2
  lib/database/adapters/RunAdapter.js
  lib/database/migrations/20240930082704-update-run-phase-shift.js
  lib/database/models/run.js
  lib/database/models/typedefs/SequelizeRun.js
  lib/database/seeders/20200713103855-runs.js
  lib/domain/dtos/UpdateRunByRunNumberDto.js
  lib/domain/entities/Run.js
  lib/usecases/run/UpdateRunUseCase.js
  test/api/runs.test.js
  test/lib/server/services/run/RunService.test.js
  test/lib/usecases/run/UpdateRunUseCase.test.js
Labels: bug
