Repository AliceO2Group/Bookkeeping, pull requests merged in 2024-06, with the labels that each got.

#1576 [O2B-1271] Store QC flags' origin from gRPC messages
  lib/database/adapters/QcFlagAdapter.js
  lib/database/migrations/20240528092020-add-qc-flag-origin-column.js
  lib/database/models/qcFlag.js
  lib/database/models/typedefs/SequelizeQcFlag.js
  lib/domain/entities/DataPassQcFlag.js
  lib/domain/entities/QcFlag.js
  lib/domain/entities/SimulationPassQcFlag.js
  lib/public/components/qcFlags/qcFlagTypeColoredBadge.js
  lib/public/components/qcFlags/qcFlagTypesSelectionDropdownModel.js
  lib/public/views/QcFlagTypes/ActiveColumns/qcFlagTypesActiveColumns.js
  lib/public/views/QcFlags/ActiveColumns/qcFlagsActiveColumns.js
  lib/public/views/QcFlags/details/qcFlagDetailsConfiguration.js
  lib/public/views/QcFlags/format/formatQcFlagCreatedBy.js
  lib/server/services/qualityControlFlag/QcFlagService.js
  test/api/qcFlags.test.js
  test/lib/server/services/qualityControlFlag/QcFlagService.test.js
Labels: frontend, backend

#1570 [O2B-1203] Require expert roles in QC flags management
  lib/public/Model.js
  lib/public/components/NavBar/index.js
  lib/public/components/qcFlags/qcFlagsPagesButtons.js
  lib/public/models/UserRoleSelectionModel.js
  lib/public/utilities/getRoleForDetector.js
  lib/server/WebUiServer.js
  lib/server/controllers/gRPC/GRPCQcFlagController.js
  lib/server/controllers/qcFlag.controller.js
  lib/server/services/qualityControlFlag/QcFlagService.js
  test/api/qcFlags.test.js
  test/lib/server/services/qualityControlFlag/QcFlagService.test.js
  test/public/flps/overview.test.js
  test/public/qcFlags/forDataPassCreation.test.js
  test/public/qcFlags/forSimulationPassCreation.test.js
  test/public/runs/runsPerDataPass.overview.test.js
  test/public/runs/runsPerSimulationPass.overview.test.js
  test/public/tags/create.test.js
Labels: backend

#1581 [O2B-1273] Verification by the same person
  lib/public/views/QcFlags/details/qcFlagDetailsComponent.js
  lib/server/services/qualityControlFlag/QcFlagService.js
  test/api/qcFlags.test.js
  test/lib/server/services/qualityControlFlag/QcFlagService.test.js
  test/public/defaults.js
  test/public/qcFlags/detailsForDataPass.test.js
  test/public/qcFlags/detailsForSimulationPass.test.js
Labels: frontend, backend

#1579 [O2B-1252] Display expected unit in duration filter
  lib/public/components/Filters/common/filtersPanelPopover.js
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
Labels: frontend

#1585 [O2B-1010] Remove proto-based API from readme
  cxx-client/README.md
Labels: documentation

#1473 [O2B-1202] Fix missing current environment state on overview page
  lib/public/components/environments/environmentStatusHistoryComponent.js
  lib/public/domain/enums/statusAcronym.mjs
  lib/public/views/Environments/ActiveColumns/environmentsActiveColumns.js
  lib/public/views/Environments/ColoredEnvironmentStatusComponent.js
  lib/public/views/Environments/format/displayEnvironmentStatus.js
  lib/public/views/Statistics/charts/environmentHistoryOccurrencesBarChartComponent.js
  lib/usecases/environment/GetAllEnvironmentsUseCase.js
  test/public/defaults.js
  test/public/envs/overview.test.js
  test/public/runs/overview.test.js
Labels: frontend

#1594 [O2B-1280] Create trigger counters fetch endpoints
  lib/database/adapters/TriggerCountersAdapter.js
  lib/database/adapters/index.js
  lib/database/migrations/20240603082112-create-trigger-counters.js
  lib/database/models/index.js
  lib/database/models/triggerCounters.js
  lib/database/models/typedefs/SequelizeTriggerCounters.js
  lib/database/repositories/TriggerCountersRepository.js
  lib/database/repositories/index.js
  lib/database/seeders/20240603124221-add-trigger-counters.js
  lib/domain/entities/TriggerCounters.js
  lib/server/controllers/index.js
  lib/server/controllers/triggerCounters.controller.js
  lib/server/routers/index.js
  lib/server/routers/triggerCounters.router.js
  lib/server/services/triggerCounters/TriggerCountersService.js
  test/api/index.js
  test/api/triggerCounters.test.js
  test/lib/server/services/index.js
  test/lib/server/services/triggerCounters/TriggerCountersService.test.js
  test/lib/server/services/triggerCounters/index.js
Labels: backend

#1597 Release 0.90.0
  CHANGELOG.md
  database/CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#1599 Several tests improvements
  lib/public/components/NavBar/index.js
  lib/public/views/QcFlags/Create/forDataPass/QcFlagCreationForDataPassPage.js
  lib/public/views/QcFlags/Create/forSimulationPass/QcFlagCreationForSimulationPassPage.js
  test/public/about/overview.test.js
  test/public/dataPasses/overviewPerLhcPeriod.test.js
  test/public/dataPasses/overviewPerSimulationPass.test.js
  test/public/defaults.js
  test/public/envs/detailsPage.test.js
  test/public/envs/overview.test.js
  test/public/eosReport/dcs-creation.test.js
  test/public/eosReport/ecs-creation.test.js
  test/public/eosReport/qc-pdp-creation.test.js
  test/public/eosReport/shift-leader-creation.test.js
  test/public/eosReport/slimos-creation.test.js
  test/public/flps/detail.test.js
  test/public/flps/overview.test.js
  test/public/home/overview.test.js
  test/public/lhcFills/detail.test.js
  test/public/lhcFills/overview.test.js
  test/public/lhcPeriods/overview.test.js
  test/public/logs/create.test.js
  test/public/logs/detail.test.js
  test/public/logs/overview.test.js
  test/public/qcFlagTypes/creation.test.js
  test/public/qcFlagTypes/overview.test.js
  test/public/qcFlags/detailsForDataPass.test.js
  test/public/qcFlags/detailsForSimulationPass.test.js
  test/public/qcFlags/forDataPassCreation.test.js
  test/public/qcFlags/forDataPassOverview.test.js
  test/public/qcFlags/forSimulationPassCreation.test.js
  test/public/qcFlags/forSimulationPassOverview.test.js
  test/public/runs/detail.test.js
  test/public/runs/overview.test.js
  test/public/runs/runsPerDataPass.overview.test.js
  test/public/runs/runsPerPeriod.overview.test.js
  test/public/runs/runsPerSimulationPass.overview.test.js
  test/public/simulationPasses/overviewAnchoredSimulationPasses.test.js
  test/public/simulationPasses/overviewPerLhcPeriod.test.js
  test/public/subsystems/detail.test.js
  test/public/subsystems/overview.test.js
  test/public/tags/create.test.js
  test/public/tags/detail.test.js
  test/public/tags/overview.test.js
Labels: frontend

#1602 [O2B-1281] Display trigger counters in run details
  lib/public/components/common/panel/PanelComponent.js
  lib/public/views/QcFlags/Create/qcFlagCreationComponent.js
  lib/public/views/Runs/Details/RunDetailsModel.js
  lib/public/views/Runs/Details/runDetailsComponent.js
  test/public/defaults.js
  test/public/qcFlags/forDataPassCreation.test.js
  test/public/qcFlags/forSimulationPassCreation.test.js
  test/public/runs/detail.test.js
  test/public/runs/runsPerPeriod.overview.test.js
Labels: frontend

#1606 [O2B-1282] Add gRPC interface for trigger counters create/update
  lib/domain/entities/TriggerCounters.js
  lib/server/controllers/gRPC/GRPCTriggerCountersController.js
  lib/server/gRPC/servicesImplementationsMappings.js
  lib/server/services/triggerCounters/TriggerCountersService.js
  proto/common.proto
  proto/triggerCounters.proto
  test/lib/server/services/triggerCounters/TriggerCountersService.test.js
  test/public/runs/runsPerDataPass.overview.test.js
Labels: backend

#1608 Release 0.91.0
  CHANGELOG.md
  database/CHANGELOG.md
  package-lock.json
  package.json
Labels: frontend

#1613 Fix QC flag effective periods creation corner case and failing test
  lib/server/services/qualityControlFlag/QcFlagService.js
  test/lib/server/services/qualityControlFlag/QcFlagService.test.js
Labels: backend

#1611 [O2B-1296] Fix data pass name usage in QC flags GRPC controller
  lib/server/controllers/gRPC/GRPCQcFlagController.js
  lib/server/services/dataPasses/DataPassService.js
Labels: backend

#1598 [O2B-1077] Fix again: keep scroll in popover
  lib/public/components/Filters/common/filtersPanelPopover.js
  lib/public/components/common/popover/PopoverEngine.js
  lib/public/components/common/popover/dropdown.js
  lib/public/components/common/popover/popover.js
  lib/public/views/Logs/Create/logCreationComponent.js
  lib/public/views/Logs/FilePreview/attachmentPreviewComponent.js
  lib/public/views/Logs/FilePreview/filePreviewComponent.js
  lib/public/views/Runs/format/formatRunDetectors.js
  test/public/dataPasses/overviewPerLhcPeriod.test.js
  test/public/dataPasses/overviewPerSimulationPass.test.js
  test/public/lhcPeriods/overview.test.js
  test/public/logs/overview.test.js
  test/public/qcFlagTypes/overview.test.js
  test/public/qcFlags/forDataPassCreation.test.js
  test/public/qcFlags/forSimulationPassCreation.test.js
  test/public/runs/overview.test.js
Labels: bug, frontend

#1618 release/0.92.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#1625 [O2B-1077] Several fixes in popover system
  lib/public/components/common/popover/PopoverEngine.js
  lib/public/components/common/popover/popover.js
Labels: bug, frontend

#1620 [O2B-1301] Disable QC for Not_for_physics runs
  lib/public/components/qcFlags/badRunInAsyncQcMessage.js
  lib/public/components/qcFlags/isRunSubjectToQc.js
  lib/public/components/qcFlags/qcFlagsPagesButtons.js
  lib/public/views/QcFlags/Create/qcFlagCreationComponent.js
  lib/public/views/Runs/ActiveColumns/runDetectorsAsyncQcActiveColumns.js
  lib/public/views/Runs/RunPerDataPass/RunsPerDataPassOverviewPage.js
  lib/public/views/Runs/RunPerPeriod/RunsPerLhcPeriodOverviewPage.js
  lib/public/views/Runs/RunsPerSimulationPass/RunsPerSimulationPassOverviewPage.js
Labels: frontend

#1632 Remove default URLs from services config
  docker-compose.yml
  lib/config/services.js
Labels: backend

#1626 [O2B-1302] Display run period in fill display
  lib/server/controllers/lhcFill.controller.js
  lib/server/controllers/runs.controller.js
  lib/server/controllers/runsToHttpView.js
  lib/server/services/lhcFill/LhcFillService.js
  test/api/lhcFills.test.js
  test/lib/server/services/lhcFill/LhcFillService.test.js
  test/lib/usecases/lhcFill/GetLhcFillUseCase.test.js
Labels: bug, frontend

#1623 [O2B-1229] Improve runs to check display in RC daily meeting template
  lib/public/services/detectors/detectorsProvider.js
  lib/public/views/Logs/Create/templates/RcDailyMeetingTemplate.js
  lib/public/views/Logs/Create/templates/rcDailyMeetingConfiguration.js
Labels: frontend

#1634 [O2B-1230] Exclude EoS report from RC daily meeting minutes template logs
  lib/public/views/Logs/Create/templates/RcDailyMeetingTemplate.js
Labels: frontend

#1566 [O2B-1241] Add filtering by Alice L3/dipole Current
  lib/database/seeders/20200713103855-runs.js
  lib/domain/dtos/filters/RunFilterDto.js
  lib/public/components/Filters/RunsFilter/AliceL3AndDipoleFilteringModel.js
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
  lib/public/views/Runs/Overview/RunsOverviewModel.js
  lib/server/controllers/lhcFill.controller.js
  lib/server/controllers/runs.controller.js
  lib/server/routers/runs.router.js
  lib/server/services/run/RunService.js
  lib/usecases/run/GetAllRunsUseCase.js
  test/api/runs.test.js
  test/lib/server/services/run/RunService.test.js
  test/lib/usecases/run/GetAllRunsUseCase.test.js
  test/public/defaults.js
  test/public/runs/runsPerDataPass.overview.test.js
Labels: backend

#1635 [O2B-1283] Create cxx client for trigger counters
  cxx-client/CMakeLists.txt
  cxx-client/example/exampleSpecificServices.cxx
  cxx-client/include/BookkeepingApi/BkpClient.h
  cxx-client/include/BookkeepingApi/TriggerCountersServiceClient.h
  cxx-client/src/grpc/GrpcBkpClient.cxx
  cxx-client/src/grpc/GrpcBkpClient.h
  cxx-client/src/grpc/services/GrpcQcFlagServiceClient.cxx
  cxx-client/src/grpc/services/GrpcQcFlagServiceClient.h
  cxx-client/src/grpc/services/GrpcTriggerCountersServiceClient.cxx
  cxx-client/src/grpc/services/GrpcTriggerCountersServiceClient.h
Labels: backend

#1636 Release 0.93.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release
