Repository AliceO2Group/Bookkeeping, pull requests merged in 2024-03, with the labels that each got.

#1367 [O2B-1133] Implement Simulation Passes per LHC Period view
  lib/public/Model.js
  lib/public/components/common/navigation/breadcrumbs.js
  lib/public/utilities/formatting/formatItemsCount.js
  lib/public/utilities/formatting/formatSizeInBytes.js
  lib/public/view.js
  lib/public/views/DataPasses/ActiveColumns/dataPassesActiveColumns.js
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
  lib/public/views/SimulationPasses/ActiveColumns/simulationPassesActiveColumns.js
  lib/public/views/SimulationPasses/PerLhcPeriodOverview/SimulationPassesPerLhcPeriodOverviewModel.js
  lib/public/views/SimulationPasses/PerLhcPeriodOverview/SimulationPassesPerLhcPeriodOverviewPage.js
  lib/public/views/SimulationPasses/SimulationPassesModel.js
  lib/public/views/lhcPeriods/ActiveColumns/lhcPeriodsActiveColumns.js
  test/public/defaults.js
  test/public/index.js
  test/public/lhcPeriods/overview.test.js
  test/public/simulationPasses/index.js
  test/public/simulationPasses/overviewPerLhcPeriod.test.js
Labels: frontend

#1423 [O2B-905] Add endpoint to fetch all replies to a given log using its id
  lib/server/controllers/logs.controller.js
  lib/server/routers/logs.router.js
  lib/server/services/log/LogService.js
  test/api/logs.test.js
  test/lib/server/services/log/LogService.test.js
Labels: backend

#1427 [O2B-1173] Remove TST detector from RCT views
  lib/public/services/detectors/detectorsProvider.js
  lib/public/views/Runs/RunPerDataPass/RunsPerDataPassOverviewModel.js
  lib/public/views/Runs/RunPerPeriod/RunsPerLhcPeriodOverviewModel.js
  test/public/runs/runsPerDataPass.overview.test.js
  test/public/runs/runsPerPeriod.overview.test.js
Labels: frontend

#1413 [O2B-1162] Display all PHYSICS runs on Data Pass view
  lib/public/components/Log/logDisplayComponent.js
  lib/public/components/environments/environmentStatusHistoryComponent.js
  lib/public/views/Environments/ActiveColumns/environmentsActiveColumns.js
  lib/public/views/Logs/Create/logCreationComponent.js
  lib/public/views/Runs/RunPerDataPass/RunsPerDataPassOverviewModel.js
  lib/public/views/Runs/RunPerDataPass/RunsPerDataPassOverviewPage.js
  lib/public/views/Runs/format/displayRunEorReasonOverview.js
  test/public/runs/runsPerDataPass.overview.test.js
Labels: frontend

#1409 [O2B-1151] Auto-fill tags in on-call log template
  lib/database/seeders/20200511151010-tags.js
  lib/public/components/Filters/common/combinationOperatorChoiceComponent.js
  lib/public/components/common/selection/SelectionModel.js
  lib/public/components/common/selection/dropdown/SelectionDropdownModel.js
  lib/public/components/common/selection/picker/PickerModel.js
  lib/public/components/common/selection/picker/picker.js
  lib/public/components/detector/DetectorSelectionDropdownModel.js
  lib/public/components/runTypes/RunTypesSelectionDropdownModel.js
  lib/public/components/tag/TagPickerModel.js
  lib/public/components/tag/TagSelectionDropdownModel.js
  lib/public/components/tag/tagPicker.js
  lib/public/views/Logs/Create/OnCallLogTemplate.js
  lib/public/views/Logs/Create/TemplatedLogCreationModel.js
  lib/public/views/Logs/Create/logCreationComponent.js
  lib/public/views/Runs/Details/editTagsPanel.js
  test/api/tags.test.js
  test/lib/usecases/tag/GetAllTagsUseCase.test.js
  test/public/logs/create.test.js
  test/public/tags/overview.test.js
Labels: frontend

#1437 Release 0.80.0
  CHANGELOG.md
  database/CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#1432 [O2B-1176] Add LHC fills statistics back to LHC fills overview
  lib/public/views/LhcFills/Overview/LhcFillsOverviewModel.js
  test/public/lhcFills/overview.test.js
Labels: bug, frontend

#1439 [O2B-1169] Fix detectors efficiency statistics tab
  lib/public/views/Statistics/StatisticsPageModel.js
Labels: bug, frontend

#1444 [O2B-1166] Environments added to eos reports
  lib/server/services/eosReport/EosReportService.js
  test/lib/server/services/eosReport/EosReportService.test.js
  test/mocks/mock-qc-pdp-eos-report.js
  test/mocks/mock-shift-leader-eos-report.js
Labels: javascript

#1429 [O2B-1175] Add simulation passes counts to LHC Periods page
  lib/database/adapters/LhcPeriodStatisticsAdapter.js
  lib/database/models/typedefs/SequelizeLhcPeriodStatistics.js
  lib/domain/entities/LhcPeriod.js
  lib/domain/entities/LhcPeriodStatistics.js
  lib/public/views/lhcPeriods/ActiveColumns/lhcPeriodsActiveColumns.js
  lib/server/services/lhcPeriod/LhcPeriodStatisticsService.js
  test/api/lhcPeriodsStatistics.test.js
  test/lib/server/services/lhcPeriod/LhcPeriodStatisticsService.test.js
  test/public/lhcPeriods/overview.test.js
Labels: frontend, backend

#1426 [O2B-1174] Add get all DPL Detectors endpoint
  lib/server/controllers/dplDetectors.controller.js
  lib/server/routers/dplDetectors.router.js
  lib/server/routers/index.js
  lib/server/services/dpl/DplDetectorsService.js
  test/api/dplDetectors.test.js
  test/api/index.js
  test/lib/server/services/dpl/DplDetectorsService.test.js
  test/lib/server/services/dpl/index.js
Labels: backend

#1438 [O2B-953] Log Creation input fields autofill when needed
  lib/public/views/Environments/Details/EnvironmentDetailsPage.js
  lib/public/views/Logs/LogsModel.js
  lib/public/views/Runs/Details/runDetailsComponent.js
  test/public/envs/detailsPage.test.js
  test/public/logs/create.test.js
  test/public/runs/detail.test.js
Labels: frontend

#1451 [O2B-1181] Add easy to reach no-anonymous toggle
  lib/public/Model.js
  lib/public/components/Filters/LogsFilter/author/AuthorFilterModel.js
  lib/public/components/Filters/LogsFilter/author/authorFilter.js
  lib/public/views/Logs/Overview/index.js
Labels: frontend

#1370 [O2B-1125] Implement Simulation Passes per Data Pass view
  lib/public/Model.js
  lib/public/view.js
  lib/public/views/DataPasses/ActiveColumns/dataPassesActiveColumns.js
  lib/public/views/SimulationPasses/AnchoredOverview/AnchoredSimulationPassesOverviewModel.js
  lib/public/views/SimulationPasses/AnchoredOverview/AnchoredSimulationPassesOverviewPage.js
  lib/public/views/SimulationPasses/SimulationPassesModel.js
  test/public/dataPasses/overviewPerLhcPeriod.test.js
  test/public/defaults.js
  test/public/simulationPasses/index.js
  test/public/simulationPasses/overviewAnchoredSimulationPasses.test.js
Labels: frontend

#1450 [O2B-1140] Extract ALICE magnets configuration snapshot form component
  lib/domain/dtos/eosReport/CreateEosReportDto.js
  lib/public/components/common/form/inputs/DateTimeInputComponent.js
  lib/public/components/common/form/inputs/DateTimeInputModel.js
  lib/public/components/common/form/inputs/TimestampInputComponent.js
  lib/public/components/common/form/magnetsConfiguration/AliceMagnetsConfigurationSnapshotsForm.js
  lib/public/components/common/form/magnetsConfiguration/aliceMagnetsConfigurationsSnapshotsForm.js
  lib/public/utilities/formatting/dateTimeInputFormatters.mjs
  lib/public/views/EosReport/create/EosReportCreationModel.js
  lib/public/views/EosReport/create/typeSpecific/eosFormShiftLeaderSpecificPart.js
  lib/server/services/eosReport/EosReportService.js
  lib/server/services/eosReport/eosTypeSpecificFormatter/formatShiftLeaderEosReportTypeSpecific.js
  test/mocks/mock-shift-leader-eos-report.js
  test/public/eosReport/shift-leader-creation.test.js
Labels: frontend

#1440 [O2B-1170] Remove title from table cells
  lib/public/components/common/table/rows.js
  lib/public/views/Environments/ActiveColumns/environmentsActiveColumns.js
  lib/public/views/LhcFills/ActiveColumns/lhcFillsActiveColumns.js
Labels: bug, frontend

#1452 [O2B-1180] Add first&last pages links
  lib/public/components/Pagination/pageSelector.js
Labels: frontend

#1454 [O2B-1140] Fix time range input when granularity is minutes
  lib/public/components/common/form/inputs/DateTimeInputComponent.js
  lib/public/components/common/form/inputs/DateTimeInputModel.js
  lib/public/utilities/formatting/dateTimeInputFormatters.mjs
  test/public/eosReport/shift-leader-creation.test.js
Labels: bug, frontend

#1455 [O2B-1193] - Runs Per LHC Period export bugfix
  lib/public/views/Runs/Overview/RunsOverviewModel.js
  test/public/runs/runsPerPeriod.overview.test.js
  test/utilities/waitForDownload.js
Labels: bug, frontend

#1453 Release 0.81.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#1380 [O2B-1118] Add migration files and models for quality control flag types
  lib/database/migrations/20240226102034-create-quality-control-flags-tables.js
  lib/database/models/index.js
  lib/database/models/qcFlagType.js
  lib/database/models/typedefs/SequelizeQCFlagType.js
  lib/database/seeders/20240213120811-quality-control-flags.js
Labels: backend, DB

#1459 Fix message format in tests
  test/utilities/waitForDownload.js
Labels: bug

#1461 [O2B-1188] Remove `info` level form infologger links
  lib/public/services/externalRouting/getInfologgerLinksUrls.js
Labels: javascript

#1460 [O2B-1140] Use observable data for detector provider
  lib/public/components/detector/DetectorSelectionDropdownModel.js
  lib/public/services/detectors/detectorsProvider.js
  lib/public/utilities/ObservableData.js
  lib/public/views/Logs/Create/OnCallLogTemplate.js
  lib/public/views/Runs/Details/RunDetailsModel.js
  lib/public/views/Runs/RunPerDataPass/RunsPerDataPassOverviewModel.js
  lib/public/views/Runs/RunPerPeriod/RunsPerLhcPeriodOverviewModel.js
Labels: frontend

#1466 [O2B-1196] Add formatting to Data Passes view
  lib/public/views/DataPasses/ActiveColumns/dataPassesActiveColumns.js
  test/public/dataPasses/overviewPerLhcPeriod.test.js
Labels: frontend

#1441 [O2B-1183] Add QC flag types fetching by id endpoint
  lib/database/adapters/QcFlagTypeAdapter.js
  lib/database/adapters/index.js
  lib/database/models/index.js
  lib/database/models/qcFlagType.js
  lib/database/models/typedefs/SequelizeQcFlagType.js
  lib/database/repositories/QcFlagTypeRepository.js
  lib/database/repositories/index.js
  lib/domain/entities/qcFlagType.js
  lib/server/controllers/qcFlagTypes.controller.js
  lib/server/routers/index.js
  lib/server/routers/qcFlagTypes.router.js
  lib/server/services/qualityControlFlag/QcFlagTypeService.js
  test/api/index.js
  test/api/qcFlagTypes.test.js
  test/lib/server/services/index.js
  test/lib/server/services/qualityControlFlag/QcFlagTypeService.test.js
  test/lib/server/services/qualityControlFlag/index.js
Labels: backend

#1470 Update docker dependencies
  Dockerfile
Labels: docker

#1472 [O2B-1201] Extract lhcPeriod from patch and not relations
  lib/server/controllers/gRPC/GRPCRunController.js
Labels: bug, backend

#1458 [O2B-1183] Add QC flag types fetch all endpoint
  lib/database/seeders/20240213120811-quality-control-flags.js
  lib/server/controllers/qcFlagTypes.controller.js
  lib/server/routers/qcFlagTypes.router.js
  lib/server/services/qualityControlFlag/QcFlagTypeService.js
  test/api/qcFlagTypes.test.js
  test/lib/server/services/qualityControlFlag/QcFlagTypeService.test.js
Labels: backend

#1477 [O2B-1181] Add tests for no-anonymous logs toggle
  lib/database/seeders/20200508094502-logs.js
  lib/public/components/common/table/rows.js
  lib/public/views/Logs/Overview/index.js
  test/lib/server/services/log/getLogsByUserInPeriod.test.js
  test/public/dataPasses/overviewPerLhcPeriod.test.js
  test/public/defaults.js
  test/public/lhcPeriods/overview.test.js
  test/public/logs/overview.test.js
  test/public/simulationPasses/overviewAnchoredSimulationPasses.test.js
  test/public/simulationPasses/overviewPerLhcPeriod.test.js
Labels: frontend

#1465 [O2B-1195] Don't transition runs & envs created less than 30s ago
  lib/server/services/environment/transitionToErrorLostEnvironments.js
  lib/server/services/housekeeping/handleLostRunsAndEnvironments.js
  lib/server/services/run/setO2StopOfLostRuns.js
Labels: backend

#1479 Release 0.82.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#1436 [O2B-1178] Add counts of anchored simulation passes
  lib/database/adapters/DataPassAdapter.js
  lib/database/models/typedefs/SequelizeDataPass.js
  lib/domain/entities/DataPass.js
  lib/public/views/DataPasses/ActiveColumns/dataPassesActiveColumns.js
  lib/server/services/dataPasses/DataPassService.js
  test/api/dataPasses.test.js
  test/lib/server/services/dataPasses/DataPassesService.test.js
  test/public/dataPasses/overviewPerLhcPeriod.test.js
  test/public/defaults.js
Labels: frontend, backend
