Repository AliceO2Group/Bookkeeping, pull requests merged in 2024-12, with the labels that each got.

#1806 [O2B-1366] Fixed user starting/stopping runs not being properly extracted
  lib/server/kafka/AliEcsSynchronizer.js
  lib/server/services/run/RunService.js
  lib/server/services/user/UserService.js
  test/lib/server/services/run/RunService.test.js
Labels: frontend, backend

#1800 [O2B-1402] Fix TF timestamps being ignored when creating QC flags
  lib/database/seeders/20200713103855-runs.js
  lib/database/seeders/20221006084006-run-detectors.js
  lib/server/controllers/gRPC/GRPCFlpRoleController.js
  lib/server/services/qualityControlFlag/QcFlagService.js
  lib/server/services/run/RunService.js
  test/lib/server/services/qualityControlFlag/QcFlagService.test.js
Labels: bug, backend

#1803 [O2B-844] Filter according to B field in runs
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
  package-lock.json
  test/public/runs/overview.test.js
Labels: frontend, javascript

#1815 Attempt at fixing FLP randomly failing tests
  lib/public/components/Pagination/amountSelector.js
  test/public/flps/index.js
  test/public/flps/overview.test.js
Labels: frontend

#1802 [O2B-1403] Use coalesced run timestamps
  lib/database/repositories/QcFlagRepository.js
  lib/server/services/qualityControlFlag/QcFlagService.js
  lib/server/services/run/setO2StopOfLostRuns.js
Labels: backend

#1482 [O2B-532] Use time range filter for run start stop
  lib/public/components/Filters/RunsFilter/o2StartFilter.js
  lib/public/components/Filters/RunsFilter/o2StopFilter.js
  lib/public/components/Filters/RunsFilter/o2start.js
  lib/public/components/Filters/RunsFilter/o2stop.js
  lib/public/components/Filters/common/filters/TimeRangeInputModel.js
  lib/public/components/common/chart/rendering/ChartRenderer.js
  lib/public/components/common/form/inputs/DateTimeInputComponent.js
  lib/public/components/common/form/inputs/DateTimeInputModel.js
  lib/public/components/common/formatting/formatTimeRange.js
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
  lib/public/views/Runs/Overview/RunsOverviewModel.js
  test/public/defaults.js
  test/public/logs/create.test.js
  test/public/runs/overview.test.js
  test/public/runs/runsPerDataPass.overview.test.js
Labels: frontend

#1814 [O2B-1412] Removed retries limit to kafka connection
  lib/application.js
Labels: backend

#1811 [O2B-892] Modernize run details
  lib/public/components/common/externalLinks/aliEcsEnvironmentLinkComponent.js
  lib/public/components/common/externalLinks/infologgerLinksComponents.js
  lib/public/components/common/externalLinks/qcGuiLinkComponent.js
  lib/public/components/common/selection/dropdown/selectionDropdown.js
  lib/public/components/tag/TagSelectionDropdownModel.js
  lib/public/views/Runs/Details/RunDetailsModel.js
  lib/public/views/Runs/Details/editTagsPanel.js
  lib/public/views/Runs/Details/lhcFillPanel.js
  lib/public/views/Runs/Details/runDetailsComponent.js
  lib/public/views/Runs/Details/runDetailsConfiguration.js
  lib/public/views/Runs/Details/runLhcFillDisplayConfiguration.js
  lib/public/views/Runs/format/editRunEorReasons.js
  lib/public/views/Runs/format/formatEditableNumber.js
  lib/public/views/Runs/format/formatRunCalibrationStatus.js
  lib/public/views/Runs/format/formatRunDetectors.js
  lib/public/views/Runs/format/formatRunQuality.js
  lib/public/views/Tags/format/formatTagsList.js
  lib/server/kafka/AliEcsSynchronizer.js
  test/public/runs/detail.test.js
Labels: frontend

#1817 Release 1.4.0
  CHANGELOG.md
  database/CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#1818 [O2B-1417] Add more logs to services synchronization
  docker-compose.yml
  lib/application.js
  lib/config/services.js
  lib/server/externalServicesSynchronization/ccdb/CcdbSynchronizer.js
  lib/server/externalServicesSynchronization/monalisa/MonAlisaClient.js
  lib/server/externalServicesSynchronization/monalisa/MonAlisaSynchronizer.js
Labels: backend

#1819 [O2B-1418] Improve runs start/stop extraction from kafka
  lib/server/kafka/AliEcsSynchronizer.js
Labels: backend

#1821 Release 1.4.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#1822 [O2B-1406] Add n TF orbits
  lib/database/adapters/RunAdapter.js
  lib/database/migrations/20241218095948-add-n-tf-orbits.js
  lib/database/models/run.js
  lib/database/models/typedefs/SequelizeRun.js
  lib/database/seeders/20200713103855-runs.js
  lib/domain/dtos/UpdateRunByRunNumberDto.js
  lib/domain/entities/Run.js
  lib/public/views/Runs/Details/runDetailsComponent.js
  test/api/runs.test.js
  test/lib/usecases/run/UpdateRunUseCase.test.js
Labels: backend

#1823 Fix randomly failing timerange selection in tests
  lib/public/components/common/form/inputs/DateTimeInputComponent.js
Labels: bug
