Repository AliceO2Group/Bookkeeping, pull requests merged in 2024-02, with the labels that each got.

#1354 [O2B-1128] Implemented status history legend on environment overview
  docs/data-model.md
  lib/database/seeders/20230124105627-environment-history.js
  lib/public/app.css
  lib/public/components/common/popover/infoTooltip.js
  lib/public/components/common/table/headers.js
  lib/public/components/environments/environmentStatusHistoryComponent.js
  lib/public/views/Environments/ActiveColumns/environmentsActiveColumns.js
  lib/public/views/Environments/ColoredEnvironmentStatusComponent.js
  lib/public/views/Environments/format/displayEnvironmentStatusHistory.js
  lib/public/views/Environments/format/displayEnvironmentStatusHistoryOverview.js
  lib/public/views/Statistics/charts/environmentHistoryOccurrencesBarChartComponent.js
  test/lib/server/services/statistics/StatisticsService.test.js
  test/public/envs/detailsPage.test.js
  test/public/envs/overview.test.js
Labels: frontend

#1332 [O2B-1115] Implement runs per data pass API
  lib/database/utilities/QueryBuilder.js
  lib/domain/dtos/filters/RunFilterDto.js
  lib/usecases/run/GetAllRunsUseCase.js
  test/api/runs.test.js
Labels: backend

#1346 [O2B-1126] Show data passes counts
  lib/database/adapters/LhcPeriodStatisticsAdapter.js
  lib/database/models/lhcPeriod.js
  lib/database/models/typedefs/SequelizeLhcPeriodStatistics.js
  lib/domain/entities/LhcPeriodStatistics.js
  lib/public/views/lhcPeriods/ActiveColumns/lhcPeriodsActiveColumns.js
  lib/server/services/lhcPeriod/LhcPeriodStatisticsService.js
  test/api/lhcPeriodsStatistics.test.js
  test/lib/server/monalisa-synchronization/MonALISASynchronizer.test.js
  test/lib/server/services/lhcPeriod/LhcPeriodStatisticsService.test.js
  test/public/lhcPeriods/overview.test.js
Labels: frontend, backend

#1377 Release 0.77.0
  CHANGELOG.md
  database/CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#1379 [O2B-1141] Unify style of Runs Per LHC Period view title
  lib/public/views/Runs/RunPerPeriod/RunsPerLhcPeriodOverviewPage.js
Labels: frontend

#1381 Remove chai major update because it uses ES6
  .github/dependabot.yml
Labels: github_actions

#1389 [02B-1146] Fixed users seeders to use auto generated pk to avoid conflicts
  lib/database/seeders/20200426144121-users.js
Labels: bug, javascript

#1337 [O2B-1123] Use generic overview model in runs model
  lib/public/views/Home/Overview/HomePage.js
  lib/public/views/Home/Overview/HomePageModel.js
  lib/public/views/Runs/Overview/RunsOverviewModel.js
  lib/public/views/Runs/Overview/RunsOverviewPage.js
  lib/public/views/Runs/Overview/exportRunsTriggerAndModal.js
  lib/public/views/Runs/RunPerPeriod/RunsPerLhcPeriodOverviewModel.js
  lib/public/views/Runs/RunPerPeriod/RunsPerLhcPeriodOverviewPage.js
  lib/public/views/Runs/RunsModel.js
Labels: frontend

#1391 [O2B-1147] Fixed physics run filter toggle behavior
  lib/public/components/Filters/LogsFilter/environments.js
  lib/public/components/Filters/RunsFilter/dcs.js
  lib/public/components/Filters/RunsFilter/ddflp.js
  lib/public/components/Filters/RunsFilter/definitionFilter.js
  lib/public/components/Filters/RunsFilter/detectorsFilterComponent.js
  lib/public/components/Filters/RunsFilter/durationFilter.js
  lib/public/components/Filters/RunsFilter/environmentId.js
  lib/public/components/Filters/RunsFilter/eorReasonFilter.js
  lib/public/components/Filters/RunsFilter/epn.js
  lib/public/components/Filters/RunsFilter/fillNumbers.js
  lib/public/components/Filters/RunsFilter/lhcPeriod.js
  lib/public/components/Filters/RunsFilter/nDetectors.js
  lib/public/components/Filters/RunsFilter/nEpns.js
  lib/public/components/Filters/RunsFilter/nFlps.js
  lib/public/components/Filters/RunsFilter/o2start.js
  lib/public/components/Filters/RunsFilter/odcTopologyFullName.js
  lib/public/components/Filters/RunsFilter/runQuality.js
  lib/public/components/Filters/RunsFilter/triggerValue.js
  lib/public/components/common/form/switchInput.js
  lib/public/views/Runs/Overview/RunsOverviewModel.js
  lib/public/views/Runs/Overview/RunsOverviewPage.js
  lib/public/views/Runs/Overview/showPhysicsButton.js
Labels: bug, frontend

#1392 [O2B-1148] Runs filtering is not considered in runs export
  lib/public/views/Runs/Overview/RunsOverviewModel.js
  test/public/runs/overview.test.js
  test/utilities/waitForDownload.js
Labels: bug

#1395 Release 0.78.0
  CHANGELOG.md
  database/CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#1400 Add all dependencies to bundled dependencies
  package.json
Labels: dependencies

#1402 Release 0.78.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#1378 [O2B-1106] Preliminary cleaning of log creation component
  lib/public/components/Log/logDetailsButton.js
  lib/public/components/Log/logDisplayComponent.js
  lib/public/components/Log/logText.js
  lib/public/components/common/errorAlert.js
  lib/public/components/common/markdown/markdown.js
  lib/public/components/common/selection/infoLoggerButtonGroup/CopyToClipboardComponent.js
  lib/public/views/EosReport/create/eosReportCreationComponent.js
  lib/public/views/EosReport/create/typeSpecific/eosFormDcsSpecificPart.js
  lib/public/views/Logs/Create/LogCreationModel.js
  lib/public/views/Logs/Create/LogCreationPage.js
  lib/public/views/Logs/Create/logCreationComponent.js
  lib/public/views/Logs/Details/LogTreeViewModel.js
  lib/public/views/Logs/Details/logTreeViewComponent.js
  test/public/defaults.js
  test/public/logs/create.test.js
  test/public/logs/detail.test.js
Labels: frontend

#1394 Fix environments tests randomness
  test/lib/usecases/environment/GetAllEnvironmentsUseCase.test.js
Labels: backend

#1403 Fix typos in Dass Pass Service
  lib/server/services/dataPasses/DataPassService.js
  test/lib/server/services/dataPasses/DataPassesService.test.js
Labels: backend

#1388 [O2B-1106] Separate log reply from log creation
  lib/public/Model.js
  lib/public/components/Filters/common/filters/TextTokensFilterModel.js
  lib/public/components/Log/logReplyButton.js
  lib/public/components/common/panel/LabelPanelHeaderComponent.js
  lib/public/components/common/panel/PanelComponent.js
  lib/public/view.js
  lib/public/views/Logs/Create/LogCreationModel.js
  lib/public/views/Logs/Create/LogReplyModel.js
  lib/public/views/Logs/Create/LogReplyPage.js
  lib/public/views/Logs/Create/logCreationComponent.js
  lib/public/views/Logs/Create/logReplyComponent.js
  lib/public/views/Logs/Create/panels/LogCreationContentPanel.js
  lib/public/views/Logs/LogsModel.js
  test/public/logs/create.test.js
  test/public/logs/detail.test.js
  test/public/runs/detail.test.js
Labels: frontend

#1404 [O2B-1106] Set up log-templating for on-call
  lib/public/app.css
  lib/public/components/common/panel/LabelPanelHeaderComponent.js
  lib/public/views/Logs/Create/LogCreationModel.js
  lib/public/views/Logs/Create/OnCallLogTemplate.js
  lib/public/views/Logs/Create/TemplatedLogCreationModel.js
  lib/public/views/Logs/Create/logCreationComponent.js
  lib/public/views/Logs/Create/logReplyComponent.js
  lib/public/views/Logs/Create/onCallLogCreationConfiguration.js
  lib/public/views/Logs/Create/panels/LogCreationContentPanel.js
  lib/public/views/Logs/LogsModel.js
  test/public/defaults.js
  test/public/logs/create.test.js
Labels: frontend

#1408 [O2B-1158] Improve readability of on-call log
  lib/public/views/Logs/Create/OnCallLogTemplate.js
  lib/public/views/Logs/Create/onCallLogCreationConfiguration.js
  test/public/logs/create.test.js
Labels: frontend

#1410 Fix usage of lastRunNumber during Data Passes synchronization
  lib/server/monalisa-synchronization/MonAlisaSynchronizer.js
  test/lib/server/monalisa-synchronization/MonAlisaSynchronizer.test.js
Labels: backend

#1420 [O2B-1165] Do not send run quality in run update patch when it do not applies
  lib/public/components/common/errorAlert.js
  lib/public/views/Runs/Details/RunDetailsModel.js
  lib/public/views/Runs/Details/RunPatch.js
  lib/public/views/Runs/Details/runDetailsComponent.js
Labels: bug, frontend

#1412 [O2B-1161] Store only PHYSICS runs from MonALISA
  lib/database/migrations/20240216160730-remove-obsolate-non-physics-runs-links.js
  lib/server/monalisa-synchronization/MonAlisaSynchronizer.js
  lib/server/services/dataPasses/DataPassService.js
  test/api/dataPasses.test.js
  test/lib/server/monalisa-synchronization/MonAlisaSynchronizer.test.js
  test/lib/server/monalisa-synchronization/data/mockDataPasses.json
  test/lib/server/monalisa-synchronization/data/mockDescriptionToDataPassDetails.json
  test/lib/server/monalisa-synchronization/data/mockSimulationPasses.json
  test/lib/server/services/dataPasses/DataPassesService.test.js
Labels: backend

#1411 [O2B-904] Add API endpoint to fetch a list of main logs
  lib/database/repositories/Repository.js
  lib/server/controllers/logs.controller.js
  lib/server/routers/logs.router.js
  lib/server/services/log/LogService.js
  test/api/logs.test.js
  test/lib/server/services/log/LogService.test.js
Labels: backend

#1418 [O2B-1140] Add endpoint to fetch LHC fills ended in a given period
  lib/database/adapters/LhcFillAdapter.js
  lib/database/adapters/index.js
  lib/database/models/lhcFill.js
  lib/database/models/typedefs/SequelizeLhcFill.js
  lib/database/repositories/LhcFillRepository.js
  lib/database/seeders/20220503120937-lhc-fills.js
  lib/domain/entities/LhcFill.js
  lib/server/controllers/lhcFill.controller.js
  lib/server/routers/lhcFills.router.js
  lib/server/services/lhcFill/LhcFillService.js
  test/api/lhcFills.test.js
  test/lib/server/services/lhcFill/LhcFillService.test.js
Labels: backend

#1430 Extract external links to common configuration
  lib/public/components/NavBar/index.js
  lib/public/components/common/navigation/externalLinks.js
Labels: frontend

#1424 [O2B-1167] Include shifters logs in SL EoS report
  lib/server/services/shift/getShiftTagsFiltersByType.js
  test/api/shift.test.js
  test/api/tags.test.js
  test/lib/server/services/shift/ShiftService.test.js
  test/lib/usecases/log/GetAllLogsUseCase.test.js
  test/mocks/mock-shift-leader-eos-report.js
Labels: backend
