Repository AliceO2Group/Bookkeeping, pull requests merged in 2024-07, with the labels that each got.

#1630 [O2B-1303] Use icon for missing verification display
  lib/public/app.css
  lib/public/components/qcFlags/qcFlagsPagesButtons.js
  lib/public/components/qcFlags/qcSummaryLegendTooltip.js
  lib/public/views/Runs/ActiveColumns/runDetectorsAsyncQcActiveColumns.js
  test/public/runs/runsPerDataPass.overview.test.js
  test/public/runs/runsPerSimulationPass.overview.test.js
Labels: frontend

#1617 [O2B-1266] Special treatment of Limited Acceptance MC Reproducible flag in QC summary
  lib/database/migrations/20240702074339-add-mc-reproducible-to-qc-flag-type.js
  lib/database/seeders/20240213120811-qc-flags-types.js
  lib/database/seeders/20240404100811-qc-flags.js
  lib/public/components/qcFlags/qcSummaryColors.js
  lib/public/views/DataPasses/ActiveColumns/dataPassesActiveColumns.js
  lib/public/views/Runs/ActiveColumns/runDetectorsAsyncQcActiveColumns.js
  lib/public/views/lhcPeriods/ActiveColumns/lhcPeriodsActiveColumns.js
  lib/server/services/qualityControlFlag/QcFlagService.js
  test/api/qcFlagTypes.test.js
  test/api/qcFlags.test.js
  test/lib/server/services/qualityControlFlag/QcFlagService.test.js
  test/lib/server/services/qualityControlFlag/QcFlagTypeService.test.js
  test/public/qcFlagTypes/overview.test.js
  test/public/qcFlags/detailsForDataPass.test.js
  test/public/runs/runsPerDataPass.overview.test.js
Labels: frontend, backend

#1640 [O2B-1189] Store environment configuration in the database
  lib/database/adapters/EnvironmentAdapter.js
  lib/database/migrations/20240702134026-add-environment-raw-configuration.js
  lib/database/models/environment.js
  lib/database/models/typedefs/SequelizeEnvironment.js
  lib/database/seeders/20220412122043-environments.js
  lib/domain/dtos/CreateEnvironmentDto.js
  lib/domain/entities/Environment.js
  lib/public/views/Environments/Details/EnvironmentDetailsModel.js
  lib/public/views/Environments/Details/EnvironmentDetailsPage.js
  lib/server/controllers/gRPC/GRPCEnvironmentController.js
  lib/usecases/environment/CreateEnvironmentUseCase.js
  proto/environment.proto
  test/api/environments.test.js
  test/lib/server/services/environment/EnvironmentService.test.js
  test/public/envs/detailsPage.test.js
Labels: frontend, backend

#1641 [O2B-1305] Add adjust beam type in on-call template log options
  lib/public/views/Logs/Create/templates/onCallLogCreationConfiguration.js
Labels: frontend

#1639 [O2B-1231] Improve RC daily meeting minutes formatting and fix fills list
  lib/database/repositories/LhcFillRepository.js
  lib/public/views/Logs/Create/templates/RcDailyMeetingTemplate.js
  lib/public/views/Logs/Create/templates/rcDailyMeetingConfiguration.js
  lib/server/services/lhcFill/LhcFillService.js
Labels: frontend

#1637 [O2B-1298] Mark deleted ML productions
  lib/database/adapters/DataPassVersionAdapter.js
  lib/database/migrations/20240702084339-add-deleted-ML-productions-column.js
  lib/database/models/dataPassVersion.js
  lib/database/models/typedefs/SequelizeDataPassVersion.js
  lib/database/repositories/Repository.js
  lib/database/seeders/20240112102011-data-passes.js
  lib/domain/entities/DataPassVersion.js
  lib/public/components/common/badge.js
  lib/public/views/DataPasses/ActiveColumns/dataPassesActiveColumns.js
  lib/public/views/DataPasses/format/formatDataPassName.js
  lib/public/views/Runs/ActiveColumns/runDetectorsAsyncQcActiveColumns.js
  lib/server/monalisa-synchronization/MonAlisaSynchronizer.js
  test/api/dataPasses.test.js
  test/lib/server/monalisa-synchronization/MonAlisaSynchronizer.test.js
  test/lib/server/services/dataPasses/DataPassService.test.js
  test/public/dataPasses/overviewPerLhcPeriod.test.js
Labels: frontend, backend

#1642 Release 0.94.0
  CHANGELOG.md
  database/CHANGELOG.md
Labels: release

#1643 Fix release 0.94.0
  package-lock.json
  package.json
Labels: release

#1644 Fix randomly failing tests for Runs Per Data Pass Page
  test/public/runs/runsPerDataPass.overview.test.js
Labels: frontend

#1645 [O2B-1311] Invalida calculation in QC summary
  lib/public/components/qcFlags/qcSummaryColors.js
  lib/public/views/Runs/ActiveColumns/runDetectorsAsyncQcActiveColumns.js
  lib/server/services/qualityControlFlag/QcFlagService.js
  test/api/qcFlags.test.js
  test/lib/server/services/qualityControlFlag/QcFlagService.test.js
  test/public/runs/runsPerDataPass.overview.test.js
Labels: backend

#1638 [O2B-1306] Fix conditions for null timestamps in QC flag creation
  lib/database/migrations/20240705142020-make-effective-period-timestamps-nullable.js
  lib/database/repositories/QcFlagEffectivePeriodRepository.js
  lib/database/repositories/QcFlagRepository.js
  lib/public/views/QcFlags/ActiveColumns/qcFlagsActiveColumns.js
  lib/public/views/QcFlags/format/formatQcFlagEnd.js
  lib/public/views/QcFlags/format/formatQcFlagStart.js
  lib/server/services/qualityControlFlag/QcFlagService.js
  test/lib/server/services/qualityControlFlag/QcFlagService.test.js
Labels: backend

#1621 [O2B-1274] Add API for setting GAQ detectors
  lib/database/adapters/GaqDetectorAdapter.js
  lib/database/adapters/index.js
  lib/database/migrations/20240709105539-add-GAQ-detectors-table.js
  lib/database/models/gaqDetector.js
  lib/database/models/index.js
  lib/database/models/typedefs/SequelizeGaqDetector.js
  lib/database/repositories/GaqDetectorRepository.js
  lib/database/repositories/index.js
  lib/domain/entities/GaqDetector.js
  lib/server/controllers/dataPasses.controller.js
  lib/server/routers/dataPasses.router.js
  lib/server/services/dataPasses/DataPassService.js
  test/api/dataPasses.test.js
  test/lib/server/services/dataPasses/DataPassService.test.js
Labels: frontend, backend

#1650 Release 0.95.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#1652 Fix randomly failing test
  test/public/envs/overview.test.js
Labels: frontend

#1655 [O2B-1308] Add possibility to filter tags in log creation and run edition
  lib/public/components/common/selection/SelectionModel.js
  lib/public/components/common/selection/dropdown/SelectionDropdownModel.js
  lib/public/components/common/selection/picker/picker.js
  lib/public/components/tag/tagPicker.js
  lib/public/views/Logs/Create/logCreationComponent.js
  lib/public/views/Runs/Details/editTagsPanel.js
  test/public/logs/create.test.js
Labels: frontend

#1658 [O2B-1318] Bugfix QC flag deletion
  lib/server/services/qualityControlFlag/QcFlagService.js
  test/lib/server/services/qualityControlFlag/QcFlagService.test.js
Labels: bug, backend

#1661 Bump WebUI patch version
  package-lock.json
  package.json
Labels: dependencies

#1654 [O2B-1274] Api for fetching GAQ flags with views
  lib/database/adapters/dpl/DplDetectorAdapter.js
  lib/database/repositories/QcFlagRepository.js
  lib/database/seeders/20240213120811-qc-flags-types.js
  lib/server/controllers/qcFlag.controller.js
  lib/server/routers/qcFlag.router.js
  lib/server/services/qualityControlFlag/QcFlagService.js
  test/api/qcFlagTypes.test.js
  test/lib/server/services/qualityControlFlag/QcFlagService.test.js
  test/lib/server/services/qualityControlFlag/QcFlagTypeService.test.js
Labels: backend

#1649 [O2B-1313] Local parallelisation
  .github/workflows/bookkeeping.yml
  .github/workflows/docker.yml
  Dockerfile
  docker-compose.test-parallel-base.yml
  docker-compose.test-parallel-ci.yml
  docker-compose.test-parallel-local.yml
  docs/parallel-testing.md
  package-lock.json
  package.json
  test/scripts/parallel-local/custom-mocha-reporter.js
  test/scripts/parallel-local/main.js
  test/scripts/parallel-local/test-runner.js
Labels: javascript

#1664 Release 0.96.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#1669 [O2B-1321] Update Run Details labels and display values
  lib/public/components/FlpRun/index.js
  lib/public/views/Flps/ActiveColumns/flpsActiveColumns.js
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
  lib/public/views/Runs/Details/runDetailsConfiguration.js
Labels: frontend

#1671 Fix run detectors creation
  lib/server/services/run/RunService.js
  lib/server/services/run/createRun.js
  lib/server/services/run/getRun.js
Labels: backend

#1670 [O2B-1319] Merge detector tables - adjust run's detectors creation
  lib/database/adapters/DetectorAdapter.js
  lib/database/migrations/20240718120539-add-type-column-to-detectors.js
  lib/database/models/detector.js
  lib/database/models/typedefs/SequelizeDetector.js
  lib/database/seeders/20221005120315-detector.js
  lib/domain/entities/Detector.js
  lib/domain/enums/DetectorTypes.js
  lib/public/domain/enums/DetectorTypes.mjs
  lib/server/services/detector/getOrCreateAllDataTakingDetectorsByName.js
  lib/server/services/detector/getOrCreateAllDetectorsByName.js
  lib/server/services/run/RunService.js
  test/lib/server/services/detector/createDetector.test.js
  test/lib/server/services/detector/getOrCreateAllDataTakingDetectorsByName.test.js
  test/lib/server/services/detector/getOrCreateAllDetectors.test.js
  test/lib/server/services/detector/index.js
  test/public/eosReport/ecs-creation.test.js
Labels: backend, DB

#1433 [O2B-1100] Delete subsystems
  .github/workflows/bookkeeping.yml
  lib/database/adapters/LogAdapter.js
  lib/database/adapters/SubsystemAdapter.js
  lib/database/adapters/index.js
  lib/database/migrations/20240430100347-delete-subsystems.js
  lib/database/models/index.js
  lib/database/models/log.js
  lib/database/models/subsystem.js
  lib/database/models/typedefs/SequelizeLog.js
  lib/database/models/typedefs/SequelizeSubsystem.js
  lib/database/repositories/LogRepository.js
  lib/database/repositories/SubsystemRepository.js
  lib/database/repositories/index.js
  lib/database/seeders/20200508094502-logs.js
  lib/database/seeders/20200606151010-subsystems.js
  lib/database/seeders/20200606301010-log-subsystems.js
  lib/domain/dtos/CreateSubsystemDto.js
  lib/domain/dtos/GetAllSubsystemsDto.js
  lib/domain/dtos/GetSubsystemDto.js
  lib/domain/dtos/index.js
  lib/domain/entities/Log.js
  lib/domain/entities/Subsystem.js
  lib/public/Model.js
  lib/public/components/NavBar/index.js
  lib/public/view.js
  lib/public/views/Subsystems/Details/index.js
  lib/public/views/Subsystems/Overview/index.js
  lib/public/views/Subsystems/Subsystems.js
  lib/server/controllers/index.js
  lib/server/controllers/subsystems.controller.js
  lib/server/routers/index.js
  lib/server/routers/subsystems.router.js
  lib/server/services/log/LogService.js
  lib/usecases/index.js
  lib/usecases/log/GetAllLogsUseCase.js
  lib/usecases/log/GetLogUseCase.js
  lib/usecases/subsystem/CreateSubsystemUseCase.js
  lib/usecases/subsystem/DeleteSubsystemUseCase.js
  lib/usecases/subsystem/GetAllSubsystemsUseCase.js
  lib/usecases/subsystem/GetLogsBySubsystemUseCase.js
  lib/usecases/subsystem/GetSubsystemUseCase.js
  lib/usecases/subsystem/index.js
  proto/log.proto
  test/api/index.js
  test/api/subsystems.test.js
  test/lib/usecases/index.js
  test/lib/usecases/subsystem/CreateSubsystemUseCase.test.js
  test/lib/usecases/subsystem/DeleteSubsystemUseCase.test.js
  test/lib/usecases/subsystem/GetAllSubsystemsUseCase.test.js
  test/lib/usecases/subsystem/GetSubsystemUseCase.test.js
  test/lib/usecases/subsystem/index.js
  test/presentation/log/toTreeView.test.js
  test/public/index.js
  test/public/subsystems/detail.test.js
  test/public/subsystems/index.js
  test/public/subsystems/overview.test.js
  test/scripts/parallel-local/main.js
  test/scripts/test-subsystems.js
Labels: frontend, backend

#1678 Bump WebUI to 2.7.0
  package-lock.json
  package.json
Labels: dependencies

#1675 [O2B-1264] Several improvements to environments
  lib/database/adapters/EnvironmentAdapter.js
  lib/database/migrations/20240712100711-environments-milliseconds-timestamps-and-remove-toredown-at.js
  lib/database/models/environment.js
  lib/database/models/environmenthistoryitem.js
  lib/database/repositories/Repository.js
  lib/domain/dtos/CreateEnvironmentHistoryItemDto.js
  lib/public/domain/enums/statusAcronym.mjs
  lib/public/views/Environments/ColoredEnvironmentStatusComponent.js
  lib/public/views/Environments/Details/EnvironmentDetailsPage.js
  lib/server/monalisa-synchronization/MonAlisaClient.js
  lib/server/services/environment/EnvironmentService.js
  test/api/environments.test.js
  test/lib/server/services/environment/EnvironmentService.test.js
Labels: frontend, backend

#1681 [O2B-1222] Stable beam only toggle on lhc fills overview page
  lib/public/views/LhcFills/Overview/LhcFillsOverviewModel.js
  lib/public/views/LhcFills/Overview/index.js
  test/public/lhcFills/overview.test.js
Labels: frontend

#1659 [O2B-1274] Fetching GAQ detectors
  lib/database/seeders/20240716124000-gaq-detectors.js
  lib/server/controllers/dataPasses.controller.js
  lib/server/routers/dataPasses.router.js
  lib/server/services/dataPasses/DataPassService.js
  test/api/dataPasses.test.js
  test/lib/server/services/dataPasses/DataPassService.test.js
  test/lib/server/services/qualityControlFlag/QcFlagService.test.js
Labels: backend

#1680 [O2B-1319] Merge detectors tables - remove DPL detectors table
  lib/database/adapters/DetectorAdapter.js
  lib/database/adapters/GaqDetectorAdapter.js
  lib/database/adapters/QcFlagAdapter.js
  lib/database/adapters/SimulationPassQcFlagAdapter.js
  lib/database/migrations/20240724134539-migrate-dpl-detectors-to-detectors.js
  lib/database/models/detector.js
  lib/database/models/dpl/dpldetector.js
  lib/database/models/dpl/dplprocessexecution.js
  lib/database/models/gaqDetector.js
  lib/database/models/index.js
  lib/database/models/qcFlag.js
  lib/database/repositories/QcFlagEffectivePeriodRepository.js
  lib/database/repositories/QcFlagRepository.js
  lib/database/repositories/dpl/DplDetectorRepository.js
  lib/database/seeders/20221005120315-detector.js
  lib/database/seeders/20230428095027-dpl-detectors.js
  lib/database/seeders/20240404100811-qc-flags.js
  lib/database/seeders/20240716124000-gaq-detectors.js
  lib/domain/entities/GaqDetector.js
  lib/public/domain/enums/DetectorTypes.js
  lib/server/controllers/detectors.controller.js
  lib/server/controllers/dplProcess.controller.js
  lib/server/controllers/gRPC/GRPCQcFlagController.js
  lib/server/controllers/qcFlag.controller.js
  lib/server/services/dataPasses/DataPassService.js
  lib/server/services/dpl/createDplDetector.js
  lib/server/services/dpl/getDplDetector.js
  lib/server/services/dpl/getDplDetectorOrFail.js
  lib/server/services/dpl/getOrCreateDplDetector.js
  lib/server/services/dpl/getPhysicalDplDetectorOrFail.js
  lib/server/services/qualityControlFlag/QcFlagService.js
  test/api/dataPasses.test.js
  test/api/qcFlags.test.js
  test/lib/server/services/dataPasses/DataPassService.test.js
  test/lib/server/services/detector/DetectorService.test.js
  test/lib/server/services/detector/getAllDetectors.test.js
  test/lib/server/services/dpl/DplProcessService.test.js
  test/lib/server/services/qualityControlFlag/QcFlagService.test.js
  test/public/runs/runsPerSimulationPass.overview.test.js
Labels: backend, DB

#1684 [O2B-1274] Fix order by GAQ detectors
  lib/server/services/dataPasses/DataPassService.js
  test/api/dataPasses.test.js
  test/lib/server/services/dataPasses/DataPassService.test.js
Labels: backend

#1657 [O2B-1322] GAQ flags overview display
  lib/database/adapters/QcFlagTypeAdapter.js
  lib/database/migrations/20240731134539-add-default-GAQ-detectors.js
  lib/database/models/qcFlagType.js
  lib/database/models/typedefs/SequelizeQcFlagType.js
  lib/database/seeders/20240213120811-qc-flags-types.js
  lib/database/seeders/20240716124000-gaq-detectors.js
  lib/domain/entities/QcFlagType.js
  lib/public/Model.js
  lib/public/components/qcFlags/qcFlagsBreadcrumbs.js
  lib/public/components/qcFlags/qcSummaryColors.js
  lib/public/view.js
  lib/public/views/QcFlags/ActiveColumns/gaqFlagsActiveColumns.js
  lib/public/views/QcFlags/GaqFlags/GaqFlagsOverviewModel.js
  lib/public/views/QcFlags/GaqFlags/GaqFlagsOverviewPage.js
  lib/public/views/QcFlags/QcFlagsModel.js
  lib/public/views/Runs/ActiveColumns/runDetectorsAsyncQcActiveColumns.js
  lib/public/views/Runs/RunPerDataPass/RunsPerDataPassOverviewModel.js
  lib/public/views/Runs/RunPerDataPass/RunsPerDataPassOverviewPage.js
  test/api/qcFlagTypes.test.js
  test/api/qcFlags.test.js
  test/lib/server/services/qualityControlFlag/QcFlagService.test.js
  test/lib/server/services/qualityControlFlag/QcFlagTypeService.test.js
  test/public/defaults.js
  test/public/qcFlags/gaqOverview.test.js
  test/public/qcFlags/index.js
Labels: frontend

#1689 [O2B-1322] Fix adding default GAQ detectors
  lib/database/migrations/20240731134539-add-default-GAQ-detectors.js
Labels: backend
