Repository AliceO2Group/Bookkeeping, pull requests merged in 2024-01, with the labels that each got.

#1318 [O2B-1092] add migration data passes runs migration
  lib/database/migrations/20240108090706-create-data-passes-runs.js
  lib/database/models/dataPass.js
  lib/database/models/run.js
Labels: DB

#1308 [O2B-1091] add checkbox filter for excluding anonymous logs on log entries overview page
  lib/public/components/Filters/LogsFilter/author.js
  lib/public/components/Filters/LogsFilter/author/AuthorFilterModel.js
  lib/public/components/Filters/LogsFilter/author/authorFilter.js
  lib/public/views/Logs/ActiveColumns/logsActiveColumns.js
  lib/public/views/Logs/Overview/LogsOverviewModel.js
  lib/usecases/log/GetAllLogsUseCase.js
  test/api/logs.test.js
Labels: frontend, backend

#1321 Add unique constraint to column name of data_passes column
  lib/database/migrations/20240109091430-add-unique-constraint-to-data-passes.js
Labels: bug

#1315 [1086] Store user starting/stopping a run in database
  lib/database/adapters/RunAdapter.js
  lib/database/migrations/20231215113344-add-stop-and-start-users-to-run.js
  lib/database/models/run.js
  lib/database/models/typedefs/SequelizeRun.js
  lib/domain/entities/Run.js
  lib/server/controllers/gRPC/GRPCRunController.js
  lib/server/services/run/RunService.js
  proto/common.proto
  proto/run.proto
  test/lib/server/services/run/RunService.test.js
  test/lib/server/services/user/UserService.test.js
Labels: backend, DB

#1330 [O2B-1112] Add scheduled process manager
  lib/application.js
  lib/server/services/ScheduledProcessesManager.js
  test/lib/server/services/ScheduledProcessesManager.test.js
Labels: backend

#1329 [O2B-1093] Add argument to logging method
  lib/server/monalisa-synchronization/MonALISASynchronizer.js
Labels: bug

#1292 [O2B-1087] Set-up reusable OverviewPageModel
  lib/public/models/OverviewModel.js
  lib/public/services/lhcFill/addStatisticsToLhcFill.js
  lib/public/utilities/ObservableData.js
  lib/public/utilities/fetch/PaginatedRemoteDataSource.js
  lib/public/utilities/fetch/RemoteDataSource.js
  lib/public/views/LhcFills/LhcFills.js
  lib/public/views/LhcFills/Overview/LhcFillsOverviewModel.js
  lib/public/views/LhcFills/Overview/index.js
  lib/public/views/Statistics/StatisticsPageModel.js
Labels: frontend

#1335 [O2B-1087] Remove clause 'other'
  lib/public/models/OverviewModel.js
Labels: bug

#1338 [O2B-1104] environment status history API bugfix
  lib/database/repositories/EnvironmentHistoryItemRepository.js
Labels: bug

#1325 [O2B-1111] Implement data passes API
  lib/server/controllers/dataPasses.controller.js
  lib/server/routers/dataPasses.router.js
  lib/server/routers/index.js
  lib/server/services/dataPasses/DataPassService.js
  test/api/dataPasses.test.js
  test/api/index.js
  test/lib/server/services/dataPasses/DataPassesService.test.js
Labels: backend

#1339 [O2B-1087] Rollback usage of RemoteData.map not already available
  lib/public/views/Statistics/StatisticsPageModel.js
Labels: bug, frontend

#1326 [O2B-1107] Filter on environment id
  lib/domain/dtos/GetAllEnvironmentsDto.js
  lib/usecases/environment/GetAllEnvironmentsUseCase.js
  test/api/environments.test.js
  test/lib/usecases/environment/GetAllEnvironmentsUseCase.test.js
Labels: backend

#1340 [O2B-1125] Use scheduled process manager for synchronisation with MonALISA
  lib/application.js
  lib/config/services.js
Labels: backend

#1344 [O2B-1020] Bug fix for LHC Fill info disappearing
  lib/public/views/Runs/Details/RunDetailsModel.js
Labels: frontend

#1334 [O2B-1094] Add runs counts to lhc periods view
  lib/database/adapters/LhcPeriodStatisticsAdapter.js
  lib/database/models/typedefs/SequelizeLhcPeriodStatistics.js
  lib/domain/entities/LhcPeriodStatistics.js
  lib/public/app.css
  lib/public/views/lhcPeriods/ActiveColumns/lhcPeriodsActiveColumns.js
  lib/server/services/lhcPeriod/LhcPeriodStatisticsService.js
  test/api/lhcPeriodsStatistics.test.js
  test/lib/server/services/lhcPeriod/LhcPeriodStatisticsService.test.js
  test/public/lhcPeriods/overview.test.js
Labels: frontend

#1328 [O2B-1103] Environment history occurrences histogram
  lib/public/domain/enums/statusAcronyms.js
  lib/public/views/Environments/ActiveColumns/environmentsActiveColumns.js
  lib/public/views/Environments/format/displayEnvironmentStatusHistory.js
  lib/public/views/Environments/format/displayEnvironmentStatusHistoryOverview.js
  lib/public/views/Statistics/StatisticsPage.js
  lib/public/views/Statistics/StatisticsPageModel.js
  lib/public/views/Statistics/charts/environmentHistoryOccurrencesBarChartComponent.js
Labels: frontend

#1349 Release 0.76.0
  CHANGELOG.md
  database/CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#1350 Remove chart dead code
  lib/public/components/common/chart/lineChart/lineChartComponent.js
Labels: frontend

#1357 [O2B-532] Add missing foreign key to history items
  lib/database/migrations/20240119152741-add-history-items-fk.js
Labels: backend

#1268 [O2B-1058] lhc fill overview page should use button group on fill number column
  lib/public/components/common/infologger/infologgerLinksComponents.js
  lib/public/components/common/selection/infoLoggerButtonGroup/buttonLinkWithDropdown.js
  lib/public/components/common/selection/infoLoggerButtonGroup/infoLoggerButtonGroup.js
  lib/public/services/externalRouting/getInfologgerLinksUrls.js
  lib/public/views/Environments/ActiveColumns/environmentsActiveColumns.js
  lib/public/views/LhcFills/ActiveColumns/lhcFillsActiveColumns.js
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
Labels: frontend, javascript

#1289 [O2B-1079] Fetch run number that includes a specific substring
  lib/usecases/run/GetAllRunsUseCase.js
  test/api/runs.test.js
  test/lib/usecases/run/GetAllRunsUseCase.test.js
  test/public/runs/overview.test.js
Labels: backend

#1342 [O2B-1108] Environment filter on current status
  lib/domain/dtos/GetAllEnvironmentsDto.js
  lib/usecases/environment/GetAllEnvironmentsUseCase.js
  test/api/environments.test.js
  test/lib/usecases/environment/GetAllEnvironmentsUseCase.test.js
Labels: backend

#1345 [O2B-1109] environment filter status history
  lib/domain/dtos/GetAllEnvironmentsDto.js
  lib/domain/enums/StatusAcronyms.js
  lib/usecases/environment/GetAllEnvironmentsUseCase.js
  test/api/environments.test.js
  test/lib/usecases/environment/GetAllEnvironmentsUseCase.test.js
Labels: backend

#1359 [O2B-987] Improvements of DPL processes tree
  lib/public/views/Runs/Details/runDetailsComponent.js
  lib/server/services/dpl/DplProcessService.js
Labels: frontend, backend, javascript

#1360 [O2B-988] Sort DPL tasks alphabetically
  lib/server/services/dpl/DplProcessService.js
  test/api/dplProcess.test.js
  test/lib/server/services/dpl/DplProcessService.test.js
Labels: backend, javascript

#1358 [O2B-1072] Home Page redesign
  lib/public/components/Pagination/PaginationModel.js
  lib/public/models/OverviewModel.js
  lib/public/utilities/estimateDisplayableRowsCount.js
  lib/public/views/Home/Overview/HomePage.js
  lib/public/views/Home/Overview/HomePageModel.js
  lib/public/views/LhcFills/ActiveColumns/lhcFillsActiveColumns.js
  lib/public/views/LhcFills/LhcFills.js
  lib/public/views/LhcFills/Overview/LhcFillsOverviewModel.js
  lib/public/views/Logs/ActiveColumns/logsActiveColumns.js
  lib/public/views/Logs/Overview/LogsOverviewModel.js
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
  lib/public/views/Runs/format/formatRunEnd.js
  lib/public/views/Runs/format/formatRunStart.js
  test/public/defaults.js
Labels: frontend, javascript

#1364 [O2B-1110] Fetch runs in sub-query in environments
  lib/database/migrations/20240124112734-add-runs-env-id-index.js
  lib/usecases/environment/GetAllEnvironmentsUseCase.js
Labels: bug, backend

#1369 [O2B-1136] Unify LHC Periods view styling
  lib/public/views/lhcPeriods/ActiveColumns/lhcPeriodsActiveColumns.js
  lib/public/views/lhcPeriods/Overview/LhcPeriodsOverviewPage.js
  test/public/lhcPeriods/overview.test.js
Labels: frontend

#1375 [O2B-883] Fix runs quality border triggering balloon display
  lib/public/app.css
  lib/public/components/common/popover/overflowBalloon.js
  lib/public/views/Runs/format/formatRunDetectorsInline.js
Labels: frontend
