Repository AliceO2Group/Bookkeeping, pull requests merged in 2024-11, with the labels that each got.

#1786 [O2B-1390] Fix grey QC summary
  lib/server/services/qualityControlFlag/QcFlagService.js
  test/lib/server/services/qualityControlFlag/QcFlagService.test.js
Labels: backend

#1790 [O2B-1337] Log when run is tagged not for physics
  lib/database/seeders/20200511151010-tags.js
  lib/public/components/NavBar/index.js
  lib/server/services/run/RunService.js
  lib/server/services/run/logEntriesCreation/logSpecificRunTag.js
  lib/server/services/run/updateRun.js
  test/api/tags.test.js
  test/lib/server/services/run/updateRun.test.js
  test/lib/usecases/tag/GetAllTagsUseCase.test.js
  test/public/logs/create.test.js
  test/public/tags/overview.test.js
Labels: backend

#1789 [O2B-1394] Survive to DB crash
  lib/server/WebUiServer.js
Labels: bug, backend

#1791 Release 1.2.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#1797 [O2B-1375] Minor improvements to environment configuration display
  lib/public/views/Environments/Details/EnvironmentDetailsPage.js
  test/public/envs/detailsPage.test.js
Labels: frontend

#1796 [O2B-1399] Fix physical constants values
  lib/database/migrations/20231025101611-create-lhc-periods-view.js
  lib/database/migrations/20241105125509-fix-physical-constants.js
  test/api/lhcPeriodsStatistics.test.js
  test/lib/server/services/lhcPeriod/LhcPeriodStatisticsService.test.js
Labels: bug, DB

#1781 [O2B-1154] QC flags visualization
  lib/database/adapters/QcFlagAdapter.js
  lib/public/components/common/chart/barChart/barChartComponent.js
  lib/public/components/common/chart/lineChart/lineChartComponent.js
  lib/public/components/common/chart/rendering/BarChartRenderer.js
  lib/public/components/common/chart/rendering/ChartRenderer.js
  lib/public/components/common/chart/rendering/LineChartRenderer.js
  lib/public/components/common/chart/rendering/dataset/renderDatasetAsBars.js
  lib/public/components/common/chart/structures/BarPropertiesProvider.js
  lib/public/components/common/chart/structures/ChartBar.js
  lib/public/components/common/chart/structures/DrawableData.js
  lib/public/components/common/chart/structures/VisualProperties.js
  lib/public/views/QcFlags/ForDataPass/QcFlagsForDataPassOverviewPage.js
  lib/public/views/QcFlags/Overview/QcFlagsOverviewModel.js
  lib/public/views/QcFlags/qcFlagsVisualization/qcFlagsChartComponent.js
  lib/server/services/qualityControlFlag/QcFlagService.js
  test/api/qcFlags.test.js
  test/lib/server/services/qualityControlFlag/QcFlagService.test.js
  test/public/qcFlags/forDataPassOverview.test.js
  test/public/qcFlags/forSimulationPassOverview.test.js
Labels: frontend

#1798 Release 1.3.0
  CHANGELOG.md
  database/CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#1795 [O2B-1401] Store runs and QC flags timestamps with ms
  lib/database/migrations/20241105090940-store-run-and-qcflags-timestamps-in-ms.js
  lib/database/repositories/EnvironmentHistoryItemRepository.js
  lib/server/services/run/setO2StopOfLostRuns.js
  lib/server/utilities/timestampToMysql.js
  test/api/qcFlags.test.js
  test/lib/server/services/qualityControlFlag/QcFlagService.test.js
  test/public/flps/overview.test.js
Labels: bug
