Repository AliceO2Group/Bookkeeping, pull requests merged in 2024-08, with the labels that each got.

#1693 Fix tests GAQ overview tests
  test/public/defaults.js
  test/public/qcFlags/gaqOverview.test.js
  test/public/qcFlags/index.js
  test/scripts/test-qcFlags.js
Labels: CI

#1691 [improv] Update jwt.js to reduce default expire value
  lib/config/jwt.js
Labels: backend

#1683 [O2B-1325] GAQ Summary API
  lib/database/repositories/QcFlagRepository.js
  lib/database/seeders/20240716124000-gaq-detectors.js
  lib/server/controllers/qcFlag.controller.js
  lib/server/routers/qcFlag.router.js
  lib/server/services/qualityControlFlag/QcFlagService.js
  test/api/qcFlags.test.js
  test/lib/server/services/qualityControlFlag/QcFlagService.test.js
Labels: backend

#1687 [O2B-1325] GAQ summary display
  lib/public/components/qcFlags/qcSummaryColors.js
  lib/public/components/qcFlags/qcSummaryLegendTooltip.js
  lib/public/views/QcFlags/ActiveColumns/gaqFlagsActiveColumns.js
  lib/public/views/Runs/ActiveColumns/getQcSummaryDisplay.js
  lib/public/views/Runs/ActiveColumns/runDetectorsAsyncQcActiveColumns.js
  lib/public/views/Runs/RunPerDataPass/RunsPerDataPassOverviewModel.js
  lib/public/views/Runs/RunPerDataPass/RunsPerDataPassOverviewPage.js
  test/public/runs/runsPerDataPass.overview.test.js
Labels: frontend

#1701 [O2B-1235] Operation of flag deletion should be logged
  lib/server/services/qualityControlFlag/QcFlagService.js
Labels: backend

#1698 [O2B-1331] Bug fix: QC flag origin not displayed on details page
  lib/database/seeders/20200426144121-users.js
  lib/database/seeders/20240404100811-qc-flags.js
  lib/public/views/QcFlags/details/qcFlagDetailsConfiguration.js
  lib/public/views/QcFlags/format/formatQcFlagCreatedBy.js
  test/api/qcFlags.test.js
  test/lib/server/services/qualityControlFlag/QcFlagService.test.js
  test/public/qcFlags/detailsForDataPass.test.js
Labels: frontend

#1690 [O2B-1327] User interface for setting GAQ detectors
  lib/public/components/common/selection/picker/picker.js
  lib/public/components/detector/PhysicalDetectorPickerModel.js
  lib/public/models/UserRoleSelectionModel.js
  lib/public/services/detectors/detectorsProvider.js
  lib/public/views/QcFlags/GaqFlags/GaqFlagsOverviewModel.js
  lib/public/views/QcFlags/GaqFlags/GaqFlagsOverviewPage.js
  lib/public/views/QcFlags/GaqFlags/gaqDetectorsSelectionModalTrigger.js
  test/public/qcFlags/detailsForDataPass.test.js
  test/public/qcFlags/gaqOverview.test.js
Labels: frontend

#1710 [O2B-1292] Runs sorting by run number
  lib/domain/dtos/GetAllRunsDto.js
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
  lib/public/views/Runs/RunPerDataPass/RunsPerDataPassOverviewPage.js
  lib/public/views/Runs/RunPerPeriod/RunsPerLhcPeriodOverviewPage.js
  lib/public/views/Runs/RunsPerSimulationPass/RunsPerSimulationPassOverviewPage.js
  test/api/runs.test.js
  test/lib/usecases/run/GetAllRunsUseCase.test.js
  test/public/runs/runsPerDataPass.overview.test.js
  test/public/runs/runsPerPeriod.overview.test.js
  test/public/runs/runsPerSimulationPass.overview.test.js
Labels: frontend, backend

#1706 [O2B-1349] Fix error from run-detectors async qualities display
  lib/public/views/Runs/RunPerDataPass/RunsPerDataPassOverviewPage.js
  lib/public/views/Runs/RunsPerSimulationPass/RunsPerSimulationPassOverviewModel.js
  lib/public/views/Runs/RunsPerSimulationPass/RunsPerSimulationPassOverviewPage.js
Labels: frontend

#1711 [O2B-1357] Add environmentId to runs overview links
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
  test/public/runs/overview.test.js
Labels: frontend

#1716 [O2B-1328] Update p2info to P2INFO in daily meeting template
  lib/database/seeders/20200511151010-tags.js
  lib/public/views/Logs/Create/templates/RcDailyMeetingTemplate.js
  test/public/logs/create.test.js
Labels: frontend

#1717 [O2B-1329] Order runs to be checked in ascending order in RC daily template
  lib/public/views/Logs/Create/templates/RcDailyMeetingTemplate.js
Labels: frontend

#1718 [O2B-1330] Add EMC to list of detectors in RC daily template
  lib/public/views/Logs/Create/templates/RcDailyMeetingTemplate.js
  test/public/logs/create.test.js
Labels: frontend

#1704 [O2B-1336] Insert default GAQ detector on synchronization with ML
  lib/database/migrations/20240731134539-add-default-GAQ-detectors.js
  lib/server/monalisa-synchronization/MonAlisaSynchronizer.js
  lib/server/services/dataPasses/DataPassService.js
  test/lib/server/monalisa-synchronization/MonAlisaSynchronizer.test.js
  test/lib/server/services/dataPasses/DataPassService.test.js
Labels: backend

#1712 [O2B-1343] Extract GAQ detectors logic to separate service and controller
  lib/database/migrations/20240731134539-add-default-GAQ-detectors.js
  lib/public/views/QcFlags/GaqFlags/GaqFlagsOverviewModel.js
  lib/server/controllers/dataPasses.controller.js
  lib/server/controllers/gaqDetectors.controller.js
  lib/server/monalisa-synchronization/MonAlisaSynchronizer.js
  lib/server/routers/dataPasses.router.js
  lib/server/routers/gaqDetectors.router.js
  lib/server/routers/index.js
  lib/server/services/dataPasses/DataPassService.js
  lib/server/services/gaq/GaqDetectorsService.js
  test/api/dataPasses.test.js
  test/api/gaqDetectors.test.js
  test/api/index.js
  test/lib/server/monalisa-synchronization/MonAlisaSynchronizer.test.js
  test/lib/server/services/dataPasses/DataPassService.test.js
  test/lib/server/services/gaq/GaqDetectorService.test.js
  test/lib/server/services/gaq/index.js
  test/lib/server/services/index.js
  test/lib/server/services/qualityControlFlag/QcFlagService.test.js
  test/public/qcFlags/index.js
Labels: backend

#1721 [O2B-1360] Remove useless toredown_at column
  Dockerfile
  docs/data-model.md
  lib/database/adapters/EnvironmentAdapter.js
  lib/database/migrations/20240815064316-remove-environments-toredown-at.js
  lib/database/models/environment.js
  lib/database/models/typedefs/SequelizeEnvironment.js
  lib/domain/dtos/UpdateEnvironmentDto.js
  lib/domain/entities/Environment.js
  lib/server/controllers/gRPC/GRPCEnvironmentController.js
  lib/usecases/environment/UpdateEnvironmentUseCase.js
  proto/environment.proto
  test/api/environments.test.js
  test/lib/usecases/environment/UpdateEnvironmentUseCase.test.js
  test/public/lhcFills/overview.test.js
Labels: backend

#1722 [O2B-1189] Handle environment raw configuration as JSON
  lib/database/seeders/20220412122043-environments.js
  lib/public/views/Environments/Details/EnvironmentDetailsPage.js
  test/lib/server/services/environment/EnvironmentService.test.js
  test/public/envs/detailsPage.test.js
Labels: frontend, backend

#1723 Release 0.97.0
  CHANGELOG.md
  database/CHANGELOG.md
Labels: release

#1724 Release 0.97.0 - Update package.json
  package-lock.json
  package.json
Labels: release

#1728 [O2B-1364] Fix unnecessary splitting of GAQ periods
  lib/database/repositories/QcFlagRepository.js
Labels: backend

#1714 [O2B-1355] API for fetching synchronous QC flags
  lib/database/seeders/20240404100811-qc-flags.js
  lib/server/controllers/qcFlag.controller.js
  lib/server/routers/qcFlag.router.js
  lib/server/services/qualityControlFlag/QcFlagService.js
  test/api/qcFlags.test.js
  test/lib/server/services/qualityControlFlag/QcFlagService.test.js
Labels: backend

#1725 [O2B-1320] Fix number formatting in run details
  lib/public/components/FlpRun/index.js
  lib/public/views/Flps/ActiveColumns/flpsActiveColumns.js
  lib/public/views/Runs/Details/runDetailsComponent.js
  test/public/runs/detail.test.js
Labels: bug

#1732 Release 0.98.0
  CHANGELOG.md
  database/CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#1736 [O2B-1345] Show status history of data passes
  lib/database/adapters/DataPassVersionAdapter.js
  lib/public/domain/enums/DataPassVersionStatus.js
  lib/public/views/DataPasses/ActiveColumns/dataPassesActiveColumns.js
  lib/public/views/DataPasses/PerLhcPeriodOverview/DataPassesPerLhcPeriodOverviewView.js
  lib/public/views/DataPasses/PerSimulationPassOverview/DataPassesPerSimulationPassOverviewPage.js
  lib/public/views/DataPasses/format/formatDataPassName.js
  lib/public/views/DataPasses/format/formatStatusHistory.js
  test/api/dataPasses.test.js
  test/lib/server/services/dataPasses/DataPassService.test.js
  test/public/dataPasses/overviewPerLhcPeriod.test.js
  test/public/dataPasses/overviewPerSimulationPass.test.js
Labels: frontend

#1708 [O2B-1351] Remove GLO column from runs views
  lib/public/services/detectors/detectorsProvider.js
  lib/public/views/Runs/ActiveColumns/runDetectorsAsyncQcActiveColumns.js
Labels: frontend

#1719 [O2B-1358] API for fetching QC summary of synchronous QC flags
  lib/server/controllers/qcFlag.controller.js
  lib/server/services/qualityControlFlag/QcFlagService.js
  test/api/qcFlags.test.js
  test/lib/server/services/qualityControlFlag/QcFlagService.test.js
Labels: backend

#1726 [O2B-1346] Runs filtering by INEL and mu values
  lib/database/adapters/DataPassAdapter.js
  lib/database/seeders/20200713103855-runs.js
  lib/database/seeders/20220503120937-lhc-fills.js
  lib/public/components/Filters/common/filters/ComparisonSelectionModel.js
  lib/public/components/Filters/common/filters/FloatComparisonFilterModel.js
  lib/public/components/Filters/common/filters/floatNumberFilter.js
  lib/public/components/Filters/common/filtersPanelPopover.js
  lib/public/components/common/selection/dropdown/selectionDropdown.js
  lib/public/domain/enums/PdpBeamType.js
  lib/public/views/DataPasses/ActiveColumns/dataPassesActiveColumns.js
  lib/public/views/Runs/ActiveColumns/inelasticInteractionRateActiveColumnsForPbPb.js
  lib/public/views/Runs/ActiveColumns/inelasticInteractionRateActiveColumnsForProtonProton.js
  lib/public/views/Runs/Details/runDetailsConfiguration.js
  lib/public/views/Runs/Overview/FixedPdpBeamTypeRunsOverviewModel.js
  lib/public/views/Runs/Overview/RunsOverviewModel.js
  lib/public/views/Runs/RunPerDataPass/RunsPerDataPassOverviewModel.js
  lib/public/views/Runs/RunPerDataPass/RunsPerDataPassOverviewPage.js
  lib/public/views/Runs/RunPerPeriod/RunsPerLhcPeriodOverviewPage.js
  lib/public/views/Runs/RunsModel.js
  lib/public/views/Runs/RunsPerSimulationPass/RunsPerSimulationPassOverviewPage.js
  lib/server/services/dataPasses/DataPassService.js
  test/api/dataPasses.test.js
  test/api/lhcPeriodsStatistics.test.js
  test/api/runs.test.js
  test/lib/server/services/dataPasses/DataPassService.test.js
  test/lib/server/services/lhcPeriod/LhcPeriodStatisticsService.test.js
  test/lib/server/services/run/RunService.test.js
  test/lib/server/services/statistics/StatisticsService.test.js
  test/lib/usecases/run/GetAllRunsUseCase.test.js
  test/lib/usecases/run/UpdateRunUseCase.test.js
  test/public/dataPasses/overviewPerLhcPeriod.test.js
  test/public/defaults.js
  test/public/lhcPeriods/overview.test.js
  test/public/runs/detail.test.js
  test/public/runs/overview.test.js
  test/public/runs/runsPerDataPass.overview.test.js
  test/public/runs/runsPerPeriod.overview.test.js
  test/public/runs/runsPerSimulationPass.overview.test.js
Labels: frontend, backend

#1729 [O2B-1363] Interpretation of MC.Reproducible flag type as not-bad
  lib/database/repositories/QcFlagRepository.js
  lib/public/views/Runs/RunPerDataPass/RunsPerDataPassOverviewModel.js
  lib/public/views/Runs/RunPerDataPass/RunsPerDataPassOverviewPage.js
  lib/server/controllers/qcFlag.controller.js
  lib/server/services/qualityControlFlag/QcFlagService.js
  test/api/qcFlags.test.js
  test/lib/server/services/qualityControlFlag/QcFlagService.test.js
  test/public/runs/runsPerDataPass.overview.test.js
Labels: frontend, backend

#1720 [O2B-1359] Display of synchronous flags at Runs Per LHC Period view
  lib/public/components/common/badge.js
  lib/public/components/common/colors.js
  lib/public/components/qcFlags/qcSummaryColors.js
  lib/public/views/Runs/ActiveColumns/getQcSummaryDisplay.js
  lib/public/views/Runs/ActiveColumns/runDetectorsQualitiesActiveColumns.js
  lib/public/views/Runs/ActiveColumns/runDetectorsSyncQcActiveColumns.js
  lib/public/views/Runs/RunPerPeriod/RunsPerLhcPeriodOverviewModel.js
  lib/public/views/Runs/RunPerPeriod/RunsPerLhcPeriodOverviewPage.js
  lib/public/views/Runs/RunsModel.js
  lib/public/views/Runs/format/formatDetectorQuality.js
  test/public/defaults.js
  test/public/runs/index.js
  test/public/runs/runsPerLhcPeriod.overview.test.js
  test/scripts/test-runs.js
Labels: frontend

#1709 [O2B-1353] Refactor RCT services after removing Dpl detectors
  lib/database/migrations/20240724134539-migrate-dpl-detectors-to-detectors.js
  lib/database/seeders/20221005120315-detector.js
  lib/domain/enums/DetectorTypes.js
  lib/public/domain/enums/DetectorTypes.js
  lib/server/services/detector/getQcDetectorOrFail.js
  lib/server/services/dpl/getOrCreateDplDetector.js
  lib/server/services/gaq/GaqDetectorsService.js
  lib/server/services/qualityControlFlag/QcFlagService.js
  test/lib/server/services/detector/getAllDetectors.test.js
Labels: backend
