Repository AliceO2Group/Bookkeeping, pull requests merged in 2025-01, with the labels that each got.

#1827 [O2B-831] Update ca-certificates for docker
  Dockerfile
Labels: dependencies

#1809 [O2B-1405] Additional query parameters for creating a log
  lib/public/views/Logs/Create/TemplatedLogCreationModel.js
  lib/public/views/Logs/Create/templates/OnCallLogTemplate.js
  lib/public/views/Logs/Create/templates/onCallLogCreationConfiguration.js
  lib/public/views/Logs/LogsModel.js
  test/public/logs/create.test.js
Labels: backend, javascript

#1829 [O2B-831] Update ca-certificates for docker
  Dockerfile
Labels: dependencies, docker

#1830 Fix QC flags tests
  lib/public/components/qcFlags/qcFlagsBreadcrumbs.js
  lib/public/views/DataPasses/PerSimulationPassOverview/DataPassesPerSimulationPassOverviewPage.js
  lib/public/views/Runs/RunPerDataPass/RunsPerDataPassOverviewPage.js
  lib/public/views/Runs/RunsPerSimulationPass/RunsPerSimulationPassOverviewPage.js
  lib/public/views/SimulationPasses/AnchoredOverview/AnchoredSimulationPassesOverviewPage.js
  lib/public/views/SimulationPasses/PerLhcPeriodOverview/SimulationPassesPerLhcPeriodOverviewPage.js
  test/public/qcFlags/forDataPassCreation.test.js
  test/public/qcFlags/forDataPassOverview.test.js
  test/public/qcFlags/forSimulationPassCreation.test.js
  test/public/qcFlags/forSimulationPassOverview.test.js
  test/public/qcFlags/gaqOverview.test.js
  test/public/qcFlags/synchronousOverview.test.js
  test/public/simulationPasses/overviewAnchoredSimulationPasses.test.js
Labels: frontend

#1820 [O2B-1056] bookkeeping error page
  lib/public/Model.js
  lib/public/view.js
  lib/public/views/Error/ErrorModel.js
  lib/public/views/Error/index.js
  test/public/error/error.test.js
  test/public/error/index.js
  test/public/index.js
Labels: frontend

#1836 Release 1.5.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#1834 [O2B-1290] multi run flagging backend
  lib/server/controllers/qcFlag.controller.js
  lib/server/routers/qcFlag.router.js
  test/api/qcFlags.test.js
Labels: backend

#1831 Fix home frontend tests randomly failing
  lib/public/views/Home/Overview/HomePage.js
  test/public/home/overview.test.js
Labels: frontend

#1810 [O2B-719] Add range based filtering for run number
  lib/domain/dtos/filters/RunFilterDto.js
  lib/usecases/run/GetAllRunsUseCase.js
  test/api/runs.test.js
  test/lib/usecases/run/GetAllRunsUseCase.test.js
Labels: backend

#1805 [O2B-1139] Refresh tags list when a tag is updated/created
  lib/database/seeders/20200511151010-tags.js
  lib/public/views/Runs/Details/RunDetailsModel.js
  test/api/logs.test.js
  test/public/runs/detail.test.js
Labels: bug, frontend

#1838 [O2B-1420] Add CTP readout host to FLP hosts
  lib/database/seeders/20220412122043-environments.js
  lib/server/services/run/RunService.js
  test/lib/server/services/run/RunService.test.js
  test/public/envs/detailsPage.test.js
Labels: backend

#1839 [O2B-912] Display user that started/stopped run
  lib/database/adapters/RunAdapter.js
  lib/database/adapters/UserAdapter.js
  lib/database/adapters/index.js
  lib/database/models/run.js
  lib/database/models/typedefs/SequelizeRun.js
  lib/database/seeders/20200713103855-runs.js
  lib/domain/entities/Run.js
  lib/public/views/Runs/Details/runDetailsComponent.js
  lib/usecases/run/GetRunUseCase.js
  test/lib/usecases/run/GetRunUseCase.test.js
  test/public/runs/detail.test.js
Labels: frontend

#832 [O2B-536] Create a reusable filtering system
  lib/public/components/Filters/common/FilterModel.js
  lib/public/components/Filters/common/FilteringModel.js
  lib/public/components/Filters/common/TagFilterModel.js
  lib/public/components/Filters/common/filters/remoteDataTagFilter.js
  lib/public/components/common/selection/SelectionModel.js
  lib/public/views/Home/Overview/HomePage.js
  lib/public/views/Logs/ActiveColumns/logsActiveColumns.js
  lib/public/views/Logs/Overview/LogsOverviewModel.js
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
  lib/public/views/Runs/Overview/RunsOverviewModel.js
  test/public/runs/overview.test.js
Labels: frontend

#1793 [O2B-1393] Use certificate when handling lost runs and envs
  lib/application.js
  lib/config/services.js
  lib/server/externalServicesSynchronization/monalisa/MonAlisaClient.js
  lib/server/services/housekeeping/handleLostRunsAndEnvironments.js
Labels: bug

#1842 Fix QC flag types randomly failing
  test/public/defaults.js
  test/public/qcFlagTypes/creation.test.js
Labels: backend

#1828 [O2B-536] Minor improvements to selection dropdown
  lib/public/components/Filters/common/combinationOperatorChoiceComponent.js
  lib/public/components/Filters/common/filters/ComparisonSelectionModel.js
  lib/public/components/Filters/common/filters/FloatComparisonFilterModel.js
  lib/public/components/common/selection/SelectionModel.js
  lib/public/components/common/selection/dropdown/selectionDropdown.js
Labels: frontend

#1843 [O2B-536] Improve runs overview runs type filter
  lib/public/components/runTypes/RunTypesFilterModel.js
  lib/public/components/runTypes/RunTypesSelectionDropdownModel.js
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
  lib/public/views/Runs/Overview/RunsOverviewModel.js
Labels: frontend

#1844 [O2B-536] Improve runs overview EOR reasons filter
  lib/public/components/Filters/RunsFilter/DetectorsFilterModel.js
  lib/public/components/Filters/RunsFilter/EorReasonFilterModel.js
  lib/public/components/Filters/RunsFilter/EorReasonsFilterModel.js
  lib/public/components/Filters/RunsFilter/eorReasonFilter.js
  lib/public/components/Filters/common/TagFilterModel.js
  lib/public/components/detector/ObservableBasedSelectionDropdownModel.js
  lib/public/components/runEorReasons/runEorReasonSelection.js
  lib/public/components/runTypes/RunTypesFilterModel.js
  lib/public/services/eorReason/eorReasonTypeProvider.js
  lib/public/services/runTypes/runTypesProvider.js
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
  lib/public/views/Runs/Overview/RunsOverviewModel.js
  test/public/runs/overview.test.js
Labels: frontend

#1845 [O2B-536] Improve runs overview start/stop filters
  lib/public/components/Filters/RunsFilter/TimeRangeFilter.js
  lib/public/components/Filters/RunsFilter/o2StartFilter.js
  lib/public/components/Filters/RunsFilter/o2StopFilter.js
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
  lib/public/views/Runs/Overview/RunsOverviewModel.js
Labels: frontend
