Repository AliceO2Group/Bookkeeping, pull requests merged in 2025-04, with the labels that each got.

#1879 Use qcTimeStart and qcTimeEnd in QC flags chart
  lib/database/adapters/RunAdapter.js
  lib/public/views/QcFlags/qcFlagsVisualization/qcFlagsChartComponent.js
Labels: frontend, backend

#1880 Fix glitch in flags chart display height
  lib/public/views/QcFlags/ForDataPass/QcFlagsForDataPassOverviewPage.js
  lib/public/views/QcFlags/qcFlagsVisualization/qcFlagsChartComponent.js
  test/public/qcFlags/detailsForDataPass.test.js
Labels: bug, frontend

#1877 [O2B-1407] Refactoring of QC flags display
  lib/public/components/common/errorAlert.js
  lib/public/components/qcFlags/qcFlagCreationPanelLink.js
  lib/public/components/qcFlags/qcFlagsBreadcrumbs.js
  lib/public/services/detectors/remoteDplDetectorUserHasAccessTo.js
  lib/public/views/QcFlags/ActiveColumns/gaqFlagsActiveColumns.js
  lib/public/views/QcFlags/ForDataPass/QcFlagsForDataPassOverviewPage.js
  lib/public/views/QcFlags/ForSimulationPass/QcFlagsForSimulationPassOverviewPage.js
  lib/public/views/QcFlags/GaqFlags/GaqFlagsOverviewPage.js
  lib/public/views/QcFlags/Synchronous/SynchronousQcFlagsOverviewPage.js
  lib/public/views/Runs/ActiveColumns/runDetectorsAsyncQcActiveColumns.js
  lib/public/views/Runs/RunPerDataPass/RunsPerDataPassOverviewPage.js
  lib/public/views/Runs/RunsPerSimulationPass/RunsPerSimulationPassOverviewPage.js
  lib/server/services/qualityControlFlag/QcFlagTypeService.js
  test/public/qcFlags/forDataPassCreation.test.js
  test/public/runs/detail.test.js
  test/public/runs/runsPerDataPass.overview.test.js
Labels: frontend

#1885 [O2B-1437] Refactor gRPC service definition
  lib/server/GRPCServer.js
  lib/server/gRPC/bindGRPCController.js
  test/gRPC/serviceImplementation.test.js
Labels: backend

#1881 [O2B-1407] Add possibility to lock RCT flags
  lib/database/adapters/DataPassAdapter.js
  lib/database/migrations/v1/20250328072732-add-datapass-freeze-flag.js
  lib/database/models/dataPass.js
  lib/database/models/typedefs/SequelizeDataPass.js
  lib/database/models/typedefs/SequelizeQcFlagVerification.js
  lib/domain/entities/DataPass.js
  lib/domain/entities/qcFlagVerification.js
  lib/public/components/qcFlags/qcFlagCreationPanelLink.js
  lib/public/views/QcFlags/Create/QcFlagCreationModel.js
  lib/public/views/QcFlags/Create/forDataPass/QcFlagCreationForDataPassPage.js
  lib/public/views/Runs/ActiveColumns/runDetectorsAsyncQcActiveColumns.js
  lib/public/views/Runs/RunPerDataPass/RunsPerDataPassOverviewModel.js
  lib/public/views/Runs/RunPerDataPass/RunsPerDataPassOverviewPage.js
  lib/server/controllers/dataPasses.controller.js
  lib/server/externalServicesSynchronization/monalisa/MonAlisaClient.js
  lib/server/routers/dataPasses.router.js
  lib/server/services/dataPasses/DataPassService.js
  lib/server/services/qualityControlFlag/QcFlagService.js
  lib/server/services/run/RunService.js
  lib/server/services/simulationPasses/SimulationPassService.js
  test/api/dataPasses.test.js
  test/api/qcFlags.test.js
  test/lib/server/services/dataPasses/DataPassService.test.js
  test/lib/server/services/qualityControlFlag/QcFlagService.test.js
  test/public/runs/runsPerDataPass.overview.test.js
Labels: frontend, backend

#1887 Release 1.9.0
  CHANGELOG.md
  database/CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#1889 Rework attachments and test screenshots storage
  database/.gitignore
  database/populate/create-databases.sql
  docker-compose.test-parallel-base.yml
  docker-compose.yml
  docker/.gitignore
  docker/database/CHANGELOG.md
  docker/database/configuration/my.cnf
  docker/database/populate/create-databases.sql
  docker/database/populate/create-user.sql
  docker/storage/.gitkeep
  docs/DEVELOPMENT.md
  lib/config/database.js
  lib/server/middleware/multer.middleware.js
Labels: docker

#1878 [O2B-1440] Use trigger to update flags on run boundaries change
  lib/database/migrations/v1/20250328151300-add-qc-flag-boundaries-update-trigger.js
  lib/server/services/qualityControlFlag/QcFlagService.js
  test/lib/server/services/run/updateRun.test.js
Labels: DB
