Repository AliceO2Group/Bookkeeping, pull requests merged in 2025-02, with the labels that each got.

#1847 [OGUI-1610] Bump NodeJS to v22 for GH Actions
  .github/workflows/bookkeeping.yml
  .github/workflows/release.yml
  Dockerfile
  docs/DEVELOPMENT.md
  package-lock.json
  package.json
  test/public/defaults.js
Labels: CI

#1846 [O2B-536] Improve runs overview magnets filter
  lib/domain/dtos/filters/RunFilterDto.js
  lib/public/components/Filters/RunsFilter/AliceL3AndDipoleFilteringModel.js
  lib/public/components/Filters/RunsFilter/MagnetsFilteringModel.js
  lib/public/components/common/selection/dropdown/SelectionDropdownModel.js
  lib/public/components/detector/ObservableBasedSelectionDropdownModel.js
  lib/public/services/magnets/magnetsCurrentLevelsProvider.js
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
  lib/public/views/Runs/Overview/RunsOverviewModel.js
  lib/server/services/run/RunService.js
  lib/usecases/run/GetAllRunsUseCase.js
  test/api/runs.test.js
  test/lib/server/services/run/RunService.test.js
  test/lib/usecases/run/GetAllRunsUseCase.test.js
Labels: frontend

#1848 [O2B-1427] Store trigger configuration per runs
  cxx-client/CMakeLists.txt
  cxx-client/example/exampleSpecificServices.cxx
  cxx-client/include/BookkeepingApi/BkpClient.h
  cxx-client/include/BookkeepingApi/RunServiceClient.h
  cxx-client/src/grpc/GrpcBkpClient.cxx
  cxx-client/src/grpc/GrpcBkpClient.h
  cxx-client/src/grpc/services/GrpcQcFlagServiceClient.cxx
  cxx-client/src/grpc/services/GrpcRunServiceClient.cxx
  cxx-client/src/grpc/services/GrpcRunServiceClient.h
  lib/database/adapters/RunAdapter.js
  lib/database/migrations/20250210110228-add-trigger-raw-configuration.js
  lib/database/models/run.js
  lib/database/models/typedefs/SequelizeRun.js
  lib/database/seeders/20200713103855-runs.js
  lib/domain/dtos/UpdateRunByRunNumberDto.js
  lib/domain/entities/Run.js
  lib/public/views/Runs/Details/RunDetailsModel.js
  lib/public/views/Runs/Details/runDetailsComponent.js
  proto/common.proto
  proto/run.proto
  test/api/runs.test.js
  test/lib/server/services/run/RunService.test.js
  test/lib/usecases/run/UpdateRunUseCase.test.js
  test/public/runs/detail.test.js
Labels: frontend, backend

#1850 [O2B-536] Improve runs overview inelastic interaction rates filtering
  lib/public/components/Filters/common/filters/ComparisonSelectionModel.js
  lib/public/components/Filters/common/filters/FloatComparisonFilterModel.js
  lib/public/components/Filters/common/filters/NumericalComparisonFilterModel.js
  lib/public/components/Filters/common/filters/ProcessedTextInputModel.js
  lib/public/components/Filters/common/filters/amountFilter.js
  lib/public/components/Filters/common/filters/floatNumberFilter.js
  lib/public/components/Filters/common/filters/numericalComparisonFilter.js
  lib/public/views/Runs/ActiveColumns/inelasticInteractionRateActiveColumnsForPbPb.js
  lib/public/views/Runs/ActiveColumns/inelasticInteractionRateActiveColumnsForProtonProton.js
  lib/public/views/Runs/Overview/RunsOverviewModel.js
  lib/public/views/Runs/RunPerDataPass/RunsPerDataPassOverviewModel.js
  lib/public/views/Runs/RunPerDataPass/RunsPerDataPassOverviewPage.js
  test/public/runs/runsPerDataPass.overview.test.js
Labels: frontend

#1852 [O2B-536] Improve runs overview run number filter
  lib/public/components/Filters/RunsFilter/runNumbersFilter.js
  lib/public/components/Filters/common/filters/RawTextFilterModel.js
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
  lib/public/views/Runs/Overview/RunsOverviewModel.js
  lib/public/views/Runs/Overview/RunsOverviewPage.js
  lib/public/views/Runs/RunPerDataPass/RunsPerDataPassOverviewPage.js
  test/public/runs/detail.test.js
  test/public/runs/overview.test.js
  test/public/runs/runsPerDataPass.overview.test.js
Labels: frontend

#1853 [O2B-1430] Rename trigger counters to CTP trigger counters
  cxx-client/CMakeLists.txt
  cxx-client/example/exampleSpecificServices.cxx
  cxx-client/include/BookkeepingApi/BkpClient.h
  cxx-client/include/BookkeepingApi/CtpTriggerCountersServiceClient.h
  cxx-client/src/grpc/GrpcBkpClient.cxx
  cxx-client/src/grpc/GrpcBkpClient.h
  cxx-client/src/grpc/services/GrpcCtpTriggerCountersServiceClient.cxx
  cxx-client/src/grpc/services/GrpcCtpTriggerCountersServiceClient.h
  lib/database/adapters/CtpTriggerCountersAdapter.js
  lib/database/adapters/index.js
  lib/database/migrations/20250211085415-rename-trigger-counters-to-ctp-trigger-counters.js
  lib/database/models/ctpTriggerCounters.js
  lib/database/models/index.js
  lib/database/models/typedefs/SequelizeCtpTriggerCounters.js
  lib/database/repositories/CtpTriggerCountersRepository.js
  lib/database/repositories/index.js
  lib/database/seeders/20240603124221-add-trigger-counters.js
  lib/domain/entities/CtpTriggerCounters.js
  lib/public/views/Runs/Details/RunDetailsModel.js
  lib/public/views/Runs/Details/runDetailsComponent.js
  lib/server/controllers/ctpTriggerCounters.controller.js
  lib/server/controllers/gRPC/GRPCCtpTriggerCountersController.js
  lib/server/controllers/index.js
  lib/server/gRPC/servicesImplementationsMappings.js
  lib/server/routers/ctpTriggerCounters.router.js
  lib/server/routers/index.js
  lib/server/routers/triggerCounters.router.js
  lib/server/services/ctpTriggerCounters/CtpTriggerCountersService.js
  proto/ctpTriggerCounters.proto
  test/api/ctpTriggerCounters.test.js
  test/api/index.js
  test/lib/server/services/ctpTriggerCounters/CtpTriggerCountersService.test.js
  test/lib/server/services/ctpTriggerCounters/index.js
  test/lib/server/services/index.js
  test/lib/server/services/triggerCounters/index.js
  test/public/runs/detail.test.js
Labels: backend

#1825 [O2B-536] Improve runs overview run definition filter
  lib/database/seeders/20200508094502-logs.js
  lib/public/components/Filters/RunsFilter/RunDefinitionFilterModel.js
  lib/public/components/Filters/RunsFilter/definitionFilter.js
  lib/public/components/Filters/RunsFilter/runDefinitionFilter.js
  lib/public/components/Filters/common/filters/SelectionFilterModel.js
  lib/public/components/common/selection/SelectionModel.js
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
  lib/public/views/Runs/Overview/RunsOverviewModel.js
  lib/public/views/Runs/Overview/RunsOverviewPage.js
  test/public/logs/detail.test.js
  test/public/runs/overview.test.js
Labels: frontend

#1833 [O2B-1290] Multi run flagging frontend
  lib/public/Model.js
  lib/public/app.css
  lib/public/components/qcFlags/getRunQcExclusionReason.js
  lib/public/components/qcFlags/isRunNotSubjectToQc.js
  lib/public/components/qcFlags/qcFlagCreationPanelLink.js
  lib/public/components/qcFlags/qcFlagOverviewPanelLink.js
  lib/public/components/qcFlags/qcFlagsBreadcrumbs.js
  lib/public/services/detectors/detectorsProvider.js
  lib/public/services/run/runsProvider.js
  lib/public/views/QcFlags/Create/QcFlagCreationModel.js
  lib/public/views/QcFlags/Create/forDataPass/QcFlagCreationForDataPassModel.js
  lib/public/views/QcFlags/Create/forDataPass/QcFlagCreationForDataPassPage.js
  lib/public/views/QcFlags/Create/forSimulationPass/QcFlagCreationForSimulationPassModel.js
  lib/public/views/QcFlags/Create/forSimulationPass/QcFlagCreationForSimulationPassPage.js
  lib/public/views/QcFlags/Create/qcFlagCreationComponent.js
  lib/public/views/QcFlags/ForDataPass/QcFlagsForDataPassOverviewPage.js
  lib/public/views/QcFlags/ForSimulationPass/QcFlagsForSimulationPassOverviewPage.js
  lib/public/views/QcFlags/QcFlagsModel.js
  lib/public/views/Runs/ActiveColumns/runDetectorsAsyncQcActiveColumns.js
  lib/public/views/Runs/ActiveColumns/runDetectorsSyncQcActiveColumns.js
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
  lib/public/views/Runs/RunDetectorsSelectionModel.js
  lib/public/views/Runs/RunPerDataPass/RunsPerDataPassOverviewModel.js
  lib/public/views/Runs/RunPerDataPass/RunsPerDataPassOverviewPage.js
  lib/public/views/Runs/RunPerPeriod/RunsPerLhcPeriodOverviewPage.js
  lib/public/views/Runs/RunsModel.js
  lib/public/views/Runs/RunsPerSimulationPass/RunsPerSimulationPassOverviewModel.js
  lib/public/views/Runs/RunsPerSimulationPass/RunsPerSimulationPassOverviewPage.js
  lib/public/views/Runs/format/formatRunEnd.js
  lib/public/views/Runs/format/formatRunStart.js
  test/public/qcFlags/forDataPassCreation.test.js
  test/public/qcFlags/forDataPassOverview.test.js
  test/public/qcFlags/forSimulationPassCreation.test.js
  test/public/qcFlags/gaqOverview.test.js
  test/public/runs/runsPerDataPass.overview.test.js
  test/public/runs/runsPerSimulationPass.overview.test.js
Labels: frontend

#1854 [O2B-536] Improve runs overview fill number filter
  lib/public/components/Filters/RunsFilter/fillNumbers.js
  lib/public/components/Filters/RunsFilter/runNumbersFilter.js
  lib/public/components/Filters/common/filters/RawTextFilterModel.js
  lib/public/components/Filters/common/filters/rawTextFilter.js
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
  lib/public/views/Runs/Overview/RunsOverviewModel.js
  test/public/runs/overview.test.js
Labels: frontend

#1855 [O2B-536] Improve runs overview LHC periods filter
  lib/public/components/Filters/RunsFilter/lhcPeriod.js
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
  lib/public/views/Runs/Overview/RunsOverviewModel.js
Labels: frontend

#1856 [O2B-536] Improve runs overview duration filter
  lib/public/components/Filters/RunsFilter/durationFilter.js
  lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
  lib/public/views/Runs/Overview/RunsOverviewModel.js
  lib/public/views/Runs/RunPerDataPass/RunsPerDataPassOverviewPage.js
  test/public/runs/overview.test.js
  test/public/runs/runsPerDataPass.overview.test.js
Labels: frontend

#1858 Release 1.6.0
  CHANGELOG.md
  database/CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#1861 [O2B-1428] Discard flags instead of delete
  .eslintrc
  lib/database/adapters/QcFlagAdapter.js
  lib/database/migrations/v1/20250217075020-add-qc-flags-deleted-flag.js
  lib/database/models/qcFlag.js
  lib/database/models/typedefs/SequelizeQcFlag.js
  lib/database/repositories/QcFlagRepository.js
  lib/database/seeders/20240404100811-qc-flags.js
  lib/domain/entities/QcFlag.js
  lib/public/app.css
  lib/public/components/common/form/deleteButton.js
  lib/public/views/QcFlags/ActiveColumns/qcFlagsActiveColumns.js
  lib/public/views/QcFlags/ForDataPass/QcFlagsForDataPassOverviewPage.js
  lib/public/views/QcFlags/details/qcFlagDetailsComponent.js
  lib/server/services/qualityControlFlag/QcFlagService.js
  test/api/qcFlags.test.js
  test/lib/server/services/qualityControlFlag/QcFlagService.test.js
  test/public/qcFlags/detailsForDataPass.test.js
  test/public/qcFlags/detailsForSimulationPass.test.js
Labels: frontend, backend

#1866 [O2B-1429] Added button to discard all QC flags per data pass
  lib/domain/enums/BkpRoles.js
  lib/public/domain/enums/BkpRoles.js
  lib/public/models/UserRoleSelectionModel.js
  lib/public/views/QcFlagTypes/Create/QcFlagTypeCreationPage.js
  lib/public/views/QcFlagTypes/Overview/QcFlagTypesOverviewPage.js
  lib/public/views/QcFlags/details/qcFlagDetailsComponent.js
  lib/public/views/Runs/Overview/exportRunsTriggerAndModal.js
  lib/public/views/Runs/RunPerDataPass/RunsPerDataPassOverviewModel.js
  lib/public/views/Runs/RunPerDataPass/RunsPerDataPassOverviewPage.js
  lib/public/views/Tags/Create/index.js
  lib/public/views/Tags/Details/tagDetailsComponent.js
  lib/server/controllers/qcFlag.controller.js
  lib/server/routers/qcFlag.router.js
  lib/server/services/qualityControlFlag/QcFlagService.js
  test/api/qcFlags.test.js
  test/lib/server/services/qualityControlFlag/QcFlagService.test.js
  test/public/runs/runsPerDataPass.overview.test.js
Labels: frontend, backend

#1865 [O2B-1290] Fix run detectors selection in runs per data-pass overview
  lib/public/views/Runs/RunDetectorsSelectionModel.js
  test/public/qcFlags/forDataPassCreation.test.js
  test/public/runs/runsPerDataPass.overview.test.js
Labels: frontend

#1860 [O2B-1412] Configure kafka to retry indefinitely
  .eslintrc
  lib/application.js
  lib/server/kafka/AliEcsSynchronizer.js
  lib/server/kafka/InfologgerKafkaLogCreator.js
  test/public/defaults.js
  test/public/runs/runsPerDataPass.overview.test.js
Labels: backend

#1868 Release 1.7.0
  CHANGELOG.md
  database/CHANGELOG.md
  package-lock.json
  package.json
Labels: release
