Repository AliceO2Group/Bookkeeping, pull requests merged in 2025-07, with the labels that each got.

#1929 Update failing dependency
  Dockerfile
Labels: docker

#1930 Npm dependencies update
  package-lock.json
  package.json
Labels: dependencies

#1808 [O2B-1365] Implement GAQ periods views
  lib/database/migrations/v1/20250518123000-create-gaq-views.js
  lib/database/repositories/QcFlagRepository.js
  lib/domain/entities/QcSummary.js
  lib/domain/enums/QcSummaryProperties.js
  lib/server/services/qualityControlFlag/GaqService.js
  lib/server/services/qualityControlFlag/QcFlagSummaryService.js
  test/lib/server/services/qualityControlFlag/QcFlagService.test.js
  test/public/qcFlags/index.js
Labels: backend, DB

#1931 [O2B-1452] Add filter option by creation date interval for retrieving environments
  lib/domain/dtos/GetAllEnvironmentsDto.js
  lib/usecases/environment/GetAllEnvironmentsUseCase.js
  test/api/environments.test.js
  test/lib/usecases/environment/GetAllEnvironmentsUseCase.test.js
Labels: backend

#1904 [O2B-1365] Disable GAQ for not fully covered runs
  lib/database/repositories/QcFlagRepository.js
  lib/database/seeders/20240404100811-qc-flags.js
  lib/database/seeders/20240716124000-gaq-detectors.js
  lib/domain/entities/QcSummary.js
  lib/domain/enums/QcSummaryProperties.js
  lib/public/views/QcFlags/ActiveColumns/gaqFlagsActiveColumns.js
  lib/public/views/Runs/RunPerDataPass/RunsPerDataPassOverviewModel.js
  lib/public/views/Runs/RunPerDataPass/RunsPerDataPassOverviewPage.js
  lib/server/services/qualityControlFlag/GaqService.js
  test/api/qcFlags.test.js
  test/api/runs.test.js
  test/lib/server/services/qualityControlFlag/QcFlagService.test.js
  test/lib/usecases/run/GetAllRunsUseCase.test.js
  test/public/qcFlags/gaqOverview.test.js
  test/public/runs/runsPerDataPass.overview.test.js
Labels: frontend, backend, DB

#1939 [O2B-1454] Use colliding bunches from LHC_FILLS if available
  lib/database/adapters/RunAdapter.js
  lib/database/seeders/20220503120937-lhc-fills.js
  test/public/lhcFills/detail.test.js
  test/public/runs/detail.test.js
Labels: backend

#1940 [O2B-1240] Display only physical productions by default and adds filtering for 'test' and 'debug' productions display
  lib/database/seeders/20240112102011-data-passes.js
  lib/domain/enums/NonPhysicsProductionsNamesRoles.js
  lib/public/components/Filters/common/FilteringModel.js
  lib/public/components/Filters/common/filters/TextTokensFilterModel.js
  lib/public/components/Filters/common/filtersPanelPopover.js
  lib/public/domain/enums/NonPhysicsProductionsNamesWords.js
  lib/public/utilities/expandNestedKey.js
  lib/public/view.js
  lib/public/views/DataPasses/ActiveColumns/dataPassesActiveColumns.js
  lib/public/views/DataPasses/DataPassesOverviewModel.js
  lib/public/views/DataPasses/PerLhcPeriodOverview/DataPassesPerLhcPeriodOverviewModel.js
  lib/public/views/DataPasses/PerLhcPeriodOverview/DataPassesPerLhcPeriodOverviewPage.js
  lib/public/views/DataPasses/PerSimulationPassOverview/DataPassesPerSimulationPassOverviewModel.js
  lib/public/views/DataPasses/PerSimulationPassOverview/DataPassesPerSimulationPassOverviewPage.js
  lib/public/views/QcFlagTypes/Overview/QcFlagTypesOverviewModel.js
  lib/public/views/SimulationPasses/AnchoredOverview/AnchoredSimulationPassesOverviewModel.js
  lib/public/views/SimulationPasses/PerLhcPeriodOverview/SimulationPassesPerLhcPeriodOverviewModel.js
  lib/public/views/lhcPeriods/Overview/LhcPeriodsOverviewModel.js
  lib/server/controllers/dataPasses.controller.js
  lib/server/services/dataPasses/DataPassService.js
  lib/server/services/lhcPeriod/LhcPeriodStatisticsService.js
  test/api/dataPasses.test.js
  test/lib/server/externalServicesSynchronization/monalisa/MonAlisaSynchronizer.test.js
  test/public/dataPasses/overviewPerLhcPeriod.test.js
  test/public/dataPasses/overviewPerSimulationPass.test.js
Labels: frontend, backend
